// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag Managed Application.

package managedapplication

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "managed-application" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "managed-application",
		Short: "Managed Application operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newManagedApplicationDeleteCmd(),
		newManagedApplicationGetCmd(),
		newManagedApplicationListCmd(),
		newManagedApplicationAppEventsCmd(),
		newManagedApplicationAppUsersCmd(),
		newManagedApplicationUpdateCmd(),
	)
	return c
}

// newManagedApplicationDeleteCmd — DELETE /saas/v1/orgs/{orgId}/managed-apps/{managedAppId} (operationId: Saas_Managed_Application_delete)
func newManagedApplicationDeleteCmd() *cobra.Command {
	var (
		managedAppID string
		dryRun       bool
		yes          bool
	)
	c := &cobra.Command{
		Use:   "delete",
		Short: "Delete managed application",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(managedAppID) == "" {
				return fmt.Errorf("--managed-app-id is required")
			}
			writePlan := map[string]any{"method": "DELETE /saas/v1/orgs/{orgId}/managed-apps/{managedAppId}"}
			writePlan["orgId"] = deps.Config.OrgID
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, true, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.SaasManagedApplicationDeleteWithResponse(cmd.Context(), deps.Config.OrgID, managedAppID)
			if err != nil {
				return err
			}
			if resp.StatusCode() >= 300 {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			fmt.Fprintln(deps.Stdout, "OK")
			return nil
		},
	}
	c.Flags().StringVar(&managedAppID, "managed-app-id", "", "managedAppId (path, required)")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newManagedApplicationGetCmd — GET /saas/v1/orgs/{orgId}/managed-apps/{managedAppId} (operationId: Saas_Managed_Application_show)
func newManagedApplicationGetCmd() *cobra.Command {
	var (
		managedAppID string
		view         string
	)
	c := &cobra.Command{
		Use:   "get",
		Short: "Show managed application",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(managedAppID) == "" {
				return fmt.Errorf("--managed-app-id is required")
			}
			params := flexera.SaasManagedApplicationShowParams{}
			if cmd.Flags().Changed("view") {
				ev := flexera.SaasManagedApplicationShowParamsView(view)
				params.View = &ev
			}
			resp, err := client.SaasManagedApplicationShowWithResponse(cmd.Context(), deps.Config.OrgID, managedAppID, &params)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringVar(&managedAppID, "managed-app-id", "", "managedAppId (path, required)")
	c.Flags().StringVar(&view, "view", "", "view (query)")
	return c
}

// newManagedApplicationListCmd — GET /saas/v1/orgs/{orgId}/managed-apps (operationId: Saas_Managed_Application_index)
func newManagedApplicationListCmd() *cobra.Command {
	var (
		view       string
		filter     string
		orderBy    string
		noPaginate bool
		skipToken  string
	)
	c := &cobra.Command{
		Use:   "list",
		Short: "List managed applications",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			params := flexera.SaasManagedApplicationIndexParams{}
			if cmd.Flags().Changed("view") {
				ev := flexera.SaasManagedApplicationIndexParamsView(view)
				params.View = &ev
			}
			if cmd.Flags().Changed("filter") {
				v := filter
				params.Filter = &v
			}
			if cmd.Flags().Changed("order-by") {
				v := orderBy
				params.OrderBy = &v
			}
			var initialSkipToken *string
			if t := strings.TrimSpace(skipToken); t != "" {
				initialSkipToken = &t
			}
			result, err := flexera.CollectPages(cmd.Context(), noPaginate, initialSkipToken,
				func(ctx context.Context, st *string) (any, error) {
					p := params
					p.SkipToken = st
					resp, callErr := client.SaasManagedApplicationIndexWithResponse(ctx, deps.Config.OrgID, &p)
					if callErr != nil {
						return nil, callErr
					}
					if resp.JSON200 == nil {
						return nil, flexera.ResponseError(resp.StatusCode(), resp.Body)
					}
					return resp.JSON200, nil
				})
			if err != nil {
				return err
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
		},
	}
	c.Flags().StringVar(&view, "view", "", "view (query)")
	c.Flags().StringVar(&filter, "filter", "", "filter (query)")
	c.Flags().StringVar(&orderBy, "order-by", "", "orderBy (query)")
	c.Flags().BoolVar(&noPaginate, "no-paginate", false, "return only the first page (do not follow nextPage)")
	c.Flags().StringVar(&skipToken, "skip-token", "", "resume pagination from this token")
	return c
}

// newManagedApplicationAppEventsCmd — GET /saas/v1/orgs/{orgId}/managed-apps/{managedAppId}/app-events (operationId: Saas_Managed_Application_indexEvents)
func newManagedApplicationAppEventsCmd() *cobra.Command {
	var (
		managedAppID         string
		mostRecentEventsOnly bool
		noPaginate           bool
		skipToken            string
	)
	c := &cobra.Command{
		Use:   "app-events",
		Short: "List managed application's events",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(managedAppID) == "" {
				return fmt.Errorf("--managed-app-id is required")
			}
			params := flexera.SaasManagedApplicationIndexEventsParams{}
			if cmd.Flags().Changed("most-recent-events-only") {
				v := mostRecentEventsOnly
				params.MostRecentEventsOnly = &v
			}
			var initialSkipToken *string
			if t := strings.TrimSpace(skipToken); t != "" {
				initialSkipToken = &t
			}
			result, err := flexera.CollectPages(cmd.Context(), noPaginate, initialSkipToken,
				func(ctx context.Context, st *string) (any, error) {
					p := params
					p.SkipToken = st
					resp, callErr := client.SaasManagedApplicationIndexEventsWithResponse(ctx, deps.Config.OrgID, managedAppID, &p)
					if callErr != nil {
						return nil, callErr
					}
					if resp.JSON200 == nil {
						return nil, flexera.ResponseError(resp.StatusCode(), resp.Body)
					}
					return resp.JSON200, nil
				})
			if err != nil {
				return err
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
		},
	}
	c.Flags().StringVar(&managedAppID, "managed-app-id", "", "managedAppId (path, required)")
	c.Flags().BoolVar(&mostRecentEventsOnly, "most-recent-events-only", false, "mostRecentEventsOnly (query)")
	c.Flags().BoolVar(&noPaginate, "no-paginate", false, "return only the first page (do not follow nextPage)")
	c.Flags().StringVar(&skipToken, "skip-token", "", "resume pagination from this token")
	return c
}

// newManagedApplicationAppUsersCmd — GET /saas/v1/orgs/{orgId}/managed-apps/{managedAppId}/app-users (operationId: Saas_Managed_Application_indexUsers)
func newManagedApplicationAppUsersCmd() *cobra.Command {
	var (
		managedAppID string
		view         string
		includeAll   bool
		noPaginate   bool
		skipToken    string
	)
	c := &cobra.Command{
		Use:   "app-users",
		Short: "List managed application's users",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(managedAppID) == "" {
				return fmt.Errorf("--managed-app-id is required")
			}
			params := flexera.SaasManagedApplicationIndexUsersParams{}
			if cmd.Flags().Changed("view") {
				ev := flexera.SaasManagedApplicationIndexUsersParamsView(view)
				params.View = &ev
			}
			if cmd.Flags().Changed("include-all") {
				v := includeAll
				params.IncludeAll = &v
			}
			var initialSkipToken *string
			if t := strings.TrimSpace(skipToken); t != "" {
				initialSkipToken = &t
			}
			result, err := flexera.CollectPages(cmd.Context(), noPaginate, initialSkipToken,
				func(ctx context.Context, st *string) (any, error) {
					p := params
					p.SkipToken = st
					resp, callErr := client.SaasManagedApplicationIndexUsersWithResponse(ctx, deps.Config.OrgID, managedAppID, &p)
					if callErr != nil {
						return nil, callErr
					}
					if resp.JSON200 == nil {
						return nil, flexera.ResponseError(resp.StatusCode(), resp.Body)
					}
					return resp.JSON200, nil
				})
			if err != nil {
				return err
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
		},
	}
	c.Flags().StringVar(&managedAppID, "managed-app-id", "", "managedAppId (path, required)")
	c.Flags().StringVar(&view, "view", "", "view (query)")
	c.Flags().BoolVar(&includeAll, "include-all", false, "includeAll (query)")
	c.Flags().BoolVar(&noPaginate, "no-paginate", false, "return only the first page (do not follow nextPage)")
	c.Flags().StringVar(&skipToken, "skip-token", "", "resume pagination from this token")
	return c
}

// newManagedApplicationUpdateCmd — PATCH /saas/v1/orgs/{orgId}/managed-apps/{managedAppId} (operationId: Saas_Managed_Application_update)
func newManagedApplicationUpdateCmd() *cobra.Command {
	var (
		managedAppID       string
		bodyRaw            string
		fActivityThreshold int
		fDescription       string
		fIsActive          bool
		fName              string
		fPointOfContact    string
		dryRun             bool
		yes                bool
	)
	c := &cobra.Command{
		Use:   "update",
		Short: "Update managed application",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(managedAppID) == "" {
				return fmt.Errorf("--managed-app-id is required")
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("activity-threshold") {
				fields["activityThreshold"] = fActivityThreshold
			}
			if cmd.Flags().Changed("description") {
				fields["description"] = fDescription
			}
			if cmd.Flags().Changed("is-active") {
				fields["isActive"] = fIsActive
			}
			if cmd.Flags().Changed("name") {
				fields["name"] = fName
			}
			if cmd.Flags().Changed("point-of-contact") {
				fields["pointOfContact"] = fPointOfContact
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.SaasManagedApplicationUpdateJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			writePlan := map[string]any{"method": "PATCH /saas/v1/orgs/{orgId}/managed-apps/{managedAppId}"}
			writePlan["orgId"] = deps.Config.OrgID
			writePlan["body"] = json.RawMessage(raw)
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, false, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.SaasManagedApplicationUpdateWithResponse(cmd.Context(), deps.Config.OrgID, managedAppID, body)
			if err != nil {
				return err
			}
			if resp.StatusCode() >= 300 {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			fmt.Fprintln(deps.Stdout, "OK")
			return nil
		},
	}
	c.Flags().StringVar(&managedAppID, "managed-app-id", "", "managedAppId (path, required)")
	c.Flags().IntVar(&fActivityThreshold, "activity-threshold", 0, "activityThreshold (body)")
	c.Flags().StringVar(&fDescription, "description", "", "description (body)")
	c.Flags().BoolVar(&fIsActive, "is-active", false, "isActive (body)")
	c.Flags().StringVar(&fName, "name", "", "name (body)")
	c.Flags().StringVar(&fPointOfContact, "point-of-contact", "", "pointOfContact (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}
