// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag org_dashboards.

package orgdashboards

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "org-dashboards" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "org-dashboards",
		Short: "org_dashboards operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newOrgDashboardsCreateCmd(),
		newOrgDashboardsDeleteCmd(),
		newOrgDashboardsGetCmd(),
		newOrgDashboardsListCmd(),
		newOrgDashboardsReplaceCmd(),
	)
	return c
}

// newOrgDashboardsCreateCmd — POST /bill-analysis/orgs/{orgId}/dashboards (operationId: BillAnalysis_org_dashboards_create)
func newOrgDashboardsCreateCmd() *cobra.Command {
	var (
		bodyRaw     string
		fArea       string
		fName       string
		fScope      []string
		fVisibility string
		dryRun      bool
		yes         bool
	)
	c := &cobra.Command{
		Use:   "create",
		Short: "create org_dashboards",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("area") {
				fields["area"] = fArea
			}
			if cmd.Flags().Changed("name") {
				fields["name"] = fName
			}
			if cmd.Flags().Changed("scope") {
				fields["scope"] = fScope
			}
			if cmd.Flags().Changed("visibility") {
				fields["visibility"] = fVisibility
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.BillAnalysisOrgDashboardsCreateJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			writePlan := map[string]any{"method": "POST /bill-analysis/orgs/{orgId}/dashboards"}
			writePlan["orgId"] = deps.Config.OrgID
			writePlan["body"] = json.RawMessage(raw)
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, false, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.BillAnalysisOrgDashboardsCreateWithResponse(cmd.Context(), int64(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			if resp.JSON201 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON201)
		},
	}
	c.Flags().StringVar(&fArea, "area", "", "area (body)")
	c.Flags().StringVar(&fName, "name", "", "name (body)")
	c.Flags().StringSliceVar(&fScope, "scope", nil, "scope (body)")
	c.Flags().StringVar(&fVisibility, "visibility", "", "visibility (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newOrgDashboardsDeleteCmd — DELETE /bill-analysis/orgs/{orgId}/dashboards/{id} (operationId: BillAnalysis_org_dashboards_destroy)
func newOrgDashboardsDeleteCmd() *cobra.Command {
	var (
		id     string
		dryRun bool
		yes    bool
	)
	c := &cobra.Command{
		Use:   "delete",
		Short: "destroy org_dashboards",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			writePlan := map[string]any{"method": "DELETE /bill-analysis/orgs/{orgId}/dashboards/{id}"}
			writePlan["orgId"] = deps.Config.OrgID
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, true, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.BillAnalysisOrgDashboardsDestroyWithResponse(cmd.Context(), int64(deps.Config.OrgID), id)
			if err != nil {
				return err
			}
			if resp.StatusCode() != 204 {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			fmt.Fprintln(deps.Stdout, "OK")
			return nil
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newOrgDashboardsGetCmd — GET /bill-analysis/orgs/{orgId}/dashboards/{id} (operationId: BillAnalysis_org_dashboards_show)
func newOrgDashboardsGetCmd() *cobra.Command {
	var (
		id string
	)
	c := &cobra.Command{
		Use:   "get",
		Short: "show org_dashboards",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			resp, err := client.BillAnalysisOrgDashboardsShowWithResponse(cmd.Context(), int64(deps.Config.OrgID), id)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	return c
}

// newOrgDashboardsListCmd — GET /bill-analysis/orgs/{orgId}/dashboards (operationId: BillAnalysis_org_dashboards_index)
func newOrgDashboardsListCmd() *cobra.Command {
	var (
		area       string
		visibility string
	)
	c := &cobra.Command{
		Use:   "list",
		Short: "index org_dashboards",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			params := flexera.BillAnalysisOrgDashboardsIndexParams{}
			if cmd.Flags().Changed("area") {
				v := area
				params.Area = &v
			}
			if cmd.Flags().Changed("visibility") {
				ev := flexera.BillAnalysisOrgDashboardsIndexParamsVisibility(visibility)
				params.Visibility = &ev
			}
			resp, err := client.BillAnalysisOrgDashboardsIndexWithResponse(cmd.Context(), int64(deps.Config.OrgID), &params)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringVar(&area, "area", "", "area (query)")
	c.Flags().StringVar(&visibility, "visibility", "", "visibility (query)")
	return c
}

// newOrgDashboardsReplaceCmd — PUT /bill-analysis/orgs/{orgId}/dashboards/{id} (operationId: BillAnalysis_org_dashboards_replace)
func newOrgDashboardsReplaceCmd() *cobra.Command {
	var (
		id          string
		bodyRaw     string
		fArea       string
		fName       string
		fScope      []string
		fVisibility string
		dryRun      bool
		yes         bool
	)
	c := &cobra.Command{
		Use:   "replace",
		Short: "replace org_dashboards",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("area") {
				fields["area"] = fArea
			}
			if cmd.Flags().Changed("name") {
				fields["name"] = fName
			}
			if cmd.Flags().Changed("scope") {
				fields["scope"] = fScope
			}
			if cmd.Flags().Changed("visibility") {
				fields["visibility"] = fVisibility
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.BillAnalysisOrgDashboardsReplaceJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			writePlan := map[string]any{"method": "PUT /bill-analysis/orgs/{orgId}/dashboards/{id}"}
			writePlan["orgId"] = deps.Config.OrgID
			writePlan["body"] = json.RawMessage(raw)
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, false, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.BillAnalysisOrgDashboardsReplaceWithResponse(cmd.Context(), int64(deps.Config.OrgID), id, body)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	c.Flags().StringVar(&fArea, "area", "", "area (body)")
	c.Flags().StringVar(&fName, "name", "", "name (body)")
	c.Flags().StringSliceVar(&fScope, "scope", nil, "scope (body)")
	c.Flags().StringVar(&fVisibility, "visibility", "", "visibility (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}
