// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag regulatory-compliance.

package regulatorycompliance

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "regulatory-compliance" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "regulatory-compliance",
		Short: "regulatory-compliance operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newRegulatoryComplianceAssetStatisticsCmd(),
		newRegulatoryComplianceFilterCmd(),
		newRegulatoryComplianceLifecycleForecastCmd(),
		newRegulatoryComplianceLifecycleTrendCmd(),
	)
	return c
}

// newRegulatoryComplianceAssetStatisticsCmd — POST /risk/v1/orgs/{orgId}/regulatory-compliance/asset-statistics (operationId: Risk_get_asset_statistics_risk_v1_orgs_orgId_regulatory_compliance_asset_statistics_post)
func newRegulatoryComplianceAssetStatisticsCmd() *cobra.Command {
	var (
		bodyRaw  string
		fMetrics []string
		dryRun   bool
		yes      bool
	)
	c := &cobra.Command{
		Use:   "asset-statistics",
		Short: "Regulatory Compliance Asset Statistics",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("metrics") {
				fields["metrics"] = fMetrics
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.RiskGetAssetStatisticsRiskV1OrgsOrgIdRegulatoryComplianceAssetStatisticsPostJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			writePlan := map[string]any{"method": "POST /risk/v1/orgs/{orgId}/regulatory-compliance/asset-statistics"}
			writePlan["orgId"] = deps.Config.OrgID
			writePlan["body"] = json.RawMessage(raw)
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, false, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.RiskGetAssetStatisticsRiskV1OrgsOrgIdRegulatoryComplianceAssetStatisticsPostWithResponse(cmd.Context(), fmt.Sprint(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringSliceVar(&fMetrics, "metrics", nil, "metrics (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newRegulatoryComplianceFilterCmd — POST /risk/v1/orgs/{orgId}/regulatory-compliance/catalog/filter (operationId: Risk_get_catalog_filter_risk_v1_orgs_orgId_regulatory_compliance_catalog_filter_post)
func newRegulatoryComplianceFilterCmd() *cobra.Command {
	var (
		bodyRaw     string
		fDimensions []string
		dryRun      bool
		yes         bool
	)
	c := &cobra.Command{
		Use:   "filter",
		Short: "Regulatory Compliance Catalog Filter",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("dimensions") {
				fields["dimensions"] = fDimensions
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.RiskGetCatalogFilterRiskV1OrgsOrgIdRegulatoryComplianceCatalogFilterPostJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			writePlan := map[string]any{"method": "POST /risk/v1/orgs/{orgId}/regulatory-compliance/catalog/filter"}
			writePlan["orgId"] = deps.Config.OrgID
			writePlan["body"] = json.RawMessage(raw)
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, false, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.RiskGetCatalogFilterRiskV1OrgsOrgIdRegulatoryComplianceCatalogFilterPostWithResponse(cmd.Context(), fmt.Sprint(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringSliceVar(&fDimensions, "dimensions", nil, "dimensions (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newRegulatoryComplianceLifecycleForecastCmd — POST /risk/v1/orgs/{orgId}/regulatory-compliance/lifecycle-forecast (operationId: Risk_get_lifecycle_forecast_risk_v1_orgs_orgId_regulatory_compliance_lifecycle_forecast_post)
func newRegulatoryComplianceLifecycleForecastCmd() *cobra.Command {
	var (
		bodyRaw          string
		fIncludeStatuses []string
		dryRun           bool
		yes              bool
	)
	c := &cobra.Command{
		Use:   "lifecycle-forecast",
		Short: "Regulatory Compliance Lifecycle Forecast",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("include-statuses") {
				fields["includeStatuses"] = fIncludeStatuses
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.RiskGetLifecycleForecastRiskV1OrgsOrgIdRegulatoryComplianceLifecycleForecastPostJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			writePlan := map[string]any{"method": "POST /risk/v1/orgs/{orgId}/regulatory-compliance/lifecycle-forecast"}
			writePlan["orgId"] = deps.Config.OrgID
			writePlan["body"] = json.RawMessage(raw)
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, false, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.RiskGetLifecycleForecastRiskV1OrgsOrgIdRegulatoryComplianceLifecycleForecastPostWithResponse(cmd.Context(), fmt.Sprint(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringSliceVar(&fIncludeStatuses, "include-statuses", nil, "includeStatuses (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newRegulatoryComplianceLifecycleTrendCmd — POST /risk/v1/orgs/{orgId}/regulatory-compliance/lifecycle-trend (operationId: Risk_get_lifecycle_trend_risk_v1_orgs_orgId_regulatory_compliance_lifecycle_trend_post)
func newRegulatoryComplianceLifecycleTrendCmd() *cobra.Command {
	var (
		bodyRaw string
		dryRun  bool
		yes     bool
	)
	c := &cobra.Command{
		Use:   "lifecycle-trend",
		Short: "Regulatory Compliance Lifecycle Trend",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			fields := map[string]any{}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.RiskGetLifecycleTrendRiskV1OrgsOrgIdRegulatoryComplianceLifecycleTrendPostJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			writePlan := map[string]any{"method": "POST /risk/v1/orgs/{orgId}/regulatory-compliance/lifecycle-trend"}
			writePlan["orgId"] = deps.Config.OrgID
			writePlan["body"] = json.RawMessage(raw)
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, false, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.RiskGetLifecycleTrendRiskV1OrgsOrgIdRegulatoryComplianceLifecycleTrendPostWithResponse(cmd.Context(), fmt.Sprint(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}
