// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag Processing History.

package processinghistory

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "processing-history" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "processing-history",
		Short: "Processing History operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newProcessingHistoryListCmd(),
		newProcessingHistoryDownloadCmd(),
		newProcessingHistoryUpdateCmd(),
	)
	return c
}

// newProcessingHistoryListCmd — GET /finops-onboarding/v1/orgs/{orgId}/processing/bill-months (operationId: FinopsOnboarding_Processing_History_index)
func newProcessingHistoryListCmd() *cobra.Command {
	var (
		limit      int
		orderBy    string
		filter     string
		noPaginate bool
		skipToken  string
	)
	c := &cobra.Command{
		Use:   "list",
		Short: "List enterprise bill months",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			params := flexera.FinopsOnboardingProcessingHistoryIndexParams{}
			if cmd.Flags().Changed("limit") {
				v := limit
				params.Limit = &v
			}
			if cmd.Flags().Changed("order-by") {
				v := orderBy
				params.OrderBy = &v
			}
			if cmd.Flags().Changed("filter") {
				v := filter
				params.Filter = &v
			}
			var initialSkipToken *string
			if t := strings.TrimSpace(skipToken); t != "" {
				initialSkipToken = &t
			}
			result, err := flexera.CollectPages(cmd.Context(), noPaginate, initialSkipToken,
				func(ctx context.Context, st *string) (any, error) {
					p := params
					p.SkipToken = st
					resp, callErr := client.FinopsOnboardingProcessingHistoryIndexWithResponse(ctx, deps.Config.OrgID, &p)
					if callErr != nil {
						return nil, callErr
					}
					if resp.JSON200 == nil {
						return nil, flexera.ResponseError(resp.StatusCode(), resp.Body)
					}
					return resp.JSON200, nil
				})
			if err != nil {
				return err
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
		},
	}
	c.Flags().IntVar(&limit, "limit", 0, "limit (query)")
	c.Flags().StringVar(&orderBy, "order-by", "", "orderBy (query)")
	c.Flags().StringVar(&filter, "filter", "", "filter (query)")
	c.Flags().BoolVar(&noPaginate, "no-paginate", false, "return only the first page (do not follow nextPage)")
	c.Flags().StringVar(&skipToken, "skip-token", "", "resume pagination from this token")
	return c
}

// newProcessingHistoryDownloadCmd — GET /finops-onboarding/v1/orgs/{orgId}/processing/bill-months/download (operationId: FinopsOnboarding_Processing_History_download)
func newProcessingHistoryDownloadCmd() *cobra.Command {
	var (
		downloadToken string
		format        string
	)
	c := &cobra.Command{
		Use:   "download",
		Short: "Download enterprise bill months in CSV",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			params := flexera.FinopsOnboardingProcessingHistoryDownloadParams{}
			if cmd.Flags().Changed("download-token") {
				params.DownloadToken = downloadToken
			}
			if cmd.Flags().Changed("format") {
				ev := flexera.FinopsOnboardingProcessingHistoryDownloadParamsFormat(format)
				params.Format = &ev
			}
			resp, err := client.FinopsOnboardingProcessingHistoryDownloadWithResponse(cmd.Context(), deps.Config.OrgID, &params)
			if err != nil {
				return err
			}
			if resp.StatusCode() >= 300 {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			fmt.Fprintln(deps.Stdout, "OK")
			return nil
		},
	}
	c.Flags().StringVar(&downloadToken, "download-token", "", "downloadToken (query)")
	c.Flags().StringVar(&format, "format", "", "format (query)")
	return c
}

// newProcessingHistoryUpdateCmd — PATCH /finops-onboarding/v1/orgs/{orgId}/processing/bill-months (operationId: FinopsOnboarding_Processing_History_reprocess)
func newProcessingHistoryUpdateCmd() *cobra.Command {
	var (
		bodyRaw string
		fAction string
		dryRun  bool
		yes     bool
	)
	c := &cobra.Command{
		Use:   "update",
		Short: "Reprocess one or more enterprise bill months",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("action") {
				fields["action"] = fAction
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.FinopsOnboardingProcessingHistoryReprocessJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			writePlan := map[string]any{"method": "PATCH /finops-onboarding/v1/orgs/{orgId}/processing/bill-months"}
			writePlan["orgId"] = deps.Config.OrgID
			writePlan["body"] = json.RawMessage(raw)
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, false, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.FinopsOnboardingProcessingHistoryReprocessWithResponse(cmd.Context(), deps.Config.OrgID, body)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringVar(&fAction, "action", "", "action (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}
