// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag BillUpload.

package billupload

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/google/uuid"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "bill-upload" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "bill-upload",
		Short: "BillUpload operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newBillUploadFilesCmd(),
		newBillUploadOperationsCmd(),
		newBillUploadCreateCmd(),
		newBillUploadDeleteCmd(),
		newBillUploadGetCmd(),
		newBillUploadListCmd(),
	)
	return c
}

// newBillUploadFilesCmd — POST /optima/orgs/{orgId}/billUploads/{billUploadId}/files/{fileId} (operationId: BillUpload_BillUpload_createFile)
func newBillUploadFilesCmd() *cobra.Command {
	var (
		billUploadID string
		fileID       string
	)
	c := &cobra.Command{
		Use:   "files",
		Short: "POST /optima/orgs/{orgId}/billUploads/{billUploadId}/files/{fileId}",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(billUploadID) == "" {
				return fmt.Errorf("--bill-upload-id is required")
			}
			if strings.TrimSpace(fileID) == "" {
				return fmt.Errorf("--file-id is required")
			}
			billUploadIDUUID, err := uuid.Parse(billUploadID)
			if err != nil {
				return fmt.Errorf("--bill-upload-id: invalid UUID: %w", err)
			}
			resp, err := client.BillUploadBillUploadCreateFileWithResponse(cmd.Context(), deps.Config.OrgID, billUploadIDUUID, fileID)
			if err != nil {
				return err
			}
			if resp.StatusCode() >= 300 {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			fmt.Fprintln(deps.Stdout, "OK")
			return nil
		},
	}
	c.Flags().StringVar(&billUploadID, "bill-upload-id", "", "billUploadId (path, required)")
	c.Flags().StringVar(&fileID, "file-id", "", "fileId (path, required)")
	return c
}

// newBillUploadOperationsCmd — POST /optima/orgs/{orgId}/billUploads/{billUploadId}/operations (operationId: BillUpload_BillUpload_createOperation)
func newBillUploadOperationsCmd() *cobra.Command {
	var (
		billUploadID string
		bodyRaw      string
		fOperation   string
	)
	c := &cobra.Command{
		Use:   "operations",
		Short: "POST /optima/orgs/{orgId}/billUploads/{billUploadId}/operations",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(billUploadID) == "" {
				return fmt.Errorf("--bill-upload-id is required")
			}
			billUploadIDUUID, err := uuid.Parse(billUploadID)
			if err != nil {
				return fmt.Errorf("--bill-upload-id: invalid UUID: %w", err)
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("operation") {
				fields["operation"] = fOperation
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.BillUploadBillUploadCreateOperationJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			resp, err := client.BillUploadBillUploadCreateOperationWithResponse(cmd.Context(), deps.Config.OrgID, billUploadIDUUID, body)
			if err != nil {
				return err
			}
			if resp.StatusCode() >= 300 {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			fmt.Fprintln(deps.Stdout, "OK")
			return nil
		},
	}
	c.Flags().StringVar(&billUploadID, "bill-upload-id", "", "billUploadId (path, required)")
	c.Flags().StringVar(&fOperation, "operation", "", "operation (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	return c
}

// newBillUploadCreateCmd — POST /optima/orgs/{orgId}/billUploads (operationId: BillUpload_BillUpload_create)
func newBillUploadCreateCmd() *cobra.Command {
	var (
		bodyRaw        string
		fBillConnectID string
		fBillingPeriod string
		dryRun         bool
		yes            bool
	)
	c := &cobra.Command{
		Use:   "create",
		Short: "POST /optima/orgs/{orgId}/billUploads",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("bill-connect-id") {
				fields["billConnectId"] = fBillConnectID
			}
			if cmd.Flags().Changed("billing-period") {
				fields["billingPeriod"] = fBillingPeriod
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.BillUploadBillUploadCreateJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			writePlan := map[string]any{"method": "POST /optima/orgs/{orgId}/billUploads"}
			writePlan["orgId"] = deps.Config.OrgID
			writePlan["body"] = json.RawMessage(raw)
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, false, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.BillUploadBillUploadCreateWithResponse(cmd.Context(), deps.Config.OrgID, body)
			if err != nil {
				return err
			}
			if resp.StatusCode() >= 300 {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			fmt.Fprintln(deps.Stdout, "OK")
			return nil
		},
	}
	c.Flags().StringVar(&fBillConnectID, "bill-connect-id", "", "billConnectId (body)")
	c.Flags().StringVar(&fBillingPeriod, "billing-period", "", "billingPeriod (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newBillUploadDeleteCmd — DELETE /optima/orgs/{orgId}/billUploads/{billUploadId} (operationId: BillUpload_BillUpload_delete)
func newBillUploadDeleteCmd() *cobra.Command {
	var (
		billUploadID string
		dryRun       bool
		yes          bool
	)
	c := &cobra.Command{
		Use:   "delete",
		Short: "DELETE /optima/orgs/{orgId}/billUploads/{billUploadId}",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(billUploadID) == "" {
				return fmt.Errorf("--bill-upload-id is required")
			}
			billUploadIDUUID, err := uuid.Parse(billUploadID)
			if err != nil {
				return fmt.Errorf("--bill-upload-id: invalid UUID: %w", err)
			}
			writePlan := map[string]any{"method": "DELETE /optima/orgs/{orgId}/billUploads/{billUploadId}"}
			writePlan["orgId"] = deps.Config.OrgID
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, true, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.BillUploadBillUploadDeleteWithResponse(cmd.Context(), deps.Config.OrgID, billUploadIDUUID)
			if err != nil {
				return err
			}
			if resp.StatusCode() != 204 {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			fmt.Fprintln(deps.Stdout, "OK")
			return nil
		},
	}
	c.Flags().StringVar(&billUploadID, "bill-upload-id", "", "billUploadId (path, required)")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newBillUploadGetCmd — GET /optima/orgs/{orgId}/billUploads/{billUploadId} (operationId: BillUpload_BillUpload_show)
func newBillUploadGetCmd() *cobra.Command {
	var (
		billUploadID string
	)
	c := &cobra.Command{
		Use:   "get",
		Short: "GET /optima/orgs/{orgId}/billUploads/{billUploadId}",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(billUploadID) == "" {
				return fmt.Errorf("--bill-upload-id is required")
			}
			billUploadIDUUID, err := uuid.Parse(billUploadID)
			if err != nil {
				return fmt.Errorf("--bill-upload-id: invalid UUID: %w", err)
			}
			resp, err := client.BillUploadBillUploadShowWithResponse(cmd.Context(), deps.Config.OrgID, billUploadIDUUID)
			if err != nil {
				return err
			}
			if resp.StatusCode() >= 300 {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			fmt.Fprintln(deps.Stdout, "OK")
			return nil
		},
	}
	c.Flags().StringVar(&billUploadID, "bill-upload-id", "", "billUploadId (path, required)")
	return c
}

// newBillUploadListCmd — GET /optima/orgs/{orgId}/billUploads (operationId: BillUpload_BillUpload_index)
func newBillUploadListCmd() *cobra.Command {
	var (
		billingPeriod string
		billConnectID string
	)
	c := &cobra.Command{
		Use:   "list",
		Short: "GET /optima/orgs/{orgId}/billUploads",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			params := flexera.BillUploadBillUploadIndexParams{}
			if cmd.Flags().Changed("billing-period") {
				v := billingPeriod
				params.BillingPeriod = &v
			}
			if cmd.Flags().Changed("bill-connect-id") {
				v := billConnectID
				params.BillConnectId = &v
			}
			resp, err := client.BillUploadBillUploadIndexWithResponse(cmd.Context(), deps.Config.OrgID, &params)
			if err != nil {
				return err
			}
			if resp.StatusCode() >= 300 {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			fmt.Fprintln(deps.Stdout, "OK")
			return nil
		},
	}
	c.Flags().StringVar(&billingPeriod, "billing-period", "", "billingPeriod (query)")
	c.Flags().StringVar(&billConnectID, "bill-connect-id", "", "billConnectId (query)")
	return c
}
