// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag Tag Dimension.

package tagdimension

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "tag-dimension" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "tag-dimension",
		Short: "Tag Dimension operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newTagDimensionCreateCmd(),
		newTagDimensionDeleteCmd(),
		newTagDimensionGetCmd(),
		newTagDimensionListCmd(),
		newTagDimensionReplaceCmd(),
	)
	return c
}

// newTagDimensionCreateCmd — POST /finops-customizations/v1/orgs/{orgId}/tag-dimensions (operationId: FinopsCustomizations_Tag_Dimension_create)
func newTagDimensionCreateCmd() *cobra.Command {
	var (
		bodyRaw     string
		fName       string
		dryRun      bool
		yes         bool
		interactive bool
	)
	c := &cobra.Command{
		Use:         "create",
		Short:       "Creates a tag dimension",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli tag-dimension create --org-id ORG_ID --body @request.json\n  flexera-cli tag-dimension create --org-id ORG_ID --body @request.json --dry-run\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema tag-dimension create --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "FinopsCustomizations_Tag_Dimension_create", "flexera.output": "structured", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if interactive {
				if err := clipkg.GuardInteractive(cmd, bodyRaw); err != nil {
					return err
				}
				if err := clipkg.GatherInteractiveParams(cmd, "FinopsCustomizations_Tag_Dimension_create"); err != nil {
					return err
				}
			}
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "FinopsCustomizations_Tag_Dimension_create")
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("name") {
				fields["name"] = fName
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				if !interactive {
					return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
				}
			}
			if interactive {
				raw, err = clipkg.GatherInteractiveBody(cmd, "FinopsCustomizations_Tag_Dimension_create", raw)
				if err != nil {
					return err
				}
			}
			var body flexera.FinopsCustomizationsTagDimensionCreateJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("FinopsCustomizations_Tag_Dimension_create", raw, &body, noValidate)
			if err != nil {
				return err
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "POST", Path: "/finops-customizations/v1/orgs/{orgId}/tag-dimensions", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			writePlan.Body, writePlan.Validation, writePlan.RequestSchema = effectiveBody, validation, requestSchema
			var writeDone bool
			var werr error
			if interactive {
				writeDone, werr = clipkg.ConfirmInteractive(cmd, dryRun, yes, writePlan, deps.Printer)
			} else {
				writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			}
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.FinopsCustomizationsTagDimensionCreateWithResponse(cmd.Context(), deps.Config.OrgID, body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 201:
				if resp.JSON201 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON201)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&fName, "name", "", "name (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	c.Flags().BoolVarP(&interactive, "interactive", "i", false, "edit inputs in a terminal form, review a plan and approve with typed yes")
	return c
}

// newTagDimensionDeleteCmd — DELETE /finops-customizations/v1/orgs/{orgId}/tag-dimensions/{id} (operationId: FinopsCustomizations_Tag_Dimension_delete)
func newTagDimensionDeleteCmd() *cobra.Command {
	var (
		id     string
		dryRun bool
		yes    bool
	)
	c := &cobra.Command{
		Use:         "delete",
		Short:       "Delete a tag dimension",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli tag-dimension delete --org-id ORG_ID --id ID\n  flexera-cli tag-dimension delete --org-id ORG_ID --id ID --dry-run",
		Annotations: map[string]string{"flexera.operationId": "FinopsCustomizations_Tag_Dimension_delete", "flexera.output": "text", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "FinopsCustomizations_Tag_Dimension_delete")
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "DELETE", Path: "/finops-customizations/v1/orgs/{orgId}/tag-dimensions/{id}", Params: planParams, Destructive: true}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			var writeDone bool
			var werr error
			writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.FinopsCustomizationsTagDimensionDeleteWithResponse(cmd.Context(), deps.Config.OrgID, id)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 204:
				fmt.Fprintln(deps.Stdout, "OK")
				return nil
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newTagDimensionGetCmd — GET /finops-customizations/v1/orgs/{orgId}/tag-dimensions/{id} (operationId: FinopsCustomizations_Tag_Dimension_show)
func newTagDimensionGetCmd() *cobra.Command {
	var (
		id string
	)
	c := &cobra.Command{
		Use:         "get",
		Short:       "Show a tag dimension",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli tag-dimension get --org-id ORG_ID --id ID",
		Annotations: map[string]string{"flexera.operationId": "FinopsCustomizations_Tag_Dimension_show", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "FinopsCustomizations_Tag_Dimension_show")
			if err != nil {
				return err
			}
			_ = effectiveParams
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.FinopsCustomizationsTagDimensionShowWithResponse(cmd.Context(), deps.Config.OrgID, id)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	return c
}

// newTagDimensionListCmd — GET /finops-customizations/v1/orgs/{orgId}/tag-dimensions (operationId: FinopsCustomizations_Tag_Dimension_index)
func newTagDimensionListCmd() *cobra.Command {
	c := &cobra.Command{
		Use:         "list",
		Short:       "Index tag dimensions",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli tag-dimension list --org-id ORG_ID",
		Annotations: map[string]string{"flexera.operationId": "FinopsCustomizations_Tag_Dimension_index", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "FinopsCustomizations_Tag_Dimension_index")
			if err != nil {
				return err
			}
			_ = effectiveParams
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.FinopsCustomizationsTagDimensionIndexWithResponse(cmd.Context(), deps.Config.OrgID)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	return c
}

// newTagDimensionReplaceCmd — PUT /finops-customizations/v1/orgs/{orgId}/tag-dimensions/{id} (operationId: FinopsCustomizations_Tag_Dimension_update)
func newTagDimensionReplaceCmd() *cobra.Command {
	var (
		id          string
		bodyRaw     string
		fName       string
		dryRun      bool
		yes         bool
		interactive bool
	)
	c := &cobra.Command{
		Use:         "replace",
		Short:       "Updates a tag dimension",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli tag-dimension replace --org-id ORG_ID --id ID --body @request.json\n  flexera-cli tag-dimension replace --org-id ORG_ID --id ID --body @request.json --dry-run\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema tag-dimension replace --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "FinopsCustomizations_Tag_Dimension_update", "flexera.output": "structured", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if interactive {
				if err := clipkg.GuardInteractive(cmd, bodyRaw); err != nil {
					return err
				}
				if err := clipkg.GatherInteractiveParams(cmd, "FinopsCustomizations_Tag_Dimension_update"); err != nil {
					return err
				}
			}
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "FinopsCustomizations_Tag_Dimension_update")
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("name") {
				fields["name"] = fName
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				if !interactive {
					return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
				}
			}
			if interactive {
				raw, err = clipkg.GatherInteractiveBody(cmd, "FinopsCustomizations_Tag_Dimension_update", raw)
				if err != nil {
					return err
				}
			}
			var body flexera.FinopsCustomizationsTagDimensionUpdateJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("FinopsCustomizations_Tag_Dimension_update", raw, &body, noValidate)
			if err != nil {
				return err
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "PUT", Path: "/finops-customizations/v1/orgs/{orgId}/tag-dimensions/{id}", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			writePlan.Body, writePlan.Validation, writePlan.RequestSchema = effectiveBody, validation, requestSchema
			var writeDone bool
			var werr error
			if interactive {
				writeDone, werr = clipkg.ConfirmInteractive(cmd, dryRun, yes, writePlan, deps.Printer)
			} else {
				writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			}
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.FinopsCustomizationsTagDimensionUpdateWithResponse(cmd.Context(), deps.Config.OrgID, id, body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	c.Flags().StringVar(&fName, "name", "", "name (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	c.Flags().BoolVarP(&interactive, "interactive", "i", false, "edit inputs in a terminal form, review a plan and approve with typed yes")
	return c
}
