// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag Policy Manager.

package policymanager

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "policy-manager" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "policy-manager",
		Short: "Policy Manager operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newPolicyManagerCreateCmd(),
		newPolicyManagerDeleteCmd(),
		newPolicyManagerGetCmd(),
		newPolicyManagerListCmd(),
		newPolicyManagerSummaryCmd(),
		newPolicyManagerUpdateCmd(),
		newPolicyManagerUpdateTemplateCmd(),
	)
	return c
}

// newPolicyManagerCreateCmd — POST /policy/v1/orgs/{orgId}/policy-managers (operationId: Policy_Policy_Manager_create)
func newPolicyManagerCreateCmd() *cobra.Command {
	var (
		bodyRaw            string
		fAllowDeletePolicy bool
		fAllowEditPolicy   bool
		fDescription       string
		fDryRun            bool
		fLogLevel          string
		fName              string
		fOrgTagsFilter     string
		fSeverity          string
		fSkipApprovals     bool
		fTemplateRef       string
		dryRun             bool
		yes                bool
		interactive        bool
	)
	c := &cobra.Command{
		Use:         "create",
		Short:       "Create a Policy Manager",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli policy policy-manager create --org-id ORG_ID --body @request.json\n  flexera-cli policy policy-manager create --org-id ORG_ID --body @request.json --dry-run\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema policy policy-manager create --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "Policy_Policy_Manager_create", "flexera.output": "text", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if interactive {
				if err := clipkg.GuardInteractive(cmd, bodyRaw); err != nil {
					return err
				}
				if err := clipkg.GatherInteractiveParams(cmd, "Policy_Policy_Manager_create"); err != nil {
					return err
				}
			}
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Policy_Policy_Manager_create")
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("allow-delete-policy") {
				fields["allowDeletePolicy"] = fAllowDeletePolicy
			}
			if cmd.Flags().Changed("allow-edit-policy") {
				fields["allowEditPolicy"] = fAllowEditPolicy
			}
			if cmd.Flags().Changed("description") {
				fields["description"] = fDescription
			}
			if cmd.Flags().Changed("body-dry-run") {
				fields["dryRun"] = fDryRun
			}
			if cmd.Flags().Changed("log-level") {
				fields["logLevel"] = fLogLevel
			}
			if cmd.Flags().Changed("name") {
				fields["name"] = fName
			}
			if cmd.Flags().Changed("org-tags-filter") {
				fields["orgTagsFilter"] = fOrgTagsFilter
			}
			if cmd.Flags().Changed("severity") {
				fields["severity"] = fSeverity
			}
			if cmd.Flags().Changed("skip-approvals") {
				fields["skipApprovals"] = fSkipApprovals
			}
			if cmd.Flags().Changed("template-ref") {
				fields["templateRef"] = fTemplateRef
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				if !interactive {
					return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
				}
			}
			if interactive {
				raw, err = clipkg.GatherInteractiveBody(cmd, "Policy_Policy_Manager_create", raw)
				if err != nil {
					return err
				}
			}
			var body flexera.PolicyPolicyManagerCreateJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("Policy_Policy_Manager_create", raw, &body, noValidate)
			if err != nil {
				return err
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "POST", Path: "/policy/v1/orgs/{orgId}/policy-managers", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			writePlan.Body, writePlan.Validation, writePlan.RequestSchema = effectiveBody, validation, requestSchema
			var writeDone bool
			var werr error
			if interactive {
				writeDone, werr = clipkg.ConfirmInteractive(cmd, dryRun, yes, writePlan, deps.Printer)
			} else {
				writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			}
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.PolicyPolicyManagerCreateWithResponse(cmd.Context(), int64(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 201:
				fmt.Fprintln(deps.Stdout, "OK")
				return nil
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().BoolVar(&fAllowDeletePolicy, "allow-delete-policy", false, "allowDeletePolicy (body)")
	c.Flags().BoolVar(&fAllowEditPolicy, "allow-edit-policy", false, "allowEditPolicy (body)")
	c.Flags().StringVar(&fDescription, "description", "", "description (body)")
	c.Flags().BoolVar(&fDryRun, "body-dry-run", false, "dryRun (body)")
	c.Flags().StringVar(&fLogLevel, "log-level", "", "logLevel (body)")
	c.Flags().StringVar(&fName, "name", "", "name (body)")
	c.Flags().StringVar(&fOrgTagsFilter, "org-tags-filter", "", "orgTagsFilter (body)")
	c.Flags().StringVar(&fSeverity, "severity", "", "severity (body)")
	c.Flags().BoolVar(&fSkipApprovals, "skip-approvals", false, "skipApprovals (body)")
	c.Flags().StringVar(&fTemplateRef, "template-ref", "", "templateRef (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	c.Flags().BoolVarP(&interactive, "interactive", "i", false, "edit inputs in a terminal form, review a plan and approve with typed yes")
	return c
}

// newPolicyManagerDeleteCmd — DELETE /policy/v1/orgs/{orgId}/policy-managers/{id} (operationId: Policy_Policy_Manager_delete)
func newPolicyManagerDeleteCmd() *cobra.Command {
	var (
		id     string
		dryRun bool
		yes    bool
	)
	c := &cobra.Command{
		Use:         "delete",
		Short:       "Delete a policy manager",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli policy policy-manager delete --org-id ORG_ID --id ID\n  flexera-cli policy policy-manager delete --org-id ORG_ID --id ID --dry-run",
		Annotations: map[string]string{"flexera.operationId": "Policy_Policy_Manager_delete", "flexera.output": "text", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Policy_Policy_Manager_delete")
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "DELETE", Path: "/policy/v1/orgs/{orgId}/policy-managers/{id}", Params: planParams, Destructive: true}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			var writeDone bool
			var werr error
			writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.PolicyPolicyManagerDeleteWithResponse(cmd.Context(), int64(deps.Config.OrgID), id)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 204:
				fmt.Fprintln(deps.Stdout, "OK")
				return nil
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newPolicyManagerGetCmd — GET /policy/v1/orgs/{orgId}/policy-managers/{id} (operationId: Policy_Policy_Manager_show)
func newPolicyManagerGetCmd() *cobra.Command {
	var (
		id   string
		view string
	)
	c := &cobra.Command{
		Use:         "get",
		Short:       "Get a policy manager",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli policy policy-manager get --org-id ORG_ID --id ID",
		Annotations: map[string]string{"flexera.operationId": "Policy_Policy_Manager_show", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Policy_Policy_Manager_show")
			if err != nil {
				return err
			}
			_ = effectiveParams
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			params := flexera.PolicyPolicyManagerShowParams{}
			if cmd.Flags().Changed("view") {
				ev := flexera.PolicyPolicyManagerShowParamsView(view)
				params.View = &ev
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.PolicyPolicyManagerShowWithResponse(cmd.Context(), int64(deps.Config.OrgID), id, &params)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	c.Flags().StringVar(&view, "view", "", "view (query)")
	return c
}

// newPolicyManagerListCmd — GET /policy/v1/orgs/{orgId}/policy-managers (operationId: Policy_Policy_Manager_index)
func newPolicyManagerListCmd() *cobra.Command {
	var (
		filter             string
		orderBy            string
		limit              int64
		includeTerminating bool
		noPaginate         bool
		skipToken          string
	)
	c := &cobra.Command{
		Use:         "list",
		Short:       "List policy managers",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli policy policy-manager list --org-id ORG_ID",
		Annotations: map[string]string{"flexera.operationId": "Policy_Policy_Manager_index", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Policy_Policy_Manager_index")
			if err != nil {
				return err
			}
			_ = effectiveParams
			params := flexera.PolicyPolicyManagerIndexParams{}
			if cmd.Flags().Changed("filter") {
				v := filter
				params.Filter = &v
			}
			if cmd.Flags().Changed("order-by") {
				v := orderBy
				params.OrderBy = &v
			}
			if cmd.Flags().Changed("limit") {
				v := limit
				params.Limit = &v
			}
			if cmd.Flags().Changed("include-terminating") {
				v := includeTerminating
				params.IncludeTerminating = &v
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			var initialSkipToken *string
			if t := strings.TrimSpace(skipToken); t != "" {
				initialSkipToken = &t
			}
			result, err := flexera.CollectPages(cmd.Context(), noPaginate, initialSkipToken,
				func(ctx context.Context, st *string) (any, error) {
					p := params
					p.SkipToken = st
					resp, callErr := client.PolicyPolicyManagerIndexWithResponse(ctx, int64(deps.Config.OrgID), &p)
					if callErr != nil {
						return nil, callErr
					}
					switch resp.StatusCode() {
					case 200:
						if resp.JSON200 != nil {
							if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
								return resp.JSON200, nil
							}
							return clipkg.DecodeResponseJSON(resp.Body)
						}
					}
					return nil, flexera.ResponseError(resp.StatusCode(), resp.Body)
				})
			if err != nil {
				return err
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
		},
	}
	c.Flags().StringVar(&filter, "filter", "", "filter (query)")
	c.Flags().StringVar(&orderBy, "order-by", "", "orderBy (query)")
	c.Flags().Int64Var(&limit, "limit", 0, "limit (query)")
	c.Flags().BoolVar(&includeTerminating, "include-terminating", false, "includeTerminating (query)")
	c.Flags().BoolVar(&noPaginate, "no-paginate", false, "return only the first page (do not follow nextPage)")
	c.Flags().StringVar(&skipToken, "skip-token", "", "resume pagination from this token")
	return c
}

// newPolicyManagerSummaryCmd — GET /policy/v1/orgs/{orgId}/policy-managers/{id}/summary (operationId: Policy_Policy_Manager_summary)
func newPolicyManagerSummaryCmd() *cobra.Command {
	var (
		id string
	)
	c := &cobra.Command{
		Use:         "summary",
		Short:       "Retrieve Summary by Organization",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli policy policy-manager summary --org-id ORG_ID --id ID",
		Annotations: map[string]string{"flexera.operationId": "Policy_Policy_Manager_summary", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Policy_Policy_Manager_summary")
			if err != nil {
				return err
			}
			_ = effectiveParams
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.PolicyPolicyManagerSummaryWithResponse(cmd.Context(), int64(deps.Config.OrgID), id)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	return c
}

// newPolicyManagerUpdateCmd — PATCH /policy/v1/orgs/{orgId}/policy-managers/{id} (operationId: Policy_Policy_Manager_update)
func newPolicyManagerUpdateCmd() *cobra.Command {
	var (
		id                 string
		bodyRaw            string
		fAllowDeletePolicy bool
		fAllowEditPolicy   bool
		fDescription       string
		fDryRun            bool
		fLogLevel          string
		fName              string
		fOrgTagsFilter     string
		fSeverity          string
		fSkipApprovals     bool
		dryRun             bool
		yes                bool
		interactive        bool
	)
	c := &cobra.Command{
		Use:         "update",
		Short:       "Update a policy manager",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli policy policy-manager update --org-id ORG_ID --id ID --body @request.json\n  flexera-cli policy policy-manager update --org-id ORG_ID --id ID --body @request.json --dry-run\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema policy policy-manager update --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "Policy_Policy_Manager_update", "flexera.output": "text", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if interactive {
				if err := clipkg.GuardInteractive(cmd, bodyRaw); err != nil {
					return err
				}
				if err := clipkg.GatherInteractiveParams(cmd, "Policy_Policy_Manager_update"); err != nil {
					return err
				}
			}
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Policy_Policy_Manager_update")
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("allow-delete-policy") {
				fields["allowDeletePolicy"] = fAllowDeletePolicy
			}
			if cmd.Flags().Changed("allow-edit-policy") {
				fields["allowEditPolicy"] = fAllowEditPolicy
			}
			if cmd.Flags().Changed("description") {
				fields["description"] = fDescription
			}
			if cmd.Flags().Changed("body-dry-run") {
				fields["dryRun"] = fDryRun
			}
			if cmd.Flags().Changed("log-level") {
				fields["logLevel"] = fLogLevel
			}
			if cmd.Flags().Changed("name") {
				fields["name"] = fName
			}
			if cmd.Flags().Changed("org-tags-filter") {
				fields["orgTagsFilter"] = fOrgTagsFilter
			}
			if cmd.Flags().Changed("severity") {
				fields["severity"] = fSeverity
			}
			if cmd.Flags().Changed("skip-approvals") {
				fields["skipApprovals"] = fSkipApprovals
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				if !interactive {
					return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
				}
			}
			if interactive {
				raw, err = clipkg.GatherInteractiveBody(cmd, "Policy_Policy_Manager_update", raw)
				if err != nil {
					return err
				}
			}
			var body flexera.PolicyPolicyManagerUpdateJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("Policy_Policy_Manager_update", raw, &body, noValidate)
			if err != nil {
				return err
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "PATCH", Path: "/policy/v1/orgs/{orgId}/policy-managers/{id}", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			writePlan.Body, writePlan.Validation, writePlan.RequestSchema = effectiveBody, validation, requestSchema
			var writeDone bool
			var werr error
			if interactive {
				writeDone, werr = clipkg.ConfirmInteractive(cmd, dryRun, yes, writePlan, deps.Printer)
			} else {
				writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			}
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.PolicyPolicyManagerUpdateWithResponse(cmd.Context(), int64(deps.Config.OrgID), id, body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 204:
				fmt.Fprintln(deps.Stdout, "OK")
				return nil
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	c.Flags().BoolVar(&fAllowDeletePolicy, "allow-delete-policy", false, "allowDeletePolicy (body)")
	c.Flags().BoolVar(&fAllowEditPolicy, "allow-edit-policy", false, "allowEditPolicy (body)")
	c.Flags().StringVar(&fDescription, "description", "", "description (body)")
	c.Flags().BoolVar(&fDryRun, "body-dry-run", false, "dryRun (body)")
	c.Flags().StringVar(&fLogLevel, "log-level", "", "logLevel (body)")
	c.Flags().StringVar(&fName, "name", "", "name (body)")
	c.Flags().StringVar(&fOrgTagsFilter, "org-tags-filter", "", "orgTagsFilter (body)")
	c.Flags().StringVar(&fSeverity, "severity", "", "severity (body)")
	c.Flags().BoolVar(&fSkipApprovals, "skip-approvals", false, "skipApprovals (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	c.Flags().BoolVarP(&interactive, "interactive", "i", false, "edit inputs in a terminal form, review a plan and approve with typed yes")
	return c
}

// newPolicyManagerUpdateTemplateCmd — PATCH /policy/v1/orgs/{orgId}/policy-managers/{id}/update-template (operationId: Policy_Policy_Manager_updateTemplate)
func newPolicyManagerUpdateTemplateCmd() *cobra.Command {
	var (
		id             string
		bodyRaw        string
		fDryRun        bool
		fLogLevel      string
		fSeverity      string
		fSkipApprovals bool
		dryRun         bool
		yes            bool
		interactive    bool
	)
	c := &cobra.Command{
		Use:         "update-template",
		Short:       "Update policy manager to reference the latest published template version",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli policy policy-manager update-template --org-id ORG_ID --id ID --body @request.json\n  flexera-cli policy policy-manager update-template --org-id ORG_ID --id ID --body @request.json --dry-run\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema policy policy-manager update-template --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "Policy_Policy_Manager_updateTemplate", "flexera.output": "text", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if interactive {
				if err := clipkg.GuardInteractive(cmd, bodyRaw); err != nil {
					return err
				}
				if err := clipkg.GatherInteractiveParams(cmd, "Policy_Policy_Manager_updateTemplate"); err != nil {
					return err
				}
			}
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Policy_Policy_Manager_updateTemplate")
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("body-dry-run") {
				fields["dryRun"] = fDryRun
			}
			if cmd.Flags().Changed("log-level") {
				fields["logLevel"] = fLogLevel
			}
			if cmd.Flags().Changed("severity") {
				fields["severity"] = fSeverity
			}
			if cmd.Flags().Changed("skip-approvals") {
				fields["skipApprovals"] = fSkipApprovals
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				if !interactive {
					return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
				}
			}
			if interactive {
				raw, err = clipkg.GatherInteractiveBody(cmd, "Policy_Policy_Manager_updateTemplate", raw)
				if err != nil {
					return err
				}
			}
			var body flexera.PolicyPolicyManagerUpdateTemplateJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("Policy_Policy_Manager_updateTemplate", raw, &body, noValidate)
			if err != nil {
				return err
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "PATCH", Path: "/policy/v1/orgs/{orgId}/policy-managers/{id}/update-template", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			writePlan.Body, writePlan.Validation, writePlan.RequestSchema = effectiveBody, validation, requestSchema
			var writeDone bool
			var werr error
			if interactive {
				writeDone, werr = clipkg.ConfirmInteractive(cmd, dryRun, yes, writePlan, deps.Printer)
			} else {
				writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			}
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.PolicyPolicyManagerUpdateTemplateWithResponse(cmd.Context(), int64(deps.Config.OrgID), id, body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 204:
				fmt.Fprintln(deps.Stdout, "OK")
				return nil
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	c.Flags().BoolVar(&fDryRun, "body-dry-run", false, "dryRun (body)")
	c.Flags().StringVar(&fLogLevel, "log-level", "", "logLevel (body)")
	c.Flags().StringVar(&fSeverity, "severity", "", "severity (body)")
	c.Flags().BoolVar(&fSkipApprovals, "skip-approvals", false, "skipApprovals (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	c.Flags().BoolVarP(&interactive, "interactive", "i", false, "edit inputs in a terminal form, review a plan and approve with typed yes")
	return c
}
