// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag anomalies.

package anomalies

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "anomalies" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "anomalies",
		Short: "anomalies operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newAnomaliesReportCmd(),
		newAnomaliesAnomaliesCmd(),
		newAnomaliesListCmd(),
		newAnomaliesAggregatedCmd(),
	)
	return c
}

// newAnomaliesReportCmd — POST /bill-analysis/orgs/{orgId}/anomalies/report (operationId: BillAnalysis_anomalies_report)
func newAnomaliesReportCmd() *cobra.Command {
	var (
		bodyRaw             string
		fBillingCenterIDs   []string
		fDetectionMethod    string
		fDimensions         []string
		fEndAt              string
		fGranularity        string
		fLimit              int
		fMetric             string
		fStandardDeviations float64
		fStartAt            string
		fWindowSize         int64
	)
	c := &cobra.Command{
		Use:         "report",
		Short:       "report anomalies",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli bill-analysis anomalies report --org-id ORG_ID --body @request.json\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema bill-analysis anomalies report --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "BillAnalysis_anomalies_report", "flexera.output": "structured", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "BillAnalysis_anomalies_report")
			if err != nil {
				return err
			}
			_ = effectiveParams
			fields := map[string]any{}
			if cmd.Flags().Changed("billing-center-ids") {
				fields["billingCenterIds"] = fBillingCenterIDs
			}
			if cmd.Flags().Changed("detection-method") {
				fields["detectionMethod"] = fDetectionMethod
			}
			if cmd.Flags().Changed("dimensions") {
				fields["dimensions"] = fDimensions
			}
			if cmd.Flags().Changed("end-at") {
				fields["endAt"] = fEndAt
			}
			if cmd.Flags().Changed("granularity") {
				fields["granularity"] = fGranularity
			}
			if cmd.Flags().Changed("limit") {
				fields["limit"] = fLimit
			}
			if cmd.Flags().Changed("metric") {
				fields["metric"] = fMetric
			}
			if cmd.Flags().Changed("standard-deviations") {
				fields["standardDeviations"] = fStandardDeviations
			}
			if cmd.Flags().Changed("start-at") {
				fields["startAt"] = fStartAt
			}
			if cmd.Flags().Changed("window-size") {
				fields["windowSize"] = fWindowSize
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
			}
			var body flexera.BillAnalysisAnomaliesReportJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("BillAnalysis_anomalies_report", raw, &body, noValidate)
			if err != nil {
				return err
			}
			_, _, _ = effectiveBody, validation, requestSchema
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.BillAnalysisAnomaliesReportWithResponse(cmd.Context(), int64(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringSliceVar(&fBillingCenterIDs, "billing-center-ids", nil, "billingCenterIds (body)")
	c.Flags().StringVar(&fDetectionMethod, "detection-method", "", "detectionMethod (body)")
	c.Flags().StringSliceVar(&fDimensions, "dimensions", nil, "dimensions (body)")
	c.Flags().StringVar(&fEndAt, "end-at", "", "endAt (body)")
	c.Flags().StringVar(&fGranularity, "granularity", "", "granularity (body)")
	c.Flags().IntVar(&fLimit, "limit", 0, "limit (body)")
	c.Flags().StringVar(&fMetric, "metric", "", "metric (body)")
	c.Flags().Float64Var(&fStandardDeviations, "standard-deviations", 0, "standardDeviations (body)")
	c.Flags().StringVar(&fStartAt, "start-at", "", "startAt (body)")
	c.Flags().Int64Var(&fWindowSize, "window-size", 0, "windowSize (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	return c
}

// newAnomaliesAnomaliesCmd — GET /bill-analysis/orgs/{orgId}/v2/anomalies/{id} (operationId: BillAnalysis_anomalies_summary)
func newAnomaliesAnomaliesCmd() *cobra.Command {
	var (
		id string
	)
	c := &cobra.Command{
		Use:         "anomalies",
		Short:       "summary anomalies",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli bill-analysis anomalies anomalies --org-id ORG_ID --id ID",
		Annotations: map[string]string{"flexera.operationId": "BillAnalysis_anomalies_summary", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "BillAnalysis_anomalies_summary")
			if err != nil {
				return err
			}
			_ = effectiveParams
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.BillAnalysisAnomaliesSummaryWithResponse(cmd.Context(), int64(deps.Config.OrgID), id)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	return c
}

// newAnomaliesListCmd — POST /bill-analysis/orgs/{orgId}/v2/anomalies (operationId: BillAnalysis_anomalies_index)
func newAnomaliesListCmd() *cobra.Command {
	var (
		bodyRaw     string
		fEndAt      string
		fLimit      int64
		fMetric     string
		fOffset     int64
		fSortColumn string
		fSortOrder  string
		fStartAt    string
	)
	c := &cobra.Command{
		Use:         "list",
		Short:       "index anomalies",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli bill-analysis anomalies list --org-id ORG_ID --body @request.json\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema bill-analysis anomalies list --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "BillAnalysis_anomalies_index", "flexera.output": "structured", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "BillAnalysis_anomalies_index")
			if err != nil {
				return err
			}
			_ = effectiveParams
			fields := map[string]any{}
			if cmd.Flags().Changed("end-at") {
				fields["endAt"] = fEndAt
			}
			if cmd.Flags().Changed("limit") {
				fields["limit"] = fLimit
			}
			if cmd.Flags().Changed("metric") {
				fields["metric"] = fMetric
			}
			if cmd.Flags().Changed("offset") {
				fields["offset"] = fOffset
			}
			if cmd.Flags().Changed("sort-column") {
				fields["sortColumn"] = fSortColumn
			}
			if cmd.Flags().Changed("sort-order") {
				fields["sortOrder"] = fSortOrder
			}
			if cmd.Flags().Changed("start-at") {
				fields["startAt"] = fStartAt
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
			}
			var body flexera.BillAnalysisAnomaliesIndexJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("BillAnalysis_anomalies_index", raw, &body, noValidate)
			if err != nil {
				return err
			}
			_, _, _ = effectiveBody, validation, requestSchema
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.BillAnalysisAnomaliesIndexWithResponse(cmd.Context(), int64(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&fEndAt, "end-at", "", "endAt (body)")
	c.Flags().Int64Var(&fLimit, "limit", 0, "limit (body)")
	c.Flags().StringVar(&fMetric, "metric", "", "metric (body)")
	c.Flags().Int64Var(&fOffset, "offset", 0, "offset (body)")
	c.Flags().StringVar(&fSortColumn, "sort-column", "", "sortColumn (body)")
	c.Flags().StringVar(&fSortOrder, "sort-order", "", "sortOrder (body)")
	c.Flags().StringVar(&fStartAt, "start-at", "", "startAt (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	return c
}

// newAnomaliesAggregatedCmd — POST /bill-analysis/orgs/{orgId}/v2/anomalies/aggregated (operationId: BillAnalysis_anomalies_aggregated)
func newAnomaliesAggregatedCmd() *cobra.Command {
	var (
		bodyRaw  string
		fEndAt   string
		fMetric  string
		fStartAt string
	)
	c := &cobra.Command{
		Use:         "aggregated",
		Short:       "aggregated anomalies",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli bill-analysis anomalies aggregated --org-id ORG_ID --body @request.json\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema bill-analysis anomalies aggregated --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "BillAnalysis_anomalies_aggregated", "flexera.output": "structured", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "BillAnalysis_anomalies_aggregated")
			if err != nil {
				return err
			}
			_ = effectiveParams
			fields := map[string]any{}
			if cmd.Flags().Changed("end-at") {
				fields["endAt"] = fEndAt
			}
			if cmd.Flags().Changed("metric") {
				fields["metric"] = fMetric
			}
			if cmd.Flags().Changed("start-at") {
				fields["startAt"] = fStartAt
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
			}
			var body flexera.BillAnalysisAnomaliesAggregatedJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("BillAnalysis_anomalies_aggregated", raw, &body, noValidate)
			if err != nil {
				return err
			}
			_, _, _ = effectiveBody, validation, requestSchema
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.BillAnalysisAnomaliesAggregatedWithResponse(cmd.Context(), int64(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&fEndAt, "end-at", "", "endAt (body)")
	c.Flags().StringVar(&fMetric, "metric", "", "metric (body)")
	c.Flags().StringVar(&fStartAt, "start-at", "", "startAt (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	return c
}
