// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag SAML2 Identity Provider Signing Key.

package saml2identityprovidersigningkey

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "saml2-identity-provider-signing-key" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "saml2-identity-provider-signing-key",
		Short: "SAML2 Identity Provider Signing Key operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newSAML2IdentityProviderSigningKeyCreateCmd(),
		newSAML2IdentityProviderSigningKeyGetCmd(),
		newSAML2IdentityProviderSigningKeyListCmd(),
	)
	return c
}

// newSAML2IdentityProviderSigningKeyCreateCmd — POST /iam/v1/orgs/{orgId}/idps/{identityProviderId}/signing-keys/generate (operationId: Iam_SAML2_Identity_Provider_Signing_Key_generate)
func newSAML2IdentityProviderSigningKeyCreateCmd() *cobra.Command {
	var (
		identityProviderID string
		bodyRaw            string
		fValidityYears     int
		dryRun             bool
		yes                bool
		interactive        bool
	)
	c := &cobra.Command{
		Use:         "create",
		Short:       "Generate a new signing key",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli saml2-identity-provider-signing-key create --org-id ORG_ID --identity-provider-id IDENTITY_PROVIDER_ID --body @request.json\n  flexera-cli saml2-identity-provider-signing-key create --org-id ORG_ID --identity-provider-id IDENTITY_PROVIDER_ID --body @request.json --dry-run\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema saml2-identity-provider-signing-key create --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "Iam_SAML2_Identity_Provider_Signing_Key_generate", "flexera.output": "structured", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if interactive {
				if err := clipkg.GuardInteractive(cmd, bodyRaw); err != nil {
					return err
				}
				if err := clipkg.GatherInteractiveParams(cmd, "Iam_SAML2_Identity_Provider_Signing_Key_generate"); err != nil {
					return err
				}
			}
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Iam_SAML2_Identity_Provider_Signing_Key_generate")
			if err != nil {
				return err
			}
			if strings.TrimSpace(identityProviderID) == "" {
				return fmt.Errorf("--identity-provider-id is required")
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("validity-years") {
				fields["validityYears"] = fValidityYears
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				if !interactive {
					return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
				}
			}
			if interactive {
				raw, err = clipkg.GatherInteractiveBody(cmd, "Iam_SAML2_Identity_Provider_Signing_Key_generate", raw)
				if err != nil {
					return err
				}
			}
			var body flexera.IamSAML2IdentityProviderSigningKeyGenerateJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("Iam_SAML2_Identity_Provider_Signing_Key_generate", raw, &body, noValidate)
			if err != nil {
				return err
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "POST", Path: "/iam/v1/orgs/{orgId}/idps/{identityProviderId}/signing-keys/generate", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			writePlan.Body, writePlan.Validation, writePlan.RequestSchema = effectiveBody, validation, requestSchema
			var writeDone bool
			var werr error
			if interactive {
				writeDone, werr = clipkg.ConfirmInteractive(cmd, dryRun, yes, writePlan, deps.Printer)
			} else {
				writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			}
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.IamSAML2IdentityProviderSigningKeyGenerateWithResponse(cmd.Context(), deps.Config.OrgID, identityProviderID, body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 201:
				if resp.JSON201 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON201)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&identityProviderID, "identity-provider-id", "", "identityProviderId (path, required)")
	c.Flags().IntVar(&fValidityYears, "validity-years", 0, "validityYears (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	c.Flags().BoolVarP(&interactive, "interactive", "i", false, "edit inputs in a terminal form, review a plan and approve with typed yes")
	return c
}

// newSAML2IdentityProviderSigningKeyGetCmd — GET /iam/v1/orgs/{orgId}/idps/{identityProviderId}/signing-keys/{id} (operationId: Iam_SAML2_Identity_Provider_Signing_Key_show)
func newSAML2IdentityProviderSigningKeyGetCmd() *cobra.Command {
	var (
		identityProviderID string
		id                 string
	)
	c := &cobra.Command{
		Use:         "get",
		Short:       "Show a signing key",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli saml2-identity-provider-signing-key get --org-id ORG_ID --identity-provider-id IDENTITY_PROVIDER_ID --id ID",
		Annotations: map[string]string{"flexera.operationId": "Iam_SAML2_Identity_Provider_Signing_Key_show", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Iam_SAML2_Identity_Provider_Signing_Key_show")
			if err != nil {
				return err
			}
			_ = effectiveParams
			if strings.TrimSpace(identityProviderID) == "" {
				return fmt.Errorf("--identity-provider-id is required")
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.IamSAML2IdentityProviderSigningKeyShowWithResponse(cmd.Context(), deps.Config.OrgID, identityProviderID, id)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&identityProviderID, "identity-provider-id", "", "identityProviderId (path, required)")
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	return c
}

// newSAML2IdentityProviderSigningKeyListCmd — GET /iam/v1/orgs/{orgId}/idps/{identityProviderId}/signing-keys (operationId: Iam_SAML2_Identity_Provider_Signing_Key_index)
func newSAML2IdentityProviderSigningKeyListCmd() *cobra.Command {
	var (
		identityProviderID string
	)
	c := &cobra.Command{
		Use:         "list",
		Short:       "Index an IdP's signing keys",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli saml2-identity-provider-signing-key list --org-id ORG_ID --identity-provider-id IDENTITY_PROVIDER_ID",
		Annotations: map[string]string{"flexera.operationId": "Iam_SAML2_Identity_Provider_Signing_Key_index", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Iam_SAML2_Identity_Provider_Signing_Key_index")
			if err != nil {
				return err
			}
			_ = effectiveParams
			if strings.TrimSpace(identityProviderID) == "" {
				return fmt.Errorf("--identity-provider-id is required")
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.IamSAML2IdentityProviderSigningKeyIndexWithResponse(cmd.Context(), deps.Config.OrgID, identityProviderID)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&identityProviderID, "identity-provider-id", "", "identityProviderId (path, required)")
	return c
}
