// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag adjustment-definition.

package adjustmentdefinition

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "adjustment-definition" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "adjustment-definition",
		Short: "adjustment-definition operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newAdjustmentDefinitionListCmd(),
		newAdjustmentDefinitionReplaceCmd(),
	)
	return c
}

// newAdjustmentDefinitionListCmd — GET /orgs/{org}/adjustments/ (operationId: BillAnalysis_adjustment_definition_show)
func newAdjustmentDefinitionListCmd() *cobra.Command {
	var (
		org int
	)
	c := &cobra.Command{
		Use:   "list",
		Short: "show adjustment-definition",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.BillAnalysisAdjustmentDefinitionShowWithResponse(cmd.Context(), org)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().IntVar(&org, "org", 0, "org (path, required)")
	return c
}

// newAdjustmentDefinitionReplaceCmd — PUT /orgs/{org}/adjustments/ (operationId: BillAnalysis_adjustment_definition_update)
func newAdjustmentDefinitionReplaceCmd() *cobra.Command {
	var (
		org     int
		bodyRaw string
		dryRun  bool
		yes     bool
	)
	c := &cobra.Command{
		Use:   "replace",
		Short: "update adjustment-definition",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			fields := map[string]any{}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.BillAnalysisAdjustmentDefinitionUpdateJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			writePlan := map[string]any{"method": "PUT /orgs/{org}/adjustments/"}
			writePlan["body"] = json.RawMessage(raw)
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, false, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.BillAnalysisAdjustmentDefinitionUpdateWithResponse(cmd.Context(), org, body)
			if err != nil {
				return err
			}
			if resp.StatusCode() != 204 {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			fmt.Fprintln(deps.Stdout, "OK")
			return nil
		},
	}
	c.Flags().IntVar(&org, "org", 0, "org (path, required)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}
