// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag anomalies.

package anomalies

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "anomalies" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "anomalies",
		Short: "anomalies operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newAnomaliesCreateCmd(),
	)
	return c
}

// newAnomaliesCreateCmd — POST /orgs/{org}/anomalies/report (operationId: BillAnalysis_anomalies_report)
func newAnomaliesCreateCmd() *cobra.Command {
	var (
		org                 int
		bodyRaw             string
		fBillingCenterIDs   []string
		fDetectionMethod    string
		fDimensions         []string
		fEndAt              string
		fGranularity        string
		fLimit              int
		fMetric             string
		fStandardDeviations float64
		fStartAt            string
		fWindowSize         int64
		dryRun              bool
		yes                 bool
	)
	c := &cobra.Command{
		Use:   "create",
		Short: "report anomalies",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("billing-center-ids") {
				fields["billingCenterIds"] = fBillingCenterIDs
			}
			if cmd.Flags().Changed("detection-method") {
				fields["detectionMethod"] = fDetectionMethod
			}
			if cmd.Flags().Changed("dimensions") {
				fields["dimensions"] = fDimensions
			}
			if cmd.Flags().Changed("end-at") {
				fields["endAt"] = fEndAt
			}
			if cmd.Flags().Changed("granularity") {
				fields["granularity"] = fGranularity
			}
			if cmd.Flags().Changed("limit") {
				fields["limit"] = fLimit
			}
			if cmd.Flags().Changed("metric") {
				fields["metric"] = fMetric
			}
			if cmd.Flags().Changed("standard-deviations") {
				fields["standardDeviations"] = fStandardDeviations
			}
			if cmd.Flags().Changed("start-at") {
				fields["startAt"] = fStartAt
			}
			if cmd.Flags().Changed("window-size") {
				fields["windowSize"] = fWindowSize
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.BillAnalysisAnomaliesReportJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			writePlan := map[string]any{"method": "POST /orgs/{org}/anomalies/report"}
			writePlan["body"] = json.RawMessage(raw)
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, false, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.BillAnalysisAnomaliesReportWithResponse(cmd.Context(), org, body)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().IntVar(&org, "org", 0, "org (path, required)")
	c.Flags().StringSliceVar(&fBillingCenterIDs, "billing-center-ids", nil, "billingCenterIds (body)")
	c.Flags().StringVar(&fDetectionMethod, "detection-method", "", "detectionMethod (body)")
	c.Flags().StringSliceVar(&fDimensions, "dimensions", nil, "dimensions (body)")
	c.Flags().StringVar(&fEndAt, "end-at", "", "endAt (body)")
	c.Flags().StringVar(&fGranularity, "granularity", "", "granularity (body)")
	c.Flags().IntVar(&fLimit, "limit", 0, "limit (body)")
	c.Flags().StringVar(&fMetric, "metric", "", "metric (body)")
	c.Flags().Float64Var(&fStandardDeviations, "standard-deviations", 0, "standardDeviations (body)")
	c.Flags().StringVar(&fStartAt, "start-at", "", "startAt (body)")
	c.Flags().Int64Var(&fWindowSize, "window-size", 0, "windowSize (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}
