// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag Customer Group.

package customergroup

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "customer-group" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "customer-group",
		Short: "Customer Group operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newCustomerGroupGetCmd(),
		newCustomerGroupListCmd(),
	)
	return c
}

// newCustomerGroupGetCmd — GET /saas/v1/orgs/{orgId}/customer-groups/{customerGroupId} (operationId: Saas_Customer_Group_show)
func newCustomerGroupGetCmd() *cobra.Command {
	var (
		customerGroupID string
	)
	c := &cobra.Command{
		Use:   "get",
		Short: "Show customer group",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(customerGroupID) == "" {
				return fmt.Errorf("--customer-group-id is required")
			}
			resp, err := client.SaasCustomerGroupShowWithResponse(cmd.Context(), deps.Config.OrgID, customerGroupID)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringVar(&customerGroupID, "customer-group-id", "", "customerGroupId (path, required)")
	return c
}

// newCustomerGroupListCmd — GET /saas/v1/orgs/{orgId}/customer-groups (operationId: Saas_Customer_Group_index)
func newCustomerGroupListCmd() *cobra.Command {
	var (
		filter     string
		orderBy    string
		noPaginate bool
		skipToken  string
	)
	c := &cobra.Command{
		Use:   "list",
		Short: "List customer groups",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			params := flexera.SaasCustomerGroupIndexParams{}
			if cmd.Flags().Changed("filter") {
				v := filter
				params.Filter = &v
			}
			if cmd.Flags().Changed("order-by") {
				v := orderBy
				params.OrderBy = &v
			}
			var initialSkipToken *string
			if t := strings.TrimSpace(skipToken); t != "" {
				initialSkipToken = &t
			}
			result, err := flexera.CollectPages(cmd.Context(), noPaginate, initialSkipToken,
				func(ctx context.Context, st *string) (any, error) {
					p := params
					p.SkipToken = st
					resp, callErr := client.SaasCustomerGroupIndexWithResponse(ctx, deps.Config.OrgID, &p)
					if callErr != nil {
						return nil, callErr
					}
					if resp.JSON200 == nil {
						return nil, flexera.ResponseError(resp.StatusCode(), resp.Body)
					}
					return resp.JSON200, nil
				})
			if err != nil {
				return err
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
		},
	}
	c.Flags().StringVar(&filter, "filter", "", "filter (query)")
	c.Flags().StringVar(&orderBy, "order-by", "", "orderBy (query)")
	c.Flags().BoolVar(&noPaginate, "no-paginate", false, "return only the first page (do not follow nextPage)")
	c.Flags().StringVar(&skipToken, "skip-token", "", "resume pagination from this token")
	return c
}
