// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag Onboarding.

package onboarding

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "onboarding" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "onboarding",
		Short: "Onboarding operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newOnboardingCreateCmd(),
		newOnboardingDeleteCmd(),
		newOnboardingReplaceCmd(),
	)
	return c
}

// newOnboardingCreateCmd — POST /data-inventory/v1/orgs/{org_id}/onboarding/ (operationId: Divnt_trigger_onboarding_post_data_inventory_v1_orgs_org_id_onboarding_post)
func newOnboardingCreateCmd() *cobra.Command {
	var (
		bodyRaw              string
		fAccountType         string
		fBillingAccountID    string
		fClientID            string
		fClientSecret        string
		fConnectorName       string
		fExcludeRegion       []string
		fExternalID          string
		fHaveBillingAccess   string
		fIncludeBPC          string
		fIncludeCostAndUsage string
		fIncludeInventory    string
		fPartnerTenantID     string
		fProvider            string
		fRoleARN             string
		fSubscriptionID      string
		fTenantID            string
		fTokenURL            string
		dryRun               bool
		yes                  bool
		interactive          bool
	)
	c := &cobra.Command{
		Use:         "create",
		Short:       "Onboarding: Create",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli data-inventory onboarding create --org-id ORG_ID --body @request.json\n  flexera-cli data-inventory onboarding create --org-id ORG_ID --body @request.json --dry-run\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema data-inventory onboarding create --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "Divnt_trigger_onboarding_post_data_inventory_v1_orgs_org_id_onboarding_post", "flexera.output": "structured", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if interactive {
				if err := clipkg.GuardInteractive(cmd, bodyRaw); err != nil {
					return err
				}
				if err := clipkg.GatherInteractiveParams(cmd, "Divnt_trigger_onboarding_post_data_inventory_v1_orgs_org_id_onboarding_post"); err != nil {
					return err
				}
			}
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Divnt_trigger_onboarding_post_data_inventory_v1_orgs_org_id_onboarding_post")
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("account-type") {
				fields["AccountType"] = fAccountType
			}
			if cmd.Flags().Changed("billing-account-id") {
				fields["BillingAccountId"] = fBillingAccountID
			}
			if cmd.Flags().Changed("body-client-id") {
				fields["ClientId"] = fClientID
			}
			if cmd.Flags().Changed("body-client-secret") {
				fields["ClientSecret"] = fClientSecret
			}
			if cmd.Flags().Changed("connector-name") {
				fields["ConnectorName"] = fConnectorName
			}
			if cmd.Flags().Changed("exclude-region") {
				fields["ExcludeRegion"] = fExcludeRegion
			}
			if cmd.Flags().Changed("external-id") {
				fields["ExternalId"] = fExternalID
			}
			if cmd.Flags().Changed("have-billing-access") {
				fields["HaveBillingAccess"] = fHaveBillingAccess
			}
			if cmd.Flags().Changed("include-bpc") {
				fields["IncludeBPC"] = fIncludeBPC
			}
			if cmd.Flags().Changed("include-cost-and-usage") {
				fields["IncludeCostAndUsage"] = fIncludeCostAndUsage
			}
			if cmd.Flags().Changed("include-inventory") {
				fields["IncludeInventory"] = fIncludeInventory
			}
			if cmd.Flags().Changed("partner-tenant-id") {
				fields["PartnerTenantId"] = fPartnerTenantID
			}
			if cmd.Flags().Changed("provider") {
				fields["Provider"] = fProvider
			}
			if cmd.Flags().Changed("role-arn") {
				fields["RoleARN"] = fRoleARN
			}
			if cmd.Flags().Changed("subscription-id") {
				fields["SubscriptionId"] = fSubscriptionID
			}
			if cmd.Flags().Changed("tenant-id") {
				fields["TenantId"] = fTenantID
			}
			if cmd.Flags().Changed("token-url") {
				fields["TokenUrl"] = fTokenURL
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				if !interactive {
					return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
				}
			}
			if interactive {
				raw, err = clipkg.GatherInteractiveBody(cmd, "Divnt_trigger_onboarding_post_data_inventory_v1_orgs_org_id_onboarding_post", raw)
				if err != nil {
					return err
				}
			}
			var body flexera.DivntTriggerOnboardingPostDataInventoryV1OrgsOrgIdOnboardingPostJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("Divnt_trigger_onboarding_post_data_inventory_v1_orgs_org_id_onboarding_post", raw, &body, noValidate)
			if err != nil {
				return err
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "POST", Path: "/data-inventory/v1/orgs/{org_id}/onboarding/", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			writePlan.Body, writePlan.Validation, writePlan.RequestSchema = effectiveBody, validation, requestSchema
			var writeDone bool
			var werr error
			if interactive {
				writeDone, werr = clipkg.ConfirmInteractive(cmd, dryRun, yes, writePlan, deps.Printer)
			} else {
				writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			}
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.DivntTriggerOnboardingPostDataInventoryV1OrgsOrgIdOnboardingPostWithResponse(cmd.Context(), fmt.Sprint(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 202:
				if resp.JSON202 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON202)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&fAccountType, "account-type", "", "AccountType (body)")
	c.Flags().StringVar(&fBillingAccountID, "billing-account-id", "", "BillingAccountId (body)")
	c.Flags().StringVar(&fClientID, "body-client-id", "", "ClientId (body)")
	c.Flags().StringVar(&fClientSecret, "body-client-secret", "", "ClientSecret (body)")
	c.Flags().StringVar(&fConnectorName, "connector-name", "", "ConnectorName (body)")
	c.Flags().StringSliceVar(&fExcludeRegion, "exclude-region", nil, "ExcludeRegion (body)")
	c.Flags().StringVar(&fExternalID, "external-id", "", "ExternalId (body)")
	c.Flags().StringVar(&fHaveBillingAccess, "have-billing-access", "", "HaveBillingAccess (body)")
	c.Flags().StringVar(&fIncludeBPC, "include-bpc", "", "IncludeBPC (body)")
	c.Flags().StringVar(&fIncludeCostAndUsage, "include-cost-and-usage", "", "IncludeCostAndUsage (body)")
	c.Flags().StringVar(&fIncludeInventory, "include-inventory", "", "IncludeInventory (body)")
	c.Flags().StringVar(&fPartnerTenantID, "partner-tenant-id", "", "PartnerTenantId (body)")
	c.Flags().StringVar(&fProvider, "provider", "", "Provider (body)")
	c.Flags().StringVar(&fRoleARN, "role-arn", "", "RoleARN (body)")
	c.Flags().StringVar(&fSubscriptionID, "subscription-id", "", "SubscriptionId (body)")
	c.Flags().StringVar(&fTenantID, "tenant-id", "", "TenantId (body)")
	c.Flags().StringVar(&fTokenURL, "token-url", "", "TokenUrl (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	c.Flags().BoolVarP(&interactive, "interactive", "i", false, "edit inputs in a terminal form, review a plan and approve with typed yes")
	return c
}

// newOnboardingDeleteCmd — DELETE /data-inventory/v1/orgs/{org_id}/onboarding/{connector_id} (operationId: Divnt_trigger_onboarding_delete_data_inventory_v1_orgs_org_id_onboarding_connector_id_delete)
func newOnboardingDeleteCmd() *cobra.Command {
	var (
		connectorID string
		provider    string
		dryRun      bool
		yes         bool
	)
	c := &cobra.Command{
		Use:         "delete",
		Short:       "Onboarding: Delete",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli data-inventory onboarding delete --org-id ORG_ID --connector-id CONNECTOR_ID --provider PROVIDER\n  flexera-cli data-inventory onboarding delete --org-id ORG_ID --connector-id CONNECTOR_ID --provider PROVIDER --dry-run",
		Annotations: map[string]string{"flexera.operationId": "Divnt_trigger_onboarding_delete_data_inventory_v1_orgs_org_id_onboarding_connector_id_delete", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Divnt_trigger_onboarding_delete_data_inventory_v1_orgs_org_id_onboarding_connector_id_delete")
			if err != nil {
				return err
			}
			if strings.TrimSpace(connectorID) == "" {
				return fmt.Errorf("--connector-id is required")
			}
			params := flexera.DivntTriggerOnboardingDeleteDataInventoryV1OrgsOrgIdOnboardingConnectorIdDeleteParams{}
			if cmd.Flags().Changed("provider") {
				params.Provider = provider
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "DELETE", Path: "/data-inventory/v1/orgs/{org_id}/onboarding/{connector_id}", Params: planParams, Destructive: true}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			var writeDone bool
			var werr error
			writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.DivntTriggerOnboardingDeleteDataInventoryV1OrgsOrgIdOnboardingConnectorIdDeleteWithResponse(cmd.Context(), connectorID, fmt.Sprint(deps.Config.OrgID), &params)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 202:
				if resp.JSON202 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON202)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&connectorID, "connector-id", "", "connector_id (path, required)")
	c.Flags().StringVar(&provider, "provider", "", "provider (query)")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newOnboardingReplaceCmd — PUT /data-inventory/v1/orgs/{org_id}/onboarding/{connector_id} (operationId: Divnt_trigger_onboarding_put_data_inventory_v1_orgs_org_id_onboarding_connector_id_put)
func newOnboardingReplaceCmd() *cobra.Command {
	var (
		connectorID          string
		provider             string
		bodyRaw              string
		fAccountType         string
		fBillingAccountID    string
		fClientID            string
		fClientSecret        string
		fConnectorName       string
		fExcludeRegion       []string
		fExternalID          string
		fHaveBillingAccess   string
		fIncludeBPC          string
		fIncludeCostAndUsage string
		fIncludeInventory    string
		fPartnerTenantID     string
		fRoleARN             string
		fSubscriptionID      string
		fTenantID            string
		fTokenURL            string
		dryRun               bool
		yes                  bool
		interactive          bool
	)
	c := &cobra.Command{
		Use:         "replace",
		Short:       "Onboarding: Update",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli data-inventory onboarding replace --org-id ORG_ID --connector-id CONNECTOR_ID --provider PROVIDER --body @request.json\n  flexera-cli data-inventory onboarding replace --org-id ORG_ID --connector-id CONNECTOR_ID --provider PROVIDER --body @request.json --dry-run\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema data-inventory onboarding replace --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "Divnt_trigger_onboarding_put_data_inventory_v1_orgs_org_id_onboarding_connector_id_put", "flexera.output": "structured", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if interactive {
				if err := clipkg.GuardInteractive(cmd, bodyRaw); err != nil {
					return err
				}
				if err := clipkg.GatherInteractiveParams(cmd, "Divnt_trigger_onboarding_put_data_inventory_v1_orgs_org_id_onboarding_connector_id_put"); err != nil {
					return err
				}
			}
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Divnt_trigger_onboarding_put_data_inventory_v1_orgs_org_id_onboarding_connector_id_put")
			if err != nil {
				return err
			}
			if strings.TrimSpace(connectorID) == "" {
				return fmt.Errorf("--connector-id is required")
			}
			params := flexera.DivntTriggerOnboardingPutDataInventoryV1OrgsOrgIdOnboardingConnectorIdPutParams{}
			if cmd.Flags().Changed("provider") {
				params.Provider = provider
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("account-type") {
				fields["AccountType"] = fAccountType
			}
			if cmd.Flags().Changed("billing-account-id") {
				fields["BillingAccountId"] = fBillingAccountID
			}
			if cmd.Flags().Changed("body-client-id") {
				fields["ClientId"] = fClientID
			}
			if cmd.Flags().Changed("body-client-secret") {
				fields["ClientSecret"] = fClientSecret
			}
			if cmd.Flags().Changed("connector-name") {
				fields["ConnectorName"] = fConnectorName
			}
			if cmd.Flags().Changed("exclude-region") {
				fields["ExcludeRegion"] = fExcludeRegion
			}
			if cmd.Flags().Changed("external-id") {
				fields["ExternalId"] = fExternalID
			}
			if cmd.Flags().Changed("have-billing-access") {
				fields["HaveBillingAccess"] = fHaveBillingAccess
			}
			if cmd.Flags().Changed("include-bpc") {
				fields["IncludeBPC"] = fIncludeBPC
			}
			if cmd.Flags().Changed("include-cost-and-usage") {
				fields["IncludeCostAndUsage"] = fIncludeCostAndUsage
			}
			if cmd.Flags().Changed("include-inventory") {
				fields["IncludeInventory"] = fIncludeInventory
			}
			if cmd.Flags().Changed("partner-tenant-id") {
				fields["PartnerTenantId"] = fPartnerTenantID
			}
			if cmd.Flags().Changed("role-arn") {
				fields["RoleARN"] = fRoleARN
			}
			if cmd.Flags().Changed("subscription-id") {
				fields["SubscriptionId"] = fSubscriptionID
			}
			if cmd.Flags().Changed("tenant-id") {
				fields["TenantId"] = fTenantID
			}
			if cmd.Flags().Changed("token-url") {
				fields["TokenUrl"] = fTokenURL
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				if !interactive {
					return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
				}
			}
			if interactive {
				raw, err = clipkg.GatherInteractiveBody(cmd, "Divnt_trigger_onboarding_put_data_inventory_v1_orgs_org_id_onboarding_connector_id_put", raw)
				if err != nil {
					return err
				}
			}
			var body flexera.DivntTriggerOnboardingPutDataInventoryV1OrgsOrgIdOnboardingConnectorIdPutJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("Divnt_trigger_onboarding_put_data_inventory_v1_orgs_org_id_onboarding_connector_id_put", raw, &body, noValidate)
			if err != nil {
				return err
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "PUT", Path: "/data-inventory/v1/orgs/{org_id}/onboarding/{connector_id}", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			writePlan.Body, writePlan.Validation, writePlan.RequestSchema = effectiveBody, validation, requestSchema
			var writeDone bool
			var werr error
			if interactive {
				writeDone, werr = clipkg.ConfirmInteractive(cmd, dryRun, yes, writePlan, deps.Printer)
			} else {
				writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			}
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.DivntTriggerOnboardingPutDataInventoryV1OrgsOrgIdOnboardingConnectorIdPutWithResponse(cmd.Context(), connectorID, fmt.Sprint(deps.Config.OrgID), &params, body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 202:
				if resp.JSON202 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON202)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&connectorID, "connector-id", "", "connector_id (path, required)")
	c.Flags().StringVar(&provider, "provider", "", "provider (query)")
	c.Flags().StringVar(&fAccountType, "account-type", "", "AccountType (body)")
	c.Flags().StringVar(&fBillingAccountID, "billing-account-id", "", "BillingAccountId (body)")
	c.Flags().StringVar(&fClientID, "body-client-id", "", "ClientId (body)")
	c.Flags().StringVar(&fClientSecret, "body-client-secret", "", "ClientSecret (body)")
	c.Flags().StringVar(&fConnectorName, "connector-name", "", "ConnectorName (body)")
	c.Flags().StringSliceVar(&fExcludeRegion, "exclude-region", nil, "ExcludeRegion (body)")
	c.Flags().StringVar(&fExternalID, "external-id", "", "ExternalId (body)")
	c.Flags().StringVar(&fHaveBillingAccess, "have-billing-access", "", "HaveBillingAccess (body)")
	c.Flags().StringVar(&fIncludeBPC, "include-bpc", "", "IncludeBPC (body)")
	c.Flags().StringVar(&fIncludeCostAndUsage, "include-cost-and-usage", "", "IncludeCostAndUsage (body)")
	c.Flags().StringVar(&fIncludeInventory, "include-inventory", "", "IncludeInventory (body)")
	c.Flags().StringVar(&fPartnerTenantID, "partner-tenant-id", "", "PartnerTenantId (body)")
	c.Flags().StringVar(&fRoleARN, "role-arn", "", "RoleARN (body)")
	c.Flags().StringVar(&fSubscriptionID, "subscription-id", "", "SubscriptionId (body)")
	c.Flags().StringVar(&fTenantID, "tenant-id", "", "TenantId (body)")
	c.Flags().StringVar(&fTokenURL, "token-url", "", "TokenUrl (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	c.Flags().BoolVarP(&interactive, "interactive", "i", false, "edit inputs in a terminal form, review a plan and approve with typed yes")
	return c
}
