// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag Project.

package project

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "project" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "project",
		Short: "Project operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newProjectListCmd(),
	)
	return c
}

// newProjectListCmd — GET /iam/v1/orgs/{orgId}/projects (operationId: Iam_Project_Index)
func newProjectListCmd() *cobra.Command {
	var (
		view string
	)
	c := &cobra.Command{
		Use:         "list",
		Short:       "Index an org's projects",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli iam project list --org-id ORG_ID",
		Annotations: map[string]string{"flexera.operationId": "Iam_Project_Index", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Iam_Project_Index")
			if err != nil {
				return err
			}
			_ = effectiveParams
			params := flexera.IamProjectIndexParams{}
			if cmd.Flags().Changed("view") {
				ev := flexera.IamProjectIndexParamsView(view)
				params.View = &ev
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.IamProjectIndexWithResponse(cmd.Context(), deps.Config.OrgID, &params)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&view, "view", "", "view (query)")
	return c
}
