// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag Invoice Schedules.

package invoiceschedules

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "invoice-schedules" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "invoice-schedules",
		Short: "Invoice Schedules operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newInvoiceSchedulesActivateCmd(),
		newInvoiceSchedulesDeactivateCmd(),
		newInvoiceSchedulesCreateCmd(),
		newInvoiceSchedulesGetCmd(),
		newInvoiceSchedulesListCmd(),
		newInvoiceSchedulesUpdateCmd(),
	)
	return c
}

// newInvoiceSchedulesActivateCmd — POST /finops-billing/v1/orgs/{orgId}/invoice-schedules/{id}/activate (operationId: FinopsBilling_Invoice_Schedules_activate)
func newInvoiceSchedulesActivateCmd() *cobra.Command {
	var (
		id           string
		endMonthYear string
		dryRun       bool
		yes          bool
	)
	c := &cobra.Command{
		Use:         "activate",
		Short:       "Activate an invoice schedule",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli finops-billing invoice-schedules activate --org-id ORG_ID --id ID\n  flexera-cli finops-billing invoice-schedules activate --org-id ORG_ID --id ID --dry-run",
		Annotations: map[string]string{"flexera.operationId": "FinopsBilling_Invoice_Schedules_activate", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "FinopsBilling_Invoice_Schedules_activate")
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			params := flexera.FinopsBillingInvoiceSchedulesActivateParams{}
			if cmd.Flags().Changed("end-month-year") {
				v := endMonthYear
				params.EndMonthYear = &v
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "POST", Path: "/finops-billing/v1/orgs/{orgId}/invoice-schedules/{id}/activate", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			var writeDone bool
			var werr error
			writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.FinopsBillingInvoiceSchedulesActivateWithResponse(cmd.Context(), deps.Config.OrgID, id, &params)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	c.Flags().StringVar(&endMonthYear, "end-month-year", "", "endMonthYear (query)")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newInvoiceSchedulesDeactivateCmd — POST /finops-billing/v1/orgs/{orgId}/invoice-schedules/{id}/deactivate (operationId: FinopsBilling_Invoice_Schedules_deactivate)
func newInvoiceSchedulesDeactivateCmd() *cobra.Command {
	var (
		id     string
		dryRun bool
		yes    bool
	)
	c := &cobra.Command{
		Use:         "deactivate",
		Short:       "Deactivate an invoice schedule",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli finops-billing invoice-schedules deactivate --org-id ORG_ID --id ID\n  flexera-cli finops-billing invoice-schedules deactivate --org-id ORG_ID --id ID --dry-run",
		Annotations: map[string]string{"flexera.operationId": "FinopsBilling_Invoice_Schedules_deactivate", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "FinopsBilling_Invoice_Schedules_deactivate")
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			params := flexera.FinopsBillingInvoiceSchedulesDeactivateParams{}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "POST", Path: "/finops-billing/v1/orgs/{orgId}/invoice-schedules/{id}/deactivate", Params: planParams, Destructive: true}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			var writeDone bool
			var werr error
			writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.FinopsBillingInvoiceSchedulesDeactivateWithResponse(cmd.Context(), deps.Config.OrgID, id, &params)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newInvoiceSchedulesCreateCmd — POST /finops-billing/v1/orgs/{orgId}/invoice-schedules (operationId: FinopsBilling_Invoice_Schedules_create)
func newInvoiceSchedulesCreateCmd() *cobra.Command {
	var (
		bodyRaw            string
		fInvoiceTemplateID string
		fIsCreateTemplate  bool
		fScheduleName      string
		dryRun             bool
		yes                bool
		interactive        bool
	)
	c := &cobra.Command{
		Use:         "create",
		Short:       "Create an invoice schedule",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli finops-billing invoice-schedules create --org-id ORG_ID --body @request.json\n  flexera-cli finops-billing invoice-schedules create --org-id ORG_ID --body @request.json --dry-run\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema finops-billing invoice-schedules create --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "FinopsBilling_Invoice_Schedules_create", "flexera.output": "structured", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if interactive {
				if err := clipkg.GuardInteractive(cmd, bodyRaw); err != nil {
					return err
				}
				if err := clipkg.GatherInteractiveParams(cmd, "FinopsBilling_Invoice_Schedules_create"); err != nil {
					return err
				}
			}
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "FinopsBilling_Invoice_Schedules_create")
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("invoice-template-id") {
				fields["invoiceTemplateId"] = fInvoiceTemplateID
			}
			if cmd.Flags().Changed("is-create-template") {
				fields["isCreateTemplate"] = fIsCreateTemplate
			}
			if cmd.Flags().Changed("schedule-name") {
				fields["scheduleName"] = fScheduleName
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				if !interactive {
					return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
				}
			}
			if interactive {
				raw, err = clipkg.GatherInteractiveBody(cmd, "FinopsBilling_Invoice_Schedules_create", raw)
				if err != nil {
					return err
				}
			}
			var body flexera.FinopsBillingInvoiceSchedulesCreateJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("FinopsBilling_Invoice_Schedules_create", raw, &body, noValidate)
			if err != nil {
				return err
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "POST", Path: "/finops-billing/v1/orgs/{orgId}/invoice-schedules", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			writePlan.Body, writePlan.Validation, writePlan.RequestSchema = effectiveBody, validation, requestSchema
			var writeDone bool
			var werr error
			if interactive {
				writeDone, werr = clipkg.ConfirmInteractive(cmd, dryRun, yes, writePlan, deps.Printer)
			} else {
				writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			}
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.FinopsBillingInvoiceSchedulesCreateWithResponse(cmd.Context(), deps.Config.OrgID, body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 201:
				if resp.JSON201 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON201)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&fInvoiceTemplateID, "invoice-template-id", "", "invoiceTemplateId (body)")
	c.Flags().BoolVar(&fIsCreateTemplate, "is-create-template", false, "isCreateTemplate (body)")
	c.Flags().StringVar(&fScheduleName, "schedule-name", "", "scheduleName (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	c.Flags().BoolVarP(&interactive, "interactive", "i", false, "edit inputs in a terminal form, review a plan and approve with typed yes")
	return c
}

// newInvoiceSchedulesGetCmd — GET /finops-billing/v1/orgs/{orgId}/invoice-schedules/{id} (operationId: FinopsBilling_Invoice_Schedules_show)
func newInvoiceSchedulesGetCmd() *cobra.Command {
	var (
		id string
	)
	c := &cobra.Command{
		Use:         "get",
		Short:       "Show an invoice schedule",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli finops-billing invoice-schedules get --org-id ORG_ID --id ID",
		Annotations: map[string]string{"flexera.operationId": "FinopsBilling_Invoice_Schedules_show", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "FinopsBilling_Invoice_Schedules_show")
			if err != nil {
				return err
			}
			_ = effectiveParams
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.FinopsBillingInvoiceSchedulesShowWithResponse(cmd.Context(), deps.Config.OrgID, id)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	return c
}

// newInvoiceSchedulesListCmd — GET /finops-billing/v1/orgs/{orgId}/invoice-schedules (operationId: FinopsBilling_Invoice_Schedules_index)
func newInvoiceSchedulesListCmd() *cobra.Command {
	var (
		limit        int
		orderBy      string
		customerID   int
		status       string
		scheduleName string
		filter       string
		noPaginate   bool
		skipToken    string
	)
	c := &cobra.Command{
		Use:         "list",
		Short:       "Index invoice schedules",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli finops-billing invoice-schedules list --org-id ORG_ID",
		Annotations: map[string]string{"flexera.operationId": "FinopsBilling_Invoice_Schedules_index", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "FinopsBilling_Invoice_Schedules_index")
			if err != nil {
				return err
			}
			_ = effectiveParams
			params := flexera.FinopsBillingInvoiceSchedulesIndexParams{}
			if cmd.Flags().Changed("limit") {
				v := limit
				params.Limit = &v
			}
			if cmd.Flags().Changed("order-by") {
				v := orderBy
				params.OrderBy = &v
			}
			if cmd.Flags().Changed("customer-id") {
				v := customerID
				params.CustomerId = &v
			}
			if cmd.Flags().Changed("status") {
				ev := flexera.FinopsBillingInvoiceSchedulesIndexParamsStatus(status)
				params.Status = &ev
			}
			if cmd.Flags().Changed("schedule-name") {
				v := scheduleName
				params.ScheduleName = &v
			}
			if cmd.Flags().Changed("filter") {
				v := filter
				params.Filter = &v
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			var initialSkipToken *string
			if t := strings.TrimSpace(skipToken); t != "" {
				initialSkipToken = &t
			}
			result, err := flexera.CollectPages(cmd.Context(), noPaginate, initialSkipToken,
				func(ctx context.Context, st *string) (any, error) {
					p := params
					p.SkipToken = st
					resp, callErr := client.FinopsBillingInvoiceSchedulesIndexWithResponse(ctx, deps.Config.OrgID, &p)
					if callErr != nil {
						return nil, callErr
					}
					switch resp.StatusCode() {
					case 200:
						if resp.JSON200 != nil {
							if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
								return resp.JSON200, nil
							}
							return clipkg.DecodeResponseJSON(resp.Body)
						}
					}
					return nil, flexera.ResponseError(resp.StatusCode(), resp.Body)
				})
			if err != nil {
				return err
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
		},
	}
	c.Flags().IntVar(&limit, "limit", 0, "limit (query)")
	c.Flags().StringVar(&orderBy, "order-by", "", "orderBy (query)")
	c.Flags().IntVar(&customerID, "customer-id", 0, "customerId (query)")
	c.Flags().StringVar(&status, "status", "", "status (query)")
	c.Flags().StringVar(&scheduleName, "schedule-name", "", "scheduleName (query)")
	c.Flags().StringVar(&filter, "filter", "", "filter (query)")
	c.Flags().BoolVar(&noPaginate, "no-paginate", false, "return only the first page (do not follow nextPage)")
	c.Flags().StringVar(&skipToken, "skip-token", "", "resume pagination from this token")
	return c
}

// newInvoiceSchedulesUpdateCmd — PATCH /finops-billing/v1/orgs/{orgId}/invoice-schedules/{id} (operationId: FinopsBilling_Invoice_Schedules_update)
func newInvoiceSchedulesUpdateCmd() *cobra.Command {
	var (
		id                 string
		bodyRaw            string
		fInvoiceTemplateID string
		fIsCreateTemplate  bool
		fScheduleName      string
		dryRun             bool
		yes                bool
		interactive        bool
	)
	c := &cobra.Command{
		Use:         "update",
		Short:       "Update an invoice schedule",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli finops-billing invoice-schedules update --org-id ORG_ID --id ID --body @request.json\n  flexera-cli finops-billing invoice-schedules update --org-id ORG_ID --id ID --body @request.json --dry-run\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema finops-billing invoice-schedules update --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "FinopsBilling_Invoice_Schedules_update", "flexera.output": "structured", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if interactive {
				if err := clipkg.GuardInteractive(cmd, bodyRaw); err != nil {
					return err
				}
				if err := clipkg.GatherInteractiveParams(cmd, "FinopsBilling_Invoice_Schedules_update"); err != nil {
					return err
				}
			}
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "FinopsBilling_Invoice_Schedules_update")
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			params := flexera.FinopsBillingInvoiceSchedulesUpdateParams{}
			fields := map[string]any{}
			if cmd.Flags().Changed("invoice-template-id") {
				fields["invoiceTemplateId"] = fInvoiceTemplateID
			}
			if cmd.Flags().Changed("is-create-template") {
				fields["isCreateTemplate"] = fIsCreateTemplate
			}
			if cmd.Flags().Changed("schedule-name") {
				fields["scheduleName"] = fScheduleName
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				if !interactive {
					return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
				}
			}
			if interactive {
				raw, err = clipkg.GatherInteractiveBody(cmd, "FinopsBilling_Invoice_Schedules_update", raw)
				if err != nil {
					return err
				}
			}
			var body flexera.FinopsBillingInvoiceSchedulesUpdateJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("FinopsBilling_Invoice_Schedules_update", raw, &body, noValidate)
			if err != nil {
				return err
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "PATCH", Path: "/finops-billing/v1/orgs/{orgId}/invoice-schedules/{id}", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			writePlan.Body, writePlan.Validation, writePlan.RequestSchema = effectiveBody, validation, requestSchema
			var writeDone bool
			var werr error
			if interactive {
				writeDone, werr = clipkg.ConfirmInteractive(cmd, dryRun, yes, writePlan, deps.Printer)
			} else {
				writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			}
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.FinopsBillingInvoiceSchedulesUpdateWithResponse(cmd.Context(), deps.Config.OrgID, id, &params, body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	c.Flags().StringVar(&fInvoiceTemplateID, "invoice-template-id", "", "invoiceTemplateId (body)")
	c.Flags().BoolVar(&fIsCreateTemplate, "is-create-template", false, "isCreateTemplate (body)")
	c.Flags().StringVar(&fScheduleName, "schedule-name", "", "scheduleName (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	c.Flags().BoolVarP(&interactive, "interactive", "i", false, "edit inputs in a terminal form, review a plan and approve with typed yes")
	return c
}
