// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag MSP Customer Tag.

package mspcustomertag

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "msp-customer-tag" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "msp-customer-tag",
		Short: "MSP Customer Tag operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newMSPCustomerTagTagsCmd(),
		newMSPCustomerTagDeleteCmd(),
		newMSPCustomerTagListAllCmd(),
		newMSPCustomerTagListCmd(),
	)
	return c
}

// newMSPCustomerTagTagsCmd — POST /msp/v1/orgs/{orgId}/customers/{customerId}/tags (operationId: Iam_MSP_Customer_Tag_Create)
func newMSPCustomerTagTagsCmd() *cobra.Command {
	var (
		customerID int
		bodyRaw    string
	)
	c := &cobra.Command{
		Use:   "tags",
		Short: "Sets a tag on an MSP's customer",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			fields := map[string]any{}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.IamMSPCustomerTagCreateJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			resp, err := client.IamMSPCustomerTagCreateWithResponse(cmd.Context(), deps.Config.OrgID, customerID, body)
			if err != nil {
				return err
			}
			if resp.JSON201 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON201)
		},
	}
	c.Flags().IntVar(&customerID, "customer-id", 0, "customerId (path, required)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	return c
}

// newMSPCustomerTagDeleteCmd — DELETE /msp/v1/orgs/{orgId}/customers/{customerId}/tags/{tag} (operationId: Iam_MSP_Customer_Tag_Delete)
func newMSPCustomerTagDeleteCmd() *cobra.Command {
	var (
		customerID int
		tag        string
		dryRun     bool
		yes        bool
	)
	c := &cobra.Command{
		Use:   "delete",
		Short: "Delete a tag for an MSP's customer",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(tag) == "" {
				return fmt.Errorf("--tag is required")
			}
			writePlan := map[string]any{"method": "DELETE /msp/v1/orgs/{orgId}/customers/{customerId}/tags/{tag}"}
			writePlan["orgId"] = deps.Config.OrgID
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, true, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.IamMSPCustomerTagDeleteWithResponse(cmd.Context(), deps.Config.OrgID, customerID, tag)
			if err != nil {
				return err
			}
			if resp.StatusCode() != 204 {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			fmt.Fprintln(deps.Stdout, "OK")
			return nil
		},
	}
	c.Flags().IntVar(&customerID, "customer-id", 0, "customerId (path, required)")
	c.Flags().StringVar(&tag, "tag", "", "tag (path, required)")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newMSPCustomerTagListAllCmd — GET /msp/v1/orgs/{orgId}/customers/tags (operationId: Iam_MSP_Customer_Tag_Index_Customers)
func newMSPCustomerTagListAllCmd() *cobra.Command {
	var (
		filter     string
		noPaginate bool
		skipToken  string
	)
	c := &cobra.Command{
		Use:   "list-all",
		Short: "Index an MSP's customers based on tag filter",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			params := flexera.IamMSPCustomerTagIndexCustomersParams{}
			if cmd.Flags().Changed("filter") {
				v := filter
				params.Filter = &v
			}
			var initialSkipToken *string
			if t := strings.TrimSpace(skipToken); t != "" {
				initialSkipToken = &t
			}
			result, err := flexera.CollectPages(cmd.Context(), noPaginate, initialSkipToken,
				func(ctx context.Context, st *string) (any, error) {
					p := params
					p.SkipToken = st
					resp, callErr := client.IamMSPCustomerTagIndexCustomersWithResponse(ctx, deps.Config.OrgID, &p)
					if callErr != nil {
						return nil, callErr
					}
					if resp.JSON200 == nil {
						return nil, flexera.ResponseError(resp.StatusCode(), resp.Body)
					}
					return resp.JSON200, nil
				})
			if err != nil {
				return err
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
		},
	}
	c.Flags().StringVar(&filter, "filter", "", "filter (query)")
	c.Flags().BoolVar(&noPaginate, "no-paginate", false, "return only the first page (do not follow nextPage)")
	c.Flags().StringVar(&skipToken, "skip-token", "", "resume pagination from this token")
	return c
}

// newMSPCustomerTagListCmd — GET /msp/v1/orgs/{orgId}/customers/{customerId}/tags (operationId: Iam_MSP_Customer_Tag_Show)
func newMSPCustomerTagListCmd() *cobra.Command {
	var (
		customerID int
	)
	c := &cobra.Command{
		Use:   "list",
		Short: "Show the tags for an MSP's customer",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.IamMSPCustomerTagShowWithResponse(cmd.Context(), deps.Config.OrgID, customerID)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().IntVar(&customerID, "customer-id", 0, "customerId (path, required)")
	return c
}
