// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag Import Job.

package importjob

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "import-job" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "import-job",
		Short: "Import Job operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newImportJobCreateCmd(),
		newImportJobGetCmd(),
		newImportJobListCmd(),
	)
	return c
}

// newImportJobCreateCmd — POST /saas/v1/orgs/{orgId}/import-jobs (operationId: Saas_Import_Job_createManagedAppImportJob)
func newImportJobCreateCmd() *cobra.Command {
	var (
		bodyRaw       string
		fManagedAppID string
		dryRun        bool
		yes           bool
		interactive   bool
	)
	c := &cobra.Command{
		Use:         "create",
		Short:       "Create import job",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli import-job create --org-id ORG_ID --body @request.json\n  flexera-cli import-job create --org-id ORG_ID --body @request.json --dry-run\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema import-job create --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "Saas_Import_Job_createManagedAppImportJob", "flexera.output": "text", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if interactive {
				if err := clipkg.GuardInteractive(cmd, bodyRaw); err != nil {
					return err
				}
				if err := clipkg.GatherInteractiveParams(cmd, "Saas_Import_Job_createManagedAppImportJob"); err != nil {
					return err
				}
			}
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Saas_Import_Job_createManagedAppImportJob")
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("managed-app-id") {
				fields["managedAppId"] = fManagedAppID
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				if !interactive {
					return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
				}
			}
			if interactive {
				raw, err = clipkg.GatherInteractiveBody(cmd, "Saas_Import_Job_createManagedAppImportJob", raw)
				if err != nil {
					return err
				}
			}
			var body flexera.SaasImportJobCreateManagedAppImportJobJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("Saas_Import_Job_createManagedAppImportJob", raw, &body, noValidate)
			if err != nil {
				return err
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "POST", Path: "/saas/v1/orgs/{orgId}/import-jobs", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			writePlan.Body, writePlan.Validation, writePlan.RequestSchema = effectiveBody, validation, requestSchema
			var writeDone bool
			var werr error
			if interactive {
				writeDone, werr = clipkg.ConfirmInteractive(cmd, dryRun, yes, writePlan, deps.Printer)
			} else {
				writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			}
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.SaasImportJobCreateManagedAppImportJobWithResponse(cmd.Context(), deps.Config.OrgID, body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 201:
				fmt.Fprintln(deps.Stdout, "OK")
				return nil
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&fManagedAppID, "managed-app-id", "", "managedAppId (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	c.Flags().BoolVarP(&interactive, "interactive", "i", false, "edit inputs in a terminal form, review a plan and approve with typed yes")
	return c
}

// newImportJobGetCmd — GET /saas/v1/orgs/{orgId}/import-jobs/{id} (operationId: Saas_Import_Job_show)
func newImportJobGetCmd() *cobra.Command {
	var (
		id string
	)
	c := &cobra.Command{
		Use:         "get",
		Short:       "Show import job",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli import-job get --org-id ORG_ID --id ID",
		Annotations: map[string]string{"flexera.operationId": "Saas_Import_Job_show", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Saas_Import_Job_show")
			if err != nil {
				return err
			}
			_ = effectiveParams
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.SaasImportJobShowWithResponse(cmd.Context(), deps.Config.OrgID, id)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	return c
}

// newImportJobListCmd — GET /saas/v1/orgs/{orgId}/import-jobs (operationId: Saas_Import_Job_index)
func newImportJobListCmd() *cobra.Command {
	var (
		filter     string
		orderBy    string
		noPaginate bool
		skipToken  string
	)
	c := &cobra.Command{
		Use:         "list",
		Short:       "List import jobs",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli import-job list --org-id ORG_ID",
		Annotations: map[string]string{"flexera.operationId": "Saas_Import_Job_index", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Saas_Import_Job_index")
			if err != nil {
				return err
			}
			_ = effectiveParams
			params := flexera.SaasImportJobIndexParams{}
			if cmd.Flags().Changed("filter") {
				v := filter
				params.Filter = &v
			}
			if cmd.Flags().Changed("order-by") {
				v := orderBy
				params.OrderBy = &v
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			var initialSkipToken *string
			if t := strings.TrimSpace(skipToken); t != "" {
				initialSkipToken = &t
			}
			result, err := flexera.CollectPages(cmd.Context(), noPaginate, initialSkipToken,
				func(ctx context.Context, st *string) (any, error) {
					p := params
					p.SkipToken = st
					resp, callErr := client.SaasImportJobIndexWithResponse(ctx, deps.Config.OrgID, &p)
					if callErr != nil {
						return nil, callErr
					}
					switch resp.StatusCode() {
					case 200:
						if resp.JSON200 != nil {
							if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
								return resp.JSON200, nil
							}
							return clipkg.DecodeResponseJSON(resp.Body)
						}
					}
					return nil, flexera.ResponseError(resp.StatusCode(), resp.Body)
				})
			if err != nil {
				return err
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
		},
	}
	c.Flags().StringVar(&filter, "filter", "", "filter (query)")
	c.Flags().StringVar(&orderBy, "order-by", "", "orderBy (query)")
	c.Flags().BoolVar(&noPaginate, "no-paginate", false, "return only the first page (do not follow nextPage)")
	c.Flags().StringVar(&skipToken, "skip-token", "", "resume pagination from this token")
	return c
}
