// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag Cloud Vendor Account.

package cloudvendoraccount

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "cloud-vendor-account" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "cloud-vendor-account",
		Short: "Cloud Vendor Account operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newCloudVendorAccountListCmd(),
	)
	return c
}

// newCloudVendorAccountListCmd — GET /finops-analytics/v1/orgs/{orgId}/cloud-vendor-accounts (operationId: Budget_Cloud_Vendor_Account_index)
func newCloudVendorAccountListCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "list",
		Short: "List all cloud vendor accounts",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.BudgetCloudVendorAccountIndexWithResponse(cmd.Context(), deps.Config.OrgID)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	return c
}
