// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag Bill Connect - GCP.

package billconnectgcp

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "bill-connect-gcp" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "bill-connect-gcp",
		Short: "Bill Connect - GCP operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newBillConnectGCPCreateCmd(),
		newBillConnectGCPDeleteCmd(),
		newBillConnectGCPGetCmd(),
		newBillConnectGCPListCmd(),
		newBillConnectGCPUpdateCmd(),
	)
	return c
}

// newBillConnectGCPCreateCmd — POST /finops-onboarding/v1/orgs/{orgId}/bill-connects/gcp (operationId: FinopsOnboarding_Bill_Connect_GCP_create)
func newBillConnectGCPCreateCmd() *cobra.Command {
	var (
		bodyRaw           string
		fBigQueryDataset  string
		fBillingAccountID string
		fGcsExportUri     string
		dryRun            bool
		yes               bool
	)
	c := &cobra.Command{
		Use:   "create",
		Short: "Create a GCP bill connect",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("big-query-dataset") {
				fields["bigQueryDataset"] = fBigQueryDataset
			}
			if cmd.Flags().Changed("billing-account-id") {
				fields["billingAccountId"] = fBillingAccountID
			}
			if cmd.Flags().Changed("gcs-export-uri") {
				fields["gcsExportUri"] = fGcsExportUri
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.FinopsOnboardingBillConnectGCPCreateJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			writePlan := map[string]any{"method": "POST /finops-onboarding/v1/orgs/{orgId}/bill-connects/gcp"}
			writePlan["orgId"] = deps.Config.OrgID
			writePlan["body"] = json.RawMessage(raw)
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, false, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.FinopsOnboardingBillConnectGCPCreateWithResponse(cmd.Context(), deps.Config.OrgID, body)
			if err != nil {
				return err
			}
			if resp.JSON201 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON201)
		},
	}
	c.Flags().StringVar(&fBigQueryDataset, "big-query-dataset", "", "bigQueryDataset (body)")
	c.Flags().StringVar(&fBillingAccountID, "billing-account-id", "", "billingAccountId (body)")
	c.Flags().StringVar(&fGcsExportUri, "gcs-export-uri", "", "gcsExportUri (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newBillConnectGCPDeleteCmd — DELETE /finops-onboarding/v1/orgs/{orgId}/bill-connects/gcp/{id} (operationId: FinopsOnboarding_Bill_Connect_GCP_delete)
func newBillConnectGCPDeleteCmd() *cobra.Command {
	var (
		id     string
		dryRun bool
		yes    bool
	)
	c := &cobra.Command{
		Use:   "delete",
		Short: "Delete a GCP bill connect",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			writePlan := map[string]any{"method": "DELETE /finops-onboarding/v1/orgs/{orgId}/bill-connects/gcp/{id}"}
			writePlan["orgId"] = deps.Config.OrgID
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, true, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.FinopsOnboardingBillConnectGCPDeleteWithResponse(cmd.Context(), deps.Config.OrgID, id)
			if err != nil {
				return err
			}
			if resp.StatusCode() != 204 {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			fmt.Fprintln(deps.Stdout, "OK")
			return nil
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newBillConnectGCPGetCmd — GET /finops-onboarding/v1/orgs/{orgId}/bill-connects/gcp/{id} (operationId: FinopsOnboarding_Bill_Connect_GCP_show)
func newBillConnectGCPGetCmd() *cobra.Command {
	var (
		id string
	)
	c := &cobra.Command{
		Use:   "get",
		Short: "Show a GCP bill connect",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			resp, err := client.FinopsOnboardingBillConnectGCPShowWithResponse(cmd.Context(), deps.Config.OrgID, id)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	return c
}

// newBillConnectGCPListCmd — GET /finops-onboarding/v1/orgs/{orgId}/bill-connects/gcp/{id}/validation (operationId: FinopsOnboarding_Bill_Connect_GCP_validate)
func newBillConnectGCPListCmd() *cobra.Command {
	var (
		id string
	)
	c := &cobra.Command{
		Use:   "list",
		Short: "Validate the credentials stored for a GCP bill connect",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			resp, err := client.FinopsOnboardingBillConnectGCPValidateWithResponse(cmd.Context(), deps.Config.OrgID, id)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	return c
}

// newBillConnectGCPUpdateCmd — PATCH /finops-onboarding/v1/orgs/{orgId}/bill-connects/gcp/{id} (operationId: FinopsOnboarding_Bill_Connect_GCP_update)
func newBillConnectGCPUpdateCmd() *cobra.Command {
	var (
		id            string
		bodyRaw       string
		fGcsExportUri string
		dryRun        bool
		yes           bool
	)
	c := &cobra.Command{
		Use:   "update",
		Short: "Update a GCP bill connect",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("gcs-export-uri") {
				fields["gcsExportUri"] = fGcsExportUri
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.FinopsOnboardingBillConnectGCPUpdateJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			writePlan := map[string]any{"method": "PATCH /finops-onboarding/v1/orgs/{orgId}/bill-connects/gcp/{id}"}
			writePlan["orgId"] = deps.Config.OrgID
			writePlan["body"] = json.RawMessage(raw)
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, false, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.FinopsOnboardingBillConnectGCPUpdateWithResponse(cmd.Context(), deps.Config.OrgID, id, body)
			if err != nil {
				return err
			}
			if resp.StatusCode() != 204 {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			fmt.Fprintln(deps.Stdout, "OK")
			return nil
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	c.Flags().StringVar(&fGcsExportUri, "gcs-export-uri", "", "gcsExportUri (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}
