// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag Refresh Token.

package refreshtoken

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "refresh-token" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "refresh-token",
		Short: "Refresh Token operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newRefreshTokenDeleteAllCmd(),
		newRefreshTokenDeleteCmd(),
		newRefreshTokenGetCmd(),
		newRefreshTokenListCmd(),
	)
	return c
}

// newRefreshTokenDeleteAllCmd — DELETE /iam/v1/refresh-tokens (operationId: Iam_Refresh_Token_RevokeAll)
func newRefreshTokenDeleteAllCmd() *cobra.Command {
	var (
		orgID  int
		userID int
		dryRun bool
		yes    bool
	)
	c := &cobra.Command{
		Use:   "delete-all",
		Short: "Revoke all user refresh tokens",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			params := flexera.IamRefreshTokenRevokeAllParams{}
			if cmd.Flags().Changed("org-id") {
				v := orgID
				params.OrgId = &v
			}
			if cmd.Flags().Changed("user-id") {
				v := userID
				params.UserId = &v
			}
			writePlan := map[string]any{"method": "DELETE /iam/v1/refresh-tokens"}
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, true, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.IamRefreshTokenRevokeAllWithResponse(cmd.Context(), &params)
			if err != nil {
				return err
			}
			if resp.StatusCode() != 204 {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			fmt.Fprintln(deps.Stdout, "OK")
			return nil
		},
	}
	c.Flags().IntVar(&orgID, "org-id", 0, "orgId (query)")
	c.Flags().IntVar(&userID, "user-id", 0, "userId (query)")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newRefreshTokenDeleteCmd — DELETE /iam/v1/refresh-tokens/{id} (operationId: Iam_Refresh_Token_Revoke)
func newRefreshTokenDeleteCmd() *cobra.Command {
	var (
		id     string
		orgID  int
		userID int
		dryRun bool
		yes    bool
	)
	c := &cobra.Command{
		Use:   "delete",
		Short: "Revoke a refresh token",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			params := flexera.IamRefreshTokenRevokeParams{}
			if cmd.Flags().Changed("org-id") {
				v := orgID
				params.OrgId = &v
			}
			if cmd.Flags().Changed("user-id") {
				v := userID
				params.UserId = &v
			}
			writePlan := map[string]any{"method": "DELETE /iam/v1/refresh-tokens/{id}"}
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, true, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.IamRefreshTokenRevokeWithResponse(cmd.Context(), id, &params)
			if err != nil {
				return err
			}
			if resp.StatusCode() != 204 {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			fmt.Fprintln(deps.Stdout, "OK")
			return nil
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	c.Flags().IntVar(&orgID, "org-id", 0, "orgId (query)")
	c.Flags().IntVar(&userID, "user-id", 0, "userId (query)")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newRefreshTokenGetCmd — GET /iam/v1/refresh-tokens/{id} (operationId: Iam_Refresh_Token_Show)
func newRefreshTokenGetCmd() *cobra.Command {
	var (
		id string
	)
	c := &cobra.Command{
		Use:   "get",
		Short: "Show a refresh token",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			resp, err := client.IamRefreshTokenShowWithResponse(cmd.Context(), id)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	return c
}

// newRefreshTokenListCmd — GET /iam/v1/refresh-tokens (operationId: Iam_Refresh_Token_Index)
func newRefreshTokenListCmd() *cobra.Command {
	var (
		orgID  int
		userID int
	)
	c := &cobra.Command{
		Use:   "list",
		Short: "Index a user's refresh tokens",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			params := flexera.IamRefreshTokenIndexParams{}
			if cmd.Flags().Changed("org-id") {
				v := orgID
				params.OrgId = &v
			}
			if cmd.Flags().Changed("user-id") {
				v := userID
				params.UserId = &v
			}
			resp, err := client.IamRefreshTokenIndexWithResponse(cmd.Context(), &params)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().IntVar(&orgID, "org-id", 0, "orgId (query)")
	c.Flags().IntVar(&userID, "user-id", 0, "userId (query)")
	return c
}
