// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag misconfiguration-ui.

package misconfigurationui

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "misconfiguration-ui" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "misconfiguration-ui",
		Short: "misconfiguration-ui operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newMisconfigurationUiCreateAllCmd(),
		newMisconfigurationUiCreateAll2Cmd(),
		newMisconfigurationUiCreateAll3Cmd(),
		newMisconfigurationUiCreateAll4Cmd(),
		newMisconfigurationUiCreateAll5Cmd(),
		newMisconfigurationUiCreateAll6Cmd(),
		newMisconfigurationUiCreateAll7Cmd(),
		newMisconfigurationUiCreateAll8Cmd(),
		newMisconfigurationUiCreateAll9Cmd(),
		newMisconfigurationUiCreateCmd(),
		newMisconfigurationUiGetRecommendationCmd(),
		newMisconfigurationUiGetRiskCmd(),
		newMisconfigurationUiListRecommendationCmd(),
		newMisconfigurationUiListRiskCmd(),
	)
	return c
}

// newMisconfigurationUiCreateAllCmd — POST /recommendation/v1/orgs/{orgId}/misconfiguration/failed-asset (operationId: Risk_get_failed_assets_recommendation_v1_orgs_orgId_misconfiguration_failed_asset_post)
func newMisconfigurationUiCreateAllCmd() *cobra.Command {
	var (
		bodyRaw         string
		fAccounts       []string
		fArgs           string
		fPageSize       int
		fProviders      []string
		fRegions        []string
		fRuleName       string
		fShowSuppressed string
		fSkipToken      string
		dryRun          bool
		yes             bool
		interactive     bool
	)
	c := &cobra.Command{
		Use:         "create-all",
		Short:       "Failed Assets List.",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli misconfiguration-ui create-all --org-id ORG_ID --body @request.json\n  flexera-cli misconfiguration-ui create-all --org-id ORG_ID --body @request.json --dry-run\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema misconfiguration-ui create-all --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "Risk_get_failed_assets_recommendation_v1_orgs_orgId_misconfiguration_failed_asset_post", "flexera.output": "structured", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if interactive {
				if err := clipkg.GuardInteractive(cmd, bodyRaw); err != nil {
					return err
				}
				if err := clipkg.GatherInteractiveParams(cmd, "Risk_get_failed_assets_recommendation_v1_orgs_orgId_misconfiguration_failed_asset_post"); err != nil {
					return err
				}
			}
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Risk_get_failed_assets_recommendation_v1_orgs_orgId_misconfiguration_failed_asset_post")
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("accounts") {
				fields["accounts"] = fAccounts
			}
			if cmd.Flags().Changed("args") {
				fields["args"] = fArgs
			}
			if cmd.Flags().Changed("page-size") {
				fields["pageSize"] = fPageSize
			}
			if cmd.Flags().Changed("providers") {
				fields["providers"] = fProviders
			}
			if cmd.Flags().Changed("regions") {
				fields["regions"] = fRegions
			}
			if cmd.Flags().Changed("rule-name") {
				fields["ruleName"] = fRuleName
			}
			if cmd.Flags().Changed("show-suppressed") {
				fields["showSuppressed"] = fShowSuppressed
			}
			if cmd.Flags().Changed("body-skip-token") {
				fields["skipToken"] = fSkipToken
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				if !interactive {
					return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
				}
			}
			if interactive {
				raw, err = clipkg.GatherInteractiveBody(cmd, "Risk_get_failed_assets_recommendation_v1_orgs_orgId_misconfiguration_failed_asset_post", raw)
				if err != nil {
					return err
				}
			}
			var body flexera.RiskGetFailedAssetsRecommendationV1OrgsOrgIdMisconfigurationFailedAssetPostJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("Risk_get_failed_assets_recommendation_v1_orgs_orgId_misconfiguration_failed_asset_post", raw, &body, noValidate)
			if err != nil {
				return err
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "POST", Path: "/recommendation/v1/orgs/{orgId}/misconfiguration/failed-asset", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			writePlan.Body, writePlan.Validation, writePlan.RequestSchema = effectiveBody, validation, requestSchema
			var writeDone bool
			var werr error
			if interactive {
				writeDone, werr = clipkg.ConfirmInteractive(cmd, dryRun, yes, writePlan, deps.Printer)
			} else {
				writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			}
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.RiskGetFailedAssetsRecommendationV1OrgsOrgIdMisconfigurationFailedAssetPostWithResponse(cmd.Context(), fmt.Sprint(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringSliceVar(&fAccounts, "accounts", nil, "accounts (body)")
	c.Flags().StringVar(&fArgs, "args", "", "args (body)")
	c.Flags().IntVar(&fPageSize, "page-size", 0, "pageSize (body)")
	c.Flags().StringSliceVar(&fProviders, "providers", nil, "providers (body)")
	c.Flags().StringSliceVar(&fRegions, "regions", nil, "regions (body)")
	c.Flags().StringVar(&fRuleName, "rule-name", "", "ruleName (body)")
	c.Flags().StringVar(&fShowSuppressed, "show-suppressed", "", "showSuppressed (body)")
	c.Flags().StringVar(&fSkipToken, "body-skip-token", "", "skipToken (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	c.Flags().BoolVarP(&interactive, "interactive", "i", false, "edit inputs in a terminal form, review a plan and approve with typed yes")
	return c
}

// newMisconfigurationUiCreateAll2Cmd — POST /recommendation/v1/orgs/{orgId}/misconfiguration/failed-asset/export (operationId: Risk_export_failed_assets_recommendation_v1_orgs_orgId_misconfiguration_failed_asset_export_post)
func newMisconfigurationUiCreateAll2Cmd() *cobra.Command {
	var (
		bodyRaw         string
		fAccounts       []string
		fArgs           string
		fPageSize       int
		fProviders      []string
		fRegions        []string
		fRuleName       string
		fShowSuppressed string
		fSkipToken      string
		dryRun          bool
		yes             bool
		interactive     bool
	)
	c := &cobra.Command{
		Use:         "create-all-2",
		Short:       "Export Failed Assets List.",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli misconfiguration-ui create-all-2 --org-id ORG_ID --body @request.json\n  flexera-cli misconfiguration-ui create-all-2 --org-id ORG_ID --body @request.json --dry-run\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema misconfiguration-ui create-all-2 --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "Risk_export_failed_assets_recommendation_v1_orgs_orgId_misconfiguration_failed_asset_export_post", "flexera.output": "structured", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if interactive {
				if err := clipkg.GuardInteractive(cmd, bodyRaw); err != nil {
					return err
				}
				if err := clipkg.GatherInteractiveParams(cmd, "Risk_export_failed_assets_recommendation_v1_orgs_orgId_misconfiguration_failed_asset_export_post"); err != nil {
					return err
				}
			}
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Risk_export_failed_assets_recommendation_v1_orgs_orgId_misconfiguration_failed_asset_export_post")
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("accounts") {
				fields["accounts"] = fAccounts
			}
			if cmd.Flags().Changed("args") {
				fields["args"] = fArgs
			}
			if cmd.Flags().Changed("page-size") {
				fields["pageSize"] = fPageSize
			}
			if cmd.Flags().Changed("providers") {
				fields["providers"] = fProviders
			}
			if cmd.Flags().Changed("regions") {
				fields["regions"] = fRegions
			}
			if cmd.Flags().Changed("rule-name") {
				fields["ruleName"] = fRuleName
			}
			if cmd.Flags().Changed("show-suppressed") {
				fields["showSuppressed"] = fShowSuppressed
			}
			if cmd.Flags().Changed("body-skip-token") {
				fields["skipToken"] = fSkipToken
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				if !interactive {
					return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
				}
			}
			if interactive {
				raw, err = clipkg.GatherInteractiveBody(cmd, "Risk_export_failed_assets_recommendation_v1_orgs_orgId_misconfiguration_failed_asset_export_post", raw)
				if err != nil {
					return err
				}
			}
			var body flexera.RiskExportFailedAssetsRecommendationV1OrgsOrgIdMisconfigurationFailedAssetExportPostJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("Risk_export_failed_assets_recommendation_v1_orgs_orgId_misconfiguration_failed_asset_export_post", raw, &body, noValidate)
			if err != nil {
				return err
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "POST", Path: "/recommendation/v1/orgs/{orgId}/misconfiguration/failed-asset/export", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			writePlan.Body, writePlan.Validation, writePlan.RequestSchema = effectiveBody, validation, requestSchema
			var writeDone bool
			var werr error
			if interactive {
				writeDone, werr = clipkg.ConfirmInteractive(cmd, dryRun, yes, writePlan, deps.Printer)
			} else {
				writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			}
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.RiskExportFailedAssetsRecommendationV1OrgsOrgIdMisconfigurationFailedAssetExportPostWithResponse(cmd.Context(), fmt.Sprint(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringSliceVar(&fAccounts, "accounts", nil, "accounts (body)")
	c.Flags().StringVar(&fArgs, "args", "", "args (body)")
	c.Flags().IntVar(&fPageSize, "page-size", 0, "pageSize (body)")
	c.Flags().StringSliceVar(&fProviders, "providers", nil, "providers (body)")
	c.Flags().StringSliceVar(&fRegions, "regions", nil, "regions (body)")
	c.Flags().StringVar(&fRuleName, "rule-name", "", "ruleName (body)")
	c.Flags().StringVar(&fShowSuppressed, "show-suppressed", "", "showSuppressed (body)")
	c.Flags().StringVar(&fSkipToken, "body-skip-token", "", "skipToken (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	c.Flags().BoolVarP(&interactive, "interactive", "i", false, "edit inputs in a terminal form, review a plan and approve with typed yes")
	return c
}

// newMisconfigurationUiCreateAll3Cmd — POST /recommendation/v1/orgs/{orgId}/misconfiguration/list (operationId: Risk_get_misconfig_rules_recommendation_v1_orgs_orgId_misconfiguration_list_post)
func newMisconfigurationUiCreateAll3Cmd() *cobra.Command {
	var (
		bodyRaw             string
		fAccounts           []string
		fComplianceStandard string
		fControlID          string
		fDate               string
		fEventID            string
		fEventTime          string
		fFeatureType        string
		fProviders          []string
		fRegions            []string
		fServices           []string
		dryRun              bool
		yes                 bool
		interactive         bool
	)
	c := &cobra.Command{
		Use:         "create-all-3",
		Short:       "Risk Misconfiguration Rules List.",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli misconfiguration-ui create-all-3 --org-id ORG_ID --body @request.json\n  flexera-cli misconfiguration-ui create-all-3 --org-id ORG_ID --body @request.json --dry-run\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema misconfiguration-ui create-all-3 --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "Risk_get_misconfig_rules_recommendation_v1_orgs_orgId_misconfiguration_list_post", "flexera.output": "structured", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if interactive {
				if err := clipkg.GuardInteractive(cmd, bodyRaw); err != nil {
					return err
				}
				if err := clipkg.GatherInteractiveParams(cmd, "Risk_get_misconfig_rules_recommendation_v1_orgs_orgId_misconfiguration_list_post"); err != nil {
					return err
				}
			}
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Risk_get_misconfig_rules_recommendation_v1_orgs_orgId_misconfiguration_list_post")
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("accounts") {
				fields["accounts"] = fAccounts
			}
			if cmd.Flags().Changed("compliance-standard") {
				fields["complianceStandard"] = fComplianceStandard
			}
			if cmd.Flags().Changed("control-id") {
				fields["controlId"] = fControlID
			}
			if cmd.Flags().Changed("date") {
				fields["date"] = fDate
			}
			if cmd.Flags().Changed("event-id") {
				fields["eventId"] = fEventID
			}
			if cmd.Flags().Changed("event-time") {
				fields["eventTime"] = fEventTime
			}
			if cmd.Flags().Changed("feature-type") {
				fields["featureType"] = fFeatureType
			}
			if cmd.Flags().Changed("providers") {
				fields["providers"] = fProviders
			}
			if cmd.Flags().Changed("regions") {
				fields["regions"] = fRegions
			}
			if cmd.Flags().Changed("services") {
				fields["services"] = fServices
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				if !interactive {
					return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
				}
			}
			if interactive {
				raw, err = clipkg.GatherInteractiveBody(cmd, "Risk_get_misconfig_rules_recommendation_v1_orgs_orgId_misconfiguration_list_post", raw)
				if err != nil {
					return err
				}
			}
			var body flexera.RiskGetMisconfigRulesRecommendationV1OrgsOrgIdMisconfigurationListPostJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("Risk_get_misconfig_rules_recommendation_v1_orgs_orgId_misconfiguration_list_post", raw, &body, noValidate)
			if err != nil {
				return err
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "POST", Path: "/recommendation/v1/orgs/{orgId}/misconfiguration/list", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			writePlan.Body, writePlan.Validation, writePlan.RequestSchema = effectiveBody, validation, requestSchema
			var writeDone bool
			var werr error
			if interactive {
				writeDone, werr = clipkg.ConfirmInteractive(cmd, dryRun, yes, writePlan, deps.Printer)
			} else {
				writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			}
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.RiskGetMisconfigRulesRecommendationV1OrgsOrgIdMisconfigurationListPostWithResponse(cmd.Context(), fmt.Sprint(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringSliceVar(&fAccounts, "accounts", nil, "accounts (body)")
	c.Flags().StringVar(&fComplianceStandard, "compliance-standard", "", "complianceStandard (body)")
	c.Flags().StringVar(&fControlID, "control-id", "", "controlId (body)")
	c.Flags().StringVar(&fDate, "date", "", "date (body)")
	c.Flags().StringVar(&fEventID, "event-id", "", "eventId (body)")
	c.Flags().StringVar(&fEventTime, "event-time", "", "eventTime (body)")
	c.Flags().StringVar(&fFeatureType, "feature-type", "", "featureType (body)")
	c.Flags().StringSliceVar(&fProviders, "providers", nil, "providers (body)")
	c.Flags().StringSliceVar(&fRegions, "regions", nil, "regions (body)")
	c.Flags().StringSliceVar(&fServices, "services", nil, "services (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	c.Flags().BoolVarP(&interactive, "interactive", "i", false, "edit inputs in a terminal form, review a plan and approve with typed yes")
	return c
}

// newMisconfigurationUiCreateAll4Cmd — POST /recommendation/v1/orgs/{orgId}/misconfiguration/overview (operationId: Risk_get_misconfig_overview_recommendation_v1_orgs_orgId_misconfiguration_overview_post)
func newMisconfigurationUiCreateAll4Cmd() *cobra.Command {
	var (
		bodyRaw     string
		fAccounts   []string
		fProviders  []string
		fRegions    []string
		fServices   []string
		dryRun      bool
		yes         bool
		interactive bool
	)
	c := &cobra.Command{
		Use:         "create-all-4",
		Short:       "Risk Misconfiguration Overview.",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli misconfiguration-ui create-all-4 --org-id ORG_ID --body @request.json\n  flexera-cli misconfiguration-ui create-all-4 --org-id ORG_ID --body @request.json --dry-run\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema misconfiguration-ui create-all-4 --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "Risk_get_misconfig_overview_recommendation_v1_orgs_orgId_misconfiguration_overview_post", "flexera.output": "structured", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if interactive {
				if err := clipkg.GuardInteractive(cmd, bodyRaw); err != nil {
					return err
				}
				if err := clipkg.GatherInteractiveParams(cmd, "Risk_get_misconfig_overview_recommendation_v1_orgs_orgId_misconfiguration_overview_post"); err != nil {
					return err
				}
			}
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Risk_get_misconfig_overview_recommendation_v1_orgs_orgId_misconfiguration_overview_post")
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("accounts") {
				fields["accounts"] = fAccounts
			}
			if cmd.Flags().Changed("providers") {
				fields["providers"] = fProviders
			}
			if cmd.Flags().Changed("regions") {
				fields["regions"] = fRegions
			}
			if cmd.Flags().Changed("services") {
				fields["services"] = fServices
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				if !interactive {
					return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
				}
			}
			if interactive {
				raw, err = clipkg.GatherInteractiveBody(cmd, "Risk_get_misconfig_overview_recommendation_v1_orgs_orgId_misconfiguration_overview_post", raw)
				if err != nil {
					return err
				}
			}
			var body flexera.RiskGetMisconfigOverviewRecommendationV1OrgsOrgIdMisconfigurationOverviewPostJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("Risk_get_misconfig_overview_recommendation_v1_orgs_orgId_misconfiguration_overview_post", raw, &body, noValidate)
			if err != nil {
				return err
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "POST", Path: "/recommendation/v1/orgs/{orgId}/misconfiguration/overview", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			writePlan.Body, writePlan.Validation, writePlan.RequestSchema = effectiveBody, validation, requestSchema
			var writeDone bool
			var werr error
			if interactive {
				writeDone, werr = clipkg.ConfirmInteractive(cmd, dryRun, yes, writePlan, deps.Printer)
			} else {
				writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			}
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.RiskGetMisconfigOverviewRecommendationV1OrgsOrgIdMisconfigurationOverviewPostWithResponse(cmd.Context(), fmt.Sprint(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringSliceVar(&fAccounts, "accounts", nil, "accounts (body)")
	c.Flags().StringSliceVar(&fProviders, "providers", nil, "providers (body)")
	c.Flags().StringSliceVar(&fRegions, "regions", nil, "regions (body)")
	c.Flags().StringSliceVar(&fServices, "services", nil, "services (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	c.Flags().BoolVarP(&interactive, "interactive", "i", false, "edit inputs in a terminal form, review a plan and approve with typed yes")
	return c
}

// newMisconfigurationUiCreateAll5Cmd — POST /recommendation/v1/orgs/{orgId}/misconfiguration/rule/suppress (operationId: Risk_suppress_rule_or_asset_recommendation_v1_orgs_orgId_misconfiguration_rule_suppress_post)
func newMisconfigurationUiCreateAll5Cmd() *cobra.Command {
	var (
		bodyRaw     string
		fUserName   string
		dryRun      bool
		yes         bool
		interactive bool
	)
	c := &cobra.Command{
		Use:         "create-all-5",
		Short:       "Suppress API for Rule and Failed Asset",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli misconfiguration-ui create-all-5 --org-id ORG_ID --body @request.json\n  flexera-cli misconfiguration-ui create-all-5 --org-id ORG_ID --body @request.json --dry-run\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema misconfiguration-ui create-all-5 --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "Risk_suppress_rule_or_asset_recommendation_v1_orgs_orgId_misconfiguration_rule_suppress_post", "flexera.output": "structured", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if interactive {
				if err := clipkg.GuardInteractive(cmd, bodyRaw); err != nil {
					return err
				}
				if err := clipkg.GatherInteractiveParams(cmd, "Risk_suppress_rule_or_asset_recommendation_v1_orgs_orgId_misconfiguration_rule_suppress_post"); err != nil {
					return err
				}
			}
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Risk_suppress_rule_or_asset_recommendation_v1_orgs_orgId_misconfiguration_rule_suppress_post")
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("user-name") {
				fields["userName"] = fUserName
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				if !interactive {
					return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
				}
			}
			if interactive {
				raw, err = clipkg.GatherInteractiveBody(cmd, "Risk_suppress_rule_or_asset_recommendation_v1_orgs_orgId_misconfiguration_rule_suppress_post", raw)
				if err != nil {
					return err
				}
			}
			var body flexera.RiskSuppressRuleOrAssetRecommendationV1OrgsOrgIdMisconfigurationRuleSuppressPostJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("Risk_suppress_rule_or_asset_recommendation_v1_orgs_orgId_misconfiguration_rule_suppress_post", raw, &body, noValidate)
			if err != nil {
				return err
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "POST", Path: "/recommendation/v1/orgs/{orgId}/misconfiguration/rule/suppress", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			writePlan.Body, writePlan.Validation, writePlan.RequestSchema = effectiveBody, validation, requestSchema
			var writeDone bool
			var werr error
			if interactive {
				writeDone, werr = clipkg.ConfirmInteractive(cmd, dryRun, yes, writePlan, deps.Printer)
			} else {
				writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			}
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.RiskSuppressRuleOrAssetRecommendationV1OrgsOrgIdMisconfigurationRuleSuppressPostWithResponse(cmd.Context(), fmt.Sprint(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&fUserName, "user-name", "", "userName (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	c.Flags().BoolVarP(&interactive, "interactive", "i", false, "edit inputs in a terminal form, review a plan and approve with typed yes")
	return c
}

// newMisconfigurationUiCreateAll6Cmd — POST /risk/v1/orgs/{orgId}/misconfiguration/failed-asset (operationId: Risk_get_failed_assets_risk_v1_orgs_orgId_misconfiguration_failed_asset_post)
func newMisconfigurationUiCreateAll6Cmd() *cobra.Command {
	var (
		bodyRaw         string
		fAccounts       []string
		fArgs           string
		fPageSize       int
		fProviders      []string
		fRegions        []string
		fRuleName       string
		fShowSuppressed string
		fSkipToken      string
		dryRun          bool
		yes             bool
		interactive     bool
	)
	c := &cobra.Command{
		Use:         "create-all-6",
		Short:       "Failed Assets List.",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli misconfiguration-ui create-all-6 --org-id ORG_ID --body @request.json\n  flexera-cli misconfiguration-ui create-all-6 --org-id ORG_ID --body @request.json --dry-run\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema misconfiguration-ui create-all-6 --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "Risk_get_failed_assets_risk_v1_orgs_orgId_misconfiguration_failed_asset_post", "flexera.output": "structured", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if interactive {
				if err := clipkg.GuardInteractive(cmd, bodyRaw); err != nil {
					return err
				}
				if err := clipkg.GatherInteractiveParams(cmd, "Risk_get_failed_assets_risk_v1_orgs_orgId_misconfiguration_failed_asset_post"); err != nil {
					return err
				}
			}
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Risk_get_failed_assets_risk_v1_orgs_orgId_misconfiguration_failed_asset_post")
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("accounts") {
				fields["accounts"] = fAccounts
			}
			if cmd.Flags().Changed("args") {
				fields["args"] = fArgs
			}
			if cmd.Flags().Changed("page-size") {
				fields["pageSize"] = fPageSize
			}
			if cmd.Flags().Changed("providers") {
				fields["providers"] = fProviders
			}
			if cmd.Flags().Changed("regions") {
				fields["regions"] = fRegions
			}
			if cmd.Flags().Changed("rule-name") {
				fields["ruleName"] = fRuleName
			}
			if cmd.Flags().Changed("show-suppressed") {
				fields["showSuppressed"] = fShowSuppressed
			}
			if cmd.Flags().Changed("body-skip-token") {
				fields["skipToken"] = fSkipToken
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				if !interactive {
					return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
				}
			}
			if interactive {
				raw, err = clipkg.GatherInteractiveBody(cmd, "Risk_get_failed_assets_risk_v1_orgs_orgId_misconfiguration_failed_asset_post", raw)
				if err != nil {
					return err
				}
			}
			var body flexera.RiskGetFailedAssetsRiskV1OrgsOrgIdMisconfigurationFailedAssetPostJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("Risk_get_failed_assets_risk_v1_orgs_orgId_misconfiguration_failed_asset_post", raw, &body, noValidate)
			if err != nil {
				return err
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "POST", Path: "/risk/v1/orgs/{orgId}/misconfiguration/failed-asset", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			writePlan.Body, writePlan.Validation, writePlan.RequestSchema = effectiveBody, validation, requestSchema
			var writeDone bool
			var werr error
			if interactive {
				writeDone, werr = clipkg.ConfirmInteractive(cmd, dryRun, yes, writePlan, deps.Printer)
			} else {
				writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			}
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.RiskGetFailedAssetsRiskV1OrgsOrgIdMisconfigurationFailedAssetPostWithResponse(cmd.Context(), fmt.Sprint(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringSliceVar(&fAccounts, "accounts", nil, "accounts (body)")
	c.Flags().StringVar(&fArgs, "args", "", "args (body)")
	c.Flags().IntVar(&fPageSize, "page-size", 0, "pageSize (body)")
	c.Flags().StringSliceVar(&fProviders, "providers", nil, "providers (body)")
	c.Flags().StringSliceVar(&fRegions, "regions", nil, "regions (body)")
	c.Flags().StringVar(&fRuleName, "rule-name", "", "ruleName (body)")
	c.Flags().StringVar(&fShowSuppressed, "show-suppressed", "", "showSuppressed (body)")
	c.Flags().StringVar(&fSkipToken, "body-skip-token", "", "skipToken (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	c.Flags().BoolVarP(&interactive, "interactive", "i", false, "edit inputs in a terminal form, review a plan and approve with typed yes")
	return c
}

// newMisconfigurationUiCreateAll7Cmd — POST /risk/v1/orgs/{orgId}/misconfiguration/failed-asset/export (operationId: Risk_export_failed_assets_risk_v1_orgs_orgId_misconfiguration_failed_asset_export_post)
func newMisconfigurationUiCreateAll7Cmd() *cobra.Command {
	var (
		bodyRaw         string
		fAccounts       []string
		fArgs           string
		fPageSize       int
		fProviders      []string
		fRegions        []string
		fRuleName       string
		fShowSuppressed string
		fSkipToken      string
		dryRun          bool
		yes             bool
		interactive     bool
	)
	c := &cobra.Command{
		Use:         "create-all-7",
		Short:       "Export Failed Assets List.",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli misconfiguration-ui create-all-7 --org-id ORG_ID --body @request.json\n  flexera-cli misconfiguration-ui create-all-7 --org-id ORG_ID --body @request.json --dry-run\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema misconfiguration-ui create-all-7 --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "Risk_export_failed_assets_risk_v1_orgs_orgId_misconfiguration_failed_asset_export_post", "flexera.output": "structured", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if interactive {
				if err := clipkg.GuardInteractive(cmd, bodyRaw); err != nil {
					return err
				}
				if err := clipkg.GatherInteractiveParams(cmd, "Risk_export_failed_assets_risk_v1_orgs_orgId_misconfiguration_failed_asset_export_post"); err != nil {
					return err
				}
			}
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Risk_export_failed_assets_risk_v1_orgs_orgId_misconfiguration_failed_asset_export_post")
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("accounts") {
				fields["accounts"] = fAccounts
			}
			if cmd.Flags().Changed("args") {
				fields["args"] = fArgs
			}
			if cmd.Flags().Changed("page-size") {
				fields["pageSize"] = fPageSize
			}
			if cmd.Flags().Changed("providers") {
				fields["providers"] = fProviders
			}
			if cmd.Flags().Changed("regions") {
				fields["regions"] = fRegions
			}
			if cmd.Flags().Changed("rule-name") {
				fields["ruleName"] = fRuleName
			}
			if cmd.Flags().Changed("show-suppressed") {
				fields["showSuppressed"] = fShowSuppressed
			}
			if cmd.Flags().Changed("body-skip-token") {
				fields["skipToken"] = fSkipToken
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				if !interactive {
					return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
				}
			}
			if interactive {
				raw, err = clipkg.GatherInteractiveBody(cmd, "Risk_export_failed_assets_risk_v1_orgs_orgId_misconfiguration_failed_asset_export_post", raw)
				if err != nil {
					return err
				}
			}
			var body flexera.RiskExportFailedAssetsRiskV1OrgsOrgIdMisconfigurationFailedAssetExportPostJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("Risk_export_failed_assets_risk_v1_orgs_orgId_misconfiguration_failed_asset_export_post", raw, &body, noValidate)
			if err != nil {
				return err
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "POST", Path: "/risk/v1/orgs/{orgId}/misconfiguration/failed-asset/export", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			writePlan.Body, writePlan.Validation, writePlan.RequestSchema = effectiveBody, validation, requestSchema
			var writeDone bool
			var werr error
			if interactive {
				writeDone, werr = clipkg.ConfirmInteractive(cmd, dryRun, yes, writePlan, deps.Printer)
			} else {
				writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			}
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.RiskExportFailedAssetsRiskV1OrgsOrgIdMisconfigurationFailedAssetExportPostWithResponse(cmd.Context(), fmt.Sprint(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringSliceVar(&fAccounts, "accounts", nil, "accounts (body)")
	c.Flags().StringVar(&fArgs, "args", "", "args (body)")
	c.Flags().IntVar(&fPageSize, "page-size", 0, "pageSize (body)")
	c.Flags().StringSliceVar(&fProviders, "providers", nil, "providers (body)")
	c.Flags().StringSliceVar(&fRegions, "regions", nil, "regions (body)")
	c.Flags().StringVar(&fRuleName, "rule-name", "", "ruleName (body)")
	c.Flags().StringVar(&fShowSuppressed, "show-suppressed", "", "showSuppressed (body)")
	c.Flags().StringVar(&fSkipToken, "body-skip-token", "", "skipToken (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	c.Flags().BoolVarP(&interactive, "interactive", "i", false, "edit inputs in a terminal form, review a plan and approve with typed yes")
	return c
}

// newMisconfigurationUiCreateAll8Cmd — POST /risk/v1/orgs/{orgId}/misconfiguration/list (operationId: Risk_get_misconfig_rules_risk_v1_orgs_orgId_misconfiguration_list_post)
func newMisconfigurationUiCreateAll8Cmd() *cobra.Command {
	var (
		bodyRaw             string
		fAccounts           []string
		fComplianceStandard string
		fControlID          string
		fDate               string
		fEventID            string
		fEventTime          string
		fFeatureType        string
		fProviders          []string
		fRegions            []string
		fServices           []string
		dryRun              bool
		yes                 bool
		interactive         bool
	)
	c := &cobra.Command{
		Use:         "create-all-8",
		Short:       "Risk Misconfiguration Rules List.",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli misconfiguration-ui create-all-8 --org-id ORG_ID --body @request.json\n  flexera-cli misconfiguration-ui create-all-8 --org-id ORG_ID --body @request.json --dry-run\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema misconfiguration-ui create-all-8 --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "Risk_get_misconfig_rules_risk_v1_orgs_orgId_misconfiguration_list_post", "flexera.output": "structured", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if interactive {
				if err := clipkg.GuardInteractive(cmd, bodyRaw); err != nil {
					return err
				}
				if err := clipkg.GatherInteractiveParams(cmd, "Risk_get_misconfig_rules_risk_v1_orgs_orgId_misconfiguration_list_post"); err != nil {
					return err
				}
			}
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Risk_get_misconfig_rules_risk_v1_orgs_orgId_misconfiguration_list_post")
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("accounts") {
				fields["accounts"] = fAccounts
			}
			if cmd.Flags().Changed("compliance-standard") {
				fields["complianceStandard"] = fComplianceStandard
			}
			if cmd.Flags().Changed("control-id") {
				fields["controlId"] = fControlID
			}
			if cmd.Flags().Changed("date") {
				fields["date"] = fDate
			}
			if cmd.Flags().Changed("event-id") {
				fields["eventId"] = fEventID
			}
			if cmd.Flags().Changed("event-time") {
				fields["eventTime"] = fEventTime
			}
			if cmd.Flags().Changed("feature-type") {
				fields["featureType"] = fFeatureType
			}
			if cmd.Flags().Changed("providers") {
				fields["providers"] = fProviders
			}
			if cmd.Flags().Changed("regions") {
				fields["regions"] = fRegions
			}
			if cmd.Flags().Changed("services") {
				fields["services"] = fServices
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				if !interactive {
					return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
				}
			}
			if interactive {
				raw, err = clipkg.GatherInteractiveBody(cmd, "Risk_get_misconfig_rules_risk_v1_orgs_orgId_misconfiguration_list_post", raw)
				if err != nil {
					return err
				}
			}
			var body flexera.RiskGetMisconfigRulesRiskV1OrgsOrgIdMisconfigurationListPostJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("Risk_get_misconfig_rules_risk_v1_orgs_orgId_misconfiguration_list_post", raw, &body, noValidate)
			if err != nil {
				return err
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "POST", Path: "/risk/v1/orgs/{orgId}/misconfiguration/list", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			writePlan.Body, writePlan.Validation, writePlan.RequestSchema = effectiveBody, validation, requestSchema
			var writeDone bool
			var werr error
			if interactive {
				writeDone, werr = clipkg.ConfirmInteractive(cmd, dryRun, yes, writePlan, deps.Printer)
			} else {
				writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			}
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.RiskGetMisconfigRulesRiskV1OrgsOrgIdMisconfigurationListPostWithResponse(cmd.Context(), fmt.Sprint(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringSliceVar(&fAccounts, "accounts", nil, "accounts (body)")
	c.Flags().StringVar(&fComplianceStandard, "compliance-standard", "", "complianceStandard (body)")
	c.Flags().StringVar(&fControlID, "control-id", "", "controlId (body)")
	c.Flags().StringVar(&fDate, "date", "", "date (body)")
	c.Flags().StringVar(&fEventID, "event-id", "", "eventId (body)")
	c.Flags().StringVar(&fEventTime, "event-time", "", "eventTime (body)")
	c.Flags().StringVar(&fFeatureType, "feature-type", "", "featureType (body)")
	c.Flags().StringSliceVar(&fProviders, "providers", nil, "providers (body)")
	c.Flags().StringSliceVar(&fRegions, "regions", nil, "regions (body)")
	c.Flags().StringSliceVar(&fServices, "services", nil, "services (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	c.Flags().BoolVarP(&interactive, "interactive", "i", false, "edit inputs in a terminal form, review a plan and approve with typed yes")
	return c
}

// newMisconfigurationUiCreateAll9Cmd — POST /risk/v1/orgs/{orgId}/misconfiguration/overview (operationId: Risk_get_misconfig_overview_risk_v1_orgs_orgId_misconfiguration_overview_post)
func newMisconfigurationUiCreateAll9Cmd() *cobra.Command {
	var (
		bodyRaw     string
		fAccounts   []string
		fProviders  []string
		fRegions    []string
		fServices   []string
		dryRun      bool
		yes         bool
		interactive bool
	)
	c := &cobra.Command{
		Use:         "create-all-9",
		Short:       "Risk Misconfiguration Overview.",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli misconfiguration-ui create-all-9 --org-id ORG_ID --body @request.json\n  flexera-cli misconfiguration-ui create-all-9 --org-id ORG_ID --body @request.json --dry-run\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema misconfiguration-ui create-all-9 --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "Risk_get_misconfig_overview_risk_v1_orgs_orgId_misconfiguration_overview_post", "flexera.output": "structured", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if interactive {
				if err := clipkg.GuardInteractive(cmd, bodyRaw); err != nil {
					return err
				}
				if err := clipkg.GatherInteractiveParams(cmd, "Risk_get_misconfig_overview_risk_v1_orgs_orgId_misconfiguration_overview_post"); err != nil {
					return err
				}
			}
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Risk_get_misconfig_overview_risk_v1_orgs_orgId_misconfiguration_overview_post")
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("accounts") {
				fields["accounts"] = fAccounts
			}
			if cmd.Flags().Changed("providers") {
				fields["providers"] = fProviders
			}
			if cmd.Flags().Changed("regions") {
				fields["regions"] = fRegions
			}
			if cmd.Flags().Changed("services") {
				fields["services"] = fServices
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				if !interactive {
					return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
				}
			}
			if interactive {
				raw, err = clipkg.GatherInteractiveBody(cmd, "Risk_get_misconfig_overview_risk_v1_orgs_orgId_misconfiguration_overview_post", raw)
				if err != nil {
					return err
				}
			}
			var body flexera.RiskGetMisconfigOverviewRiskV1OrgsOrgIdMisconfigurationOverviewPostJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("Risk_get_misconfig_overview_risk_v1_orgs_orgId_misconfiguration_overview_post", raw, &body, noValidate)
			if err != nil {
				return err
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "POST", Path: "/risk/v1/orgs/{orgId}/misconfiguration/overview", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			writePlan.Body, writePlan.Validation, writePlan.RequestSchema = effectiveBody, validation, requestSchema
			var writeDone bool
			var werr error
			if interactive {
				writeDone, werr = clipkg.ConfirmInteractive(cmd, dryRun, yes, writePlan, deps.Printer)
			} else {
				writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			}
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.RiskGetMisconfigOverviewRiskV1OrgsOrgIdMisconfigurationOverviewPostWithResponse(cmd.Context(), fmt.Sprint(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringSliceVar(&fAccounts, "accounts", nil, "accounts (body)")
	c.Flags().StringSliceVar(&fProviders, "providers", nil, "providers (body)")
	c.Flags().StringSliceVar(&fRegions, "regions", nil, "regions (body)")
	c.Flags().StringSliceVar(&fServices, "services", nil, "services (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	c.Flags().BoolVarP(&interactive, "interactive", "i", false, "edit inputs in a terminal form, review a plan and approve with typed yes")
	return c
}

// newMisconfigurationUiCreateCmd — POST /risk/v1/orgs/{orgId}/misconfiguration/rule/suppress (operationId: Risk_suppress_rule_or_asset_risk_v1_orgs_orgId_misconfiguration_rule_suppress_post)
func newMisconfigurationUiCreateCmd() *cobra.Command {
	var (
		bodyRaw     string
		fUserName   string
		dryRun      bool
		yes         bool
		interactive bool
	)
	c := &cobra.Command{
		Use:         "create",
		Short:       "Suppress API for Rule and Failed Asset",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli misconfiguration-ui create --org-id ORG_ID --body @request.json\n  flexera-cli misconfiguration-ui create --org-id ORG_ID --body @request.json --dry-run\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema misconfiguration-ui create --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "Risk_suppress_rule_or_asset_risk_v1_orgs_orgId_misconfiguration_rule_suppress_post", "flexera.output": "structured", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if interactive {
				if err := clipkg.GuardInteractive(cmd, bodyRaw); err != nil {
					return err
				}
				if err := clipkg.GatherInteractiveParams(cmd, "Risk_suppress_rule_or_asset_risk_v1_orgs_orgId_misconfiguration_rule_suppress_post"); err != nil {
					return err
				}
			}
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Risk_suppress_rule_or_asset_risk_v1_orgs_orgId_misconfiguration_rule_suppress_post")
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("user-name") {
				fields["userName"] = fUserName
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				if !interactive {
					return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
				}
			}
			if interactive {
				raw, err = clipkg.GatherInteractiveBody(cmd, "Risk_suppress_rule_or_asset_risk_v1_orgs_orgId_misconfiguration_rule_suppress_post", raw)
				if err != nil {
					return err
				}
			}
			var body flexera.RiskSuppressRuleOrAssetRiskV1OrgsOrgIdMisconfigurationRuleSuppressPostJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("Risk_suppress_rule_or_asset_risk_v1_orgs_orgId_misconfiguration_rule_suppress_post", raw, &body, noValidate)
			if err != nil {
				return err
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "POST", Path: "/risk/v1/orgs/{orgId}/misconfiguration/rule/suppress", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			writePlan.Body, writePlan.Validation, writePlan.RequestSchema = effectiveBody, validation, requestSchema
			var writeDone bool
			var werr error
			if interactive {
				writeDone, werr = clipkg.ConfirmInteractive(cmd, dryRun, yes, writePlan, deps.Printer)
			} else {
				writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			}
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.RiskSuppressRuleOrAssetRiskV1OrgsOrgIdMisconfigurationRuleSuppressPostWithResponse(cmd.Context(), fmt.Sprint(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&fUserName, "user-name", "", "userName (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	c.Flags().BoolVarP(&interactive, "interactive", "i", false, "edit inputs in a terminal form, review a plan and approve with typed yes")
	return c
}

// newMisconfigurationUiGetRecommendationCmd — GET /recommendation/v1/orgs/{orgId}/misconfiguration/remediation-steps/{riskId}/{remediationMethod} (operationId: Risk_get_remediation_steps_recommendation_v1_orgs_orgId_misconfiguration_remediation_steps_riskId_remediationMethod_get)
func newMisconfigurationUiGetRecommendationCmd() *cobra.Command {
	var (
		riskID            string
		remediationMethod string
	)
	c := &cobra.Command{
		Use:         "get-recommendation",
		Short:       "Remediation Steps for Risk.",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli misconfiguration-ui get-recommendation --org-id ORG_ID --risk-id RISK_ID --remediation-method REMEDIATION_METHOD",
		Annotations: map[string]string{"flexera.operationId": "Risk_get_remediation_steps_recommendation_v1_orgs_orgId_misconfiguration_remediation_steps_riskId_remediationMethod_get", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Risk_get_remediation_steps_recommendation_v1_orgs_orgId_misconfiguration_remediation_steps_riskId_remediationMethod_get")
			if err != nil {
				return err
			}
			_ = effectiveParams
			if strings.TrimSpace(riskID) == "" {
				return fmt.Errorf("--risk-id is required")
			}
			if strings.TrimSpace(remediationMethod) == "" {
				return fmt.Errorf("--remediation-method is required")
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.RiskGetRemediationStepsRecommendationV1OrgsOrgIdMisconfigurationRemediationStepsRiskIdRemediationMethodGetWithResponse(cmd.Context(), fmt.Sprint(deps.Config.OrgID), riskID, remediationMethod)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&riskID, "risk-id", "", "riskId (path, required)")
	c.Flags().StringVar(&remediationMethod, "remediation-method", "", "remediationMethod (path, required)")
	return c
}

// newMisconfigurationUiGetRiskCmd — GET /risk/v1/orgs/{orgId}/misconfiguration/remediation-steps/{riskId}/{remediationMethod} (operationId: Risk_get_remediation_steps_risk_v1_orgs_orgId_misconfiguration_remediation_steps_riskId_remediationMethod_get)
func newMisconfigurationUiGetRiskCmd() *cobra.Command {
	var (
		riskID            string
		remediationMethod string
	)
	c := &cobra.Command{
		Use:         "get-risk",
		Short:       "Remediation Steps for Risk.",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli misconfiguration-ui get-risk --org-id ORG_ID --risk-id RISK_ID --remediation-method REMEDIATION_METHOD",
		Annotations: map[string]string{"flexera.operationId": "Risk_get_remediation_steps_risk_v1_orgs_orgId_misconfiguration_remediation_steps_riskId_remediationMethod_get", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Risk_get_remediation_steps_risk_v1_orgs_orgId_misconfiguration_remediation_steps_riskId_remediationMethod_get")
			if err != nil {
				return err
			}
			_ = effectiveParams
			if strings.TrimSpace(riskID) == "" {
				return fmt.Errorf("--risk-id is required")
			}
			if strings.TrimSpace(remediationMethod) == "" {
				return fmt.Errorf("--remediation-method is required")
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.RiskGetRemediationStepsRiskV1OrgsOrgIdMisconfigurationRemediationStepsRiskIdRemediationMethodGetWithResponse(cmd.Context(), fmt.Sprint(deps.Config.OrgID), riskID, remediationMethod)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&riskID, "risk-id", "", "riskId (path, required)")
	c.Flags().StringVar(&remediationMethod, "remediation-method", "", "remediationMethod (path, required)")
	return c
}

// newMisconfigurationUiListRecommendationCmd — GET /recommendation/v1/orgs/{orgId}/misconfiguration/risk/{riskId}/details (operationId: Risk_get_risk_details_recommendation_v1_orgs_orgId_misconfiguration_risk_riskId_details_get)
func newMisconfigurationUiListRecommendationCmd() *cobra.Command {
	var (
		riskID   string
		provider string
	)
	c := &cobra.Command{
		Use:         "list-recommendation",
		Short:       "Risk Details",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli misconfiguration-ui list-recommendation --org-id ORG_ID --risk-id RISK_ID",
		Annotations: map[string]string{"flexera.operationId": "Risk_get_risk_details_recommendation_v1_orgs_orgId_misconfiguration_risk_riskId_details_get", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Risk_get_risk_details_recommendation_v1_orgs_orgId_misconfiguration_risk_riskId_details_get")
			if err != nil {
				return err
			}
			_ = effectiveParams
			if strings.TrimSpace(riskID) == "" {
				return fmt.Errorf("--risk-id is required")
			}
			params := flexera.RiskGetRiskDetailsRecommendationV1OrgsOrgIdMisconfigurationRiskRiskIdDetailsGetParams{}
			if cmd.Flags().Changed("provider") {
				v := provider
				params.Provider = &v
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.RiskGetRiskDetailsRecommendationV1OrgsOrgIdMisconfigurationRiskRiskIdDetailsGetWithResponse(cmd.Context(), fmt.Sprint(deps.Config.OrgID), riskID, &params)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&riskID, "risk-id", "", "riskId (path, required)")
	c.Flags().StringVar(&provider, "provider", "", "provider (query)")
	return c
}

// newMisconfigurationUiListRiskCmd — GET /risk/v1/orgs/{orgId}/misconfiguration/risk/{riskId}/details (operationId: Risk_get_risk_details_risk_v1_orgs_orgId_misconfiguration_risk_riskId_details_get)
func newMisconfigurationUiListRiskCmd() *cobra.Command {
	var (
		riskID   string
		provider string
	)
	c := &cobra.Command{
		Use:         "list-risk",
		Short:       "Risk Details",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli misconfiguration-ui list-risk --org-id ORG_ID --risk-id RISK_ID",
		Annotations: map[string]string{"flexera.operationId": "Risk_get_risk_details_risk_v1_orgs_orgId_misconfiguration_risk_riskId_details_get", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Risk_get_risk_details_risk_v1_orgs_orgId_misconfiguration_risk_riskId_details_get")
			if err != nil {
				return err
			}
			_ = effectiveParams
			if strings.TrimSpace(riskID) == "" {
				return fmt.Errorf("--risk-id is required")
			}
			params := flexera.RiskGetRiskDetailsRiskV1OrgsOrgIdMisconfigurationRiskRiskIdDetailsGetParams{}
			if cmd.Flags().Changed("provider") {
				v := provider
				params.Provider = &v
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.RiskGetRiskDetailsRiskV1OrgsOrgIdMisconfigurationRiskRiskIdDetailsGetWithResponse(cmd.Context(), fmt.Sprint(deps.Config.OrgID), riskID, &params)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&riskID, "risk-id", "", "riskId (path, required)")
	c.Flags().StringVar(&provider, "provider", "", "provider (query)")
	return c
}
