// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag Managed Application Event.

package managedapplicationevent

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "managed-application-event" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "managed-application-event",
		Short: "Managed Application Event operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newManagedApplicationEventGetCmd(),
		newManagedApplicationEventListCmd(),
	)
	return c
}

// newManagedApplicationEventGetCmd — GET /saas/v1/orgs/{orgId}/app-events/{eventId} (operationId: Saas_Managed_Application_Event_show)
func newManagedApplicationEventGetCmd() *cobra.Command {
	var (
		eventID string
	)
	c := &cobra.Command{
		Use:         "get",
		Short:       "Show managed application event",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli managed-application-event get --org-id ORG_ID --event-id EVENT_ID",
		Annotations: map[string]string{"flexera.operationId": "Saas_Managed_Application_Event_show", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Saas_Managed_Application_Event_show")
			if err != nil {
				return err
			}
			_ = effectiveParams
			if strings.TrimSpace(eventID) == "" {
				return fmt.Errorf("--event-id is required")
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.SaasManagedApplicationEventShowWithResponse(cmd.Context(), deps.Config.OrgID, eventID)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&eventID, "event-id", "", "eventId (path, required)")
	return c
}

// newManagedApplicationEventListCmd — GET /saas/v1/orgs/{orgId}/app-events (operationId: Saas_Managed_Application_Event_index)
func newManagedApplicationEventListCmd() *cobra.Command {
	var (
		filter               string
		mostRecentEventsOnly bool
		noPaginate           bool
		skipToken            string
	)
	c := &cobra.Command{
		Use:         "list",
		Short:       "List managed application events",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli managed-application-event list --org-id ORG_ID",
		Annotations: map[string]string{"flexera.operationId": "Saas_Managed_Application_Event_index", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Saas_Managed_Application_Event_index")
			if err != nil {
				return err
			}
			_ = effectiveParams
			params := flexera.SaasManagedApplicationEventIndexParams{}
			if cmd.Flags().Changed("filter") {
				v := filter
				params.Filter = &v
			}
			if cmd.Flags().Changed("most-recent-events-only") {
				v := mostRecentEventsOnly
				params.MostRecentEventsOnly = &v
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			var initialSkipToken *string
			if t := strings.TrimSpace(skipToken); t != "" {
				initialSkipToken = &t
			}
			result, err := flexera.CollectPages(cmd.Context(), noPaginate, initialSkipToken,
				func(ctx context.Context, st *string) (any, error) {
					p := params
					p.SkipToken = st
					resp, callErr := client.SaasManagedApplicationEventIndexWithResponse(ctx, deps.Config.OrgID, &p)
					if callErr != nil {
						return nil, callErr
					}
					switch resp.StatusCode() {
					case 200:
						if resp.JSON200 != nil {
							if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
								return resp.JSON200, nil
							}
							return clipkg.DecodeResponseJSON(resp.Body)
						}
					}
					return nil, flexera.ResponseError(resp.StatusCode(), resp.Body)
				})
			if err != nil {
				return err
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
		},
	}
	c.Flags().StringVar(&filter, "filter", "", "filter (query)")
	c.Flags().BoolVar(&mostRecentEventsOnly, "most-recent-events-only", false, "mostRecentEventsOnly (query)")
	c.Flags().BoolVar(&noPaginate, "no-paginate", false, "return only the first page (do not follow nextPage)")
	c.Flags().StringVar(&skipToken, "skip-token", "", "resume pagination from this token")
	return c
}
