// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag org_dashboards.

package orgdashboards

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "org-dashboards" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "org-dashboards",
		Short: "org_dashboards operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newOrgDashboardsCreateCmd(),
		newOrgDashboardsDeleteCmd(),
		newOrgDashboardsGetCmd(),
		newOrgDashboardsListCmd(),
		newOrgDashboardsReplaceCmd(),
	)
	return c
}

// newOrgDashboardsCreateCmd — POST /bill-analysis/orgs/{orgId}/dashboards (operationId: BillAnalysis_org_dashboards_create)
func newOrgDashboardsCreateCmd() *cobra.Command {
	var (
		bodyRaw     string
		fArea       string
		fName       string
		fScope      []string
		fVisibility string
		dryRun      bool
		yes         bool
		interactive bool
	)
	c := &cobra.Command{
		Use:         "create",
		Short:       "create org_dashboards",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli bill-analysis org-dashboards create --org-id ORG_ID --body @request.json\n  flexera-cli bill-analysis org-dashboards create --org-id ORG_ID --body @request.json --dry-run\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema bill-analysis org-dashboards create --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "BillAnalysis_org_dashboards_create", "flexera.output": "structured", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if interactive {
				if err := clipkg.GuardInteractive(cmd, bodyRaw); err != nil {
					return err
				}
				if err := clipkg.GatherInteractiveParams(cmd, "BillAnalysis_org_dashboards_create"); err != nil {
					return err
				}
			}
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "BillAnalysis_org_dashboards_create")
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("area") {
				fields["area"] = fArea
			}
			if cmd.Flags().Changed("name") {
				fields["name"] = fName
			}
			if cmd.Flags().Changed("scope") {
				fields["scope"] = fScope
			}
			if cmd.Flags().Changed("visibility") {
				fields["visibility"] = fVisibility
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				if !interactive {
					return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
				}
			}
			if interactive {
				raw, err = clipkg.GatherInteractiveBody(cmd, "BillAnalysis_org_dashboards_create", raw)
				if err != nil {
					return err
				}
			}
			var body flexera.BillAnalysisOrgDashboardsCreateJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("BillAnalysis_org_dashboards_create", raw, &body, noValidate)
			if err != nil {
				return err
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "POST", Path: "/bill-analysis/orgs/{orgId}/dashboards", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			writePlan.Body, writePlan.Validation, writePlan.RequestSchema = effectiveBody, validation, requestSchema
			var writeDone bool
			var werr error
			if interactive {
				writeDone, werr = clipkg.ConfirmInteractive(cmd, dryRun, yes, writePlan, deps.Printer)
			} else {
				writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			}
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.BillAnalysisOrgDashboardsCreateWithResponse(cmd.Context(), int64(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 201:
				if resp.JSON201 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON201)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&fArea, "area", "", "area (body)")
	c.Flags().StringVar(&fName, "name", "", "name (body)")
	c.Flags().StringSliceVar(&fScope, "scope", nil, "scope (body)")
	c.Flags().StringVar(&fVisibility, "visibility", "", "visibility (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	c.Flags().BoolVarP(&interactive, "interactive", "i", false, "edit inputs in a terminal form, review a plan and approve with typed yes")
	return c
}

// newOrgDashboardsDeleteCmd — DELETE /bill-analysis/orgs/{orgId}/dashboards/{id} (operationId: BillAnalysis_org_dashboards_destroy)
func newOrgDashboardsDeleteCmd() *cobra.Command {
	var (
		id     string
		dryRun bool
		yes    bool
	)
	c := &cobra.Command{
		Use:         "delete",
		Short:       "destroy org_dashboards",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli bill-analysis org-dashboards delete --org-id ORG_ID --id ID\n  flexera-cli bill-analysis org-dashboards delete --org-id ORG_ID --id ID --dry-run",
		Annotations: map[string]string{"flexera.operationId": "BillAnalysis_org_dashboards_destroy", "flexera.output": "text", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "BillAnalysis_org_dashboards_destroy")
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "DELETE", Path: "/bill-analysis/orgs/{orgId}/dashboards/{id}", Params: planParams, Destructive: true}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			var writeDone bool
			var werr error
			writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.BillAnalysisOrgDashboardsDestroyWithResponse(cmd.Context(), int64(deps.Config.OrgID), id)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 204:
				fmt.Fprintln(deps.Stdout, "OK")
				return nil
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newOrgDashboardsGetCmd — GET /bill-analysis/orgs/{orgId}/dashboards/{id} (operationId: BillAnalysis_org_dashboards_show)
func newOrgDashboardsGetCmd() *cobra.Command {
	var (
		id string
	)
	c := &cobra.Command{
		Use:         "get",
		Short:       "show org_dashboards",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli bill-analysis org-dashboards get --org-id ORG_ID --id ID",
		Annotations: map[string]string{"flexera.operationId": "BillAnalysis_org_dashboards_show", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "BillAnalysis_org_dashboards_show")
			if err != nil {
				return err
			}
			_ = effectiveParams
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.BillAnalysisOrgDashboardsShowWithResponse(cmd.Context(), int64(deps.Config.OrgID), id)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	return c
}

// newOrgDashboardsListCmd — GET /bill-analysis/orgs/{orgId}/dashboards (operationId: BillAnalysis_org_dashboards_index)
func newOrgDashboardsListCmd() *cobra.Command {
	var (
		area       string
		visibility string
	)
	c := &cobra.Command{
		Use:         "list",
		Short:       "index org_dashboards",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli bill-analysis org-dashboards list --org-id ORG_ID",
		Annotations: map[string]string{"flexera.operationId": "BillAnalysis_org_dashboards_index", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "BillAnalysis_org_dashboards_index")
			if err != nil {
				return err
			}
			_ = effectiveParams
			params := flexera.BillAnalysisOrgDashboardsIndexParams{}
			if cmd.Flags().Changed("area") {
				v := area
				params.Area = &v
			}
			if cmd.Flags().Changed("visibility") {
				ev := flexera.BillAnalysisOrgDashboardsIndexParamsVisibility(visibility)
				params.Visibility = &ev
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.BillAnalysisOrgDashboardsIndexWithResponse(cmd.Context(), int64(deps.Config.OrgID), &params)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&area, "area", "", "area (query)")
	c.Flags().StringVar(&visibility, "visibility", "", "visibility (query)")
	return c
}

// newOrgDashboardsReplaceCmd — PUT /bill-analysis/orgs/{orgId}/dashboards/{id} (operationId: BillAnalysis_org_dashboards_replace)
func newOrgDashboardsReplaceCmd() *cobra.Command {
	var (
		id          string
		bodyRaw     string
		fArea       string
		fName       string
		fScope      []string
		fVisibility string
		dryRun      bool
		yes         bool
		interactive bool
	)
	c := &cobra.Command{
		Use:         "replace",
		Short:       "replace org_dashboards",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli bill-analysis org-dashboards replace --org-id ORG_ID --id ID --body @request.json\n  flexera-cli bill-analysis org-dashboards replace --org-id ORG_ID --id ID --body @request.json --dry-run\nValidated illustrative body, when available (review before use):\n  flexera-cli cli schema bill-analysis org-dashboards replace --example > request.json",
		Annotations: map[string]string{"flexera.operationId": "BillAnalysis_org_dashboards_replace", "flexera.output": "structured", "flexera.validation": "body"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if interactive {
				if err := clipkg.GuardInteractive(cmd, bodyRaw); err != nil {
					return err
				}
				if err := clipkg.GatherInteractiveParams(cmd, "BillAnalysis_org_dashboards_replace"); err != nil {
					return err
				}
			}
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "BillAnalysis_org_dashboards_replace")
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("area") {
				fields["area"] = fArea
			}
			if cmd.Flags().Changed("name") {
				fields["name"] = fName
			}
			if cmd.Flags().Changed("scope") {
				fields["scope"] = fScope
			}
			if cmd.Flags().Changed("visibility") {
				fields["visibility"] = fVisibility
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				if !interactive {
					return clipkg.Exit(2, fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags"))
				}
			}
			if interactive {
				raw, err = clipkg.GatherInteractiveBody(cmd, "BillAnalysis_org_dashboards_replace", raw)
				if err != nil {
					return err
				}
			}
			var body flexera.BillAnalysisOrgDashboardsReplaceJSONRequestBody
			noValidate, err := cmd.Flags().GetBool(clipkg.FlagNoValidate)
			if err != nil {
				return clipkg.Exit(2, err)
			}
			effectiveBody, validation, requestSchema, err := clipkg.PrepareRequestBody("BillAnalysis_org_dashboards_replace", raw, &body, noValidate)
			if err != nil {
				return err
			}
			planParams := effectiveParams
			writePlan := clipkg.Plan{Command: cmd.CommandPath(), Method: "PUT", Path: "/bill-analysis/orgs/{orgId}/dashboards/{id}", Params: planParams, Destructive: false}
			writePlan.OrgID = deps.Config.OrgID
			planParams["org-id"] = deps.Config.OrgID
			writePlan.Body, writePlan.Validation, writePlan.RequestSchema = effectiveBody, validation, requestSchema
			var writeDone bool
			var werr error
			if interactive {
				writeDone, werr = clipkg.ConfirmInteractive(cmd, dryRun, yes, writePlan, deps.Printer)
			} else {
				writeDone, werr = clipkg.ConfirmPlan(dryRun, yes, deps.Stdout, writePlan, deps.Printer)
			}
			if werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.BillAnalysisOrgDashboardsReplaceWithResponse(cmd.Context(), int64(deps.Config.OrgID), id, body)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	c.Flags().StringVar(&fArea, "area", "", "area (body)")
	c.Flags().StringVar(&fName, "name", "", "name (body)")
	c.Flags().StringSliceVar(&fScope, "scope", nil, "scope (body)")
	c.Flags().StringVar(&fVisibility, "visibility", "", "visibility (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	c.Flags().BoolVarP(&interactive, "interactive", "i", false, "edit inputs in a terminal form, review a plan and approve with typed yes")
	return c
}
