// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag Customization Type.

package customizationtype

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "customization-type" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "customization-type",
		Short: "Customization Type operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newCustomizationTypeGetCmd(),
		newCustomizationTypeListCmd(),
	)
	return c
}

// newCustomizationTypeGetCmd — GET /iam/v1/orgs/{orgId}/customization-types/{id} (operationId: Iam_Customization_Type_show)
func newCustomizationTypeGetCmd() *cobra.Command {
	var (
		id   string
		view string
	)
	c := &cobra.Command{
		Use:         "get",
		Short:       "Returns a specific customization type",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli iam customization-type get --org-id ORG_ID --id ID",
		Annotations: map[string]string{"flexera.operationId": "Iam_Customization_Type_show", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Iam_Customization_Type_show")
			if err != nil {
				return err
			}
			_ = effectiveParams
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			params := flexera.IamCustomizationTypeShowParams{}
			if cmd.Flags().Changed("view") {
				ev := flexera.IamCustomizationTypeShowParamsView(view)
				params.View = &ev
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.IamCustomizationTypeShowWithResponse(cmd.Context(), deps.Config.OrgID, id, &params)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	c.Flags().StringVar(&view, "view", "", "view (query)")
	return c
}

// newCustomizationTypeListCmd — GET /iam/v1/orgs/{orgId}/customization-types (operationId: Iam_Customization_Type_index)
func newCustomizationTypeListCmd() *cobra.Command {
	var (
		view       string
		filter     string
		noPaginate bool
		skipToken  string
	)
	c := &cobra.Command{
		Use:         "list",
		Short:       "Returns types of customizations that are available to an org",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli iam customization-type list --org-id ORG_ID",
		Annotations: map[string]string{"flexera.operationId": "Iam_Customization_Type_index", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Iam_Customization_Type_index")
			if err != nil {
				return err
			}
			_ = effectiveParams
			params := flexera.IamCustomizationTypeIndexParams{}
			if cmd.Flags().Changed("view") {
				ev := flexera.IamCustomizationTypeIndexParamsView(view)
				params.View = &ev
			}
			if cmd.Flags().Changed("filter") {
				v := filter
				params.Filter = &v
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			var initialSkipToken *string
			if t := strings.TrimSpace(skipToken); t != "" {
				initialSkipToken = &t
			}
			result, err := flexera.CollectPages(cmd.Context(), noPaginate, initialSkipToken,
				func(ctx context.Context, st *string) (any, error) {
					p := params
					p.SkipToken = st
					resp, callErr := client.IamCustomizationTypeIndexWithResponse(ctx, deps.Config.OrgID, &p)
					if callErr != nil {
						return nil, callErr
					}
					switch resp.StatusCode() {
					case 200:
						if resp.JSON200 != nil {
							if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
								return resp.JSON200, nil
							}
							return clipkg.DecodeResponseJSON(resp.Body)
						}
					}
					return nil, flexera.ResponseError(resp.StatusCode(), resp.Body)
				})
			if err != nil {
				return err
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
		},
	}
	c.Flags().StringVar(&view, "view", "", "view (query)")
	c.Flags().StringVar(&filter, "filter", "", "filter (query)")
	c.Flags().BoolVar(&noPaginate, "no-paginate", false, "return only the first page (do not follow nextPage)")
	c.Flags().StringVar(&skipToken, "skip-token", "", "resume pagination from this token")
	return c
}
