// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag Bill Connect - Azure CSP.

package billconnectazurecsp

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "bill-connect-azure-csp" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "bill-connect-azure-csp",
		Short: "Bill Connect - Azure CSP operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newBillConnectAzureCSPCreateCmd(),
		newBillConnectAzureCSPDeleteCmd(),
		newBillConnectAzureCSPGetCmd(),
		newBillConnectAzureCSPListCmd(),
		newBillConnectAzureCSPUpdateCmd(),
	)
	return c
}

// newBillConnectAzureCSPCreateCmd — POST /finops-onboarding/v1/orgs/{orgId}/bill-connects/azure-csp (operationId: FinopsOnboarding_Bill_Connect_Azure_CSP_create)
func newBillConnectAzureCSPCreateCmd() *cobra.Command {
	var (
		bodyRaw             string
		fBillingAccountID   string
		fClientID           string
		fClientSecret       string
		fProxy              string
		fStartBillingPeriod string
		fTenantID           string
		dryRun              bool
		yes                 bool
	)
	c := &cobra.Command{
		Use:   "create",
		Short: "Create an Azure CSP bill connect",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("billing-account-id") {
				fields["billingAccountId"] = fBillingAccountID
			}
			if cmd.Flags().Changed("client-id") {
				fields["clientId"] = fClientID
			}
			if cmd.Flags().Changed("client-secret") {
				fields["clientSecret"] = fClientSecret
			}
			if cmd.Flags().Changed("proxy") {
				fields["proxy"] = fProxy
			}
			if cmd.Flags().Changed("start-billing-period") {
				fields["startBillingPeriod"] = fStartBillingPeriod
			}
			if cmd.Flags().Changed("tenant-id") {
				fields["tenantId"] = fTenantID
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.FinopsOnboardingBillConnectAzureCSPCreateJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			writePlan := map[string]any{"method": "POST /finops-onboarding/v1/orgs/{orgId}/bill-connects/azure-csp"}
			writePlan["orgId"] = deps.Config.OrgID
			writePlan["body"] = json.RawMessage(raw)
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, false, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.FinopsOnboardingBillConnectAzureCSPCreateWithResponse(cmd.Context(), deps.Config.OrgID, body)
			if err != nil {
				return err
			}
			if resp.JSON201 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON201)
		},
	}
	c.Flags().StringVar(&fBillingAccountID, "billing-account-id", "", "billingAccountId (body)")
	c.Flags().StringVar(&fClientID, "client-id", "", "clientId (body)")
	c.Flags().StringVar(&fClientSecret, "client-secret", "", "clientSecret (body)")
	c.Flags().StringVar(&fProxy, "proxy", "", "proxy (body)")
	c.Flags().StringVar(&fStartBillingPeriod, "start-billing-period", "", "startBillingPeriod (body)")
	c.Flags().StringVar(&fTenantID, "tenant-id", "", "tenantId (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newBillConnectAzureCSPDeleteCmd — DELETE /finops-onboarding/v1/orgs/{orgId}/bill-connects/azure-csp/{id} (operationId: FinopsOnboarding_Bill_Connect_Azure_CSP_delete)
func newBillConnectAzureCSPDeleteCmd() *cobra.Command {
	var (
		id     string
		dryRun bool
		yes    bool
	)
	c := &cobra.Command{
		Use:   "delete",
		Short: "Delete an Azure CSP bill connect",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			writePlan := map[string]any{"method": "DELETE /finops-onboarding/v1/orgs/{orgId}/bill-connects/azure-csp/{id}"}
			writePlan["orgId"] = deps.Config.OrgID
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, true, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.FinopsOnboardingBillConnectAzureCSPDeleteWithResponse(cmd.Context(), deps.Config.OrgID, id)
			if err != nil {
				return err
			}
			if resp.StatusCode() != 204 {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			fmt.Fprintln(deps.Stdout, "OK")
			return nil
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newBillConnectAzureCSPGetCmd — GET /finops-onboarding/v1/orgs/{orgId}/bill-connects/azure-csp/{id} (operationId: FinopsOnboarding_Bill_Connect_Azure_CSP_show)
func newBillConnectAzureCSPGetCmd() *cobra.Command {
	var (
		id string
	)
	c := &cobra.Command{
		Use:   "get",
		Short: "Show an Azure CSP bill connect",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			resp, err := client.FinopsOnboardingBillConnectAzureCSPShowWithResponse(cmd.Context(), deps.Config.OrgID, id)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	return c
}

// newBillConnectAzureCSPListCmd — GET /finops-onboarding/v1/orgs/{orgId}/bill-connects/azure-csp/{id}/validation (operationId: FinopsOnboarding_Bill_Connect_Azure_CSP_validate)
func newBillConnectAzureCSPListCmd() *cobra.Command {
	var (
		id string
	)
	c := &cobra.Command{
		Use:   "list",
		Short: "Validate the credentials stored for an Azure CSP bill connect",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			resp, err := client.FinopsOnboardingBillConnectAzureCSPValidateWithResponse(cmd.Context(), deps.Config.OrgID, id)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	return c
}

// newBillConnectAzureCSPUpdateCmd — PATCH /finops-onboarding/v1/orgs/{orgId}/bill-connects/azure-csp/{id} (operationId: FinopsOnboarding_Bill_Connect_Azure_CSP_update)
func newBillConnectAzureCSPUpdateCmd() *cobra.Command {
	var (
		id                  string
		bodyRaw             string
		fBillingAccountID   string
		fClientID           string
		fClientSecret       string
		fProxy              string
		fStartBillingPeriod string
		fTenantID           string
		dryRun              bool
		yes                 bool
	)
	c := &cobra.Command{
		Use:   "update",
		Short: "Update an Azure CSP bill connect",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("billing-account-id") {
				fields["billingAccountId"] = fBillingAccountID
			}
			if cmd.Flags().Changed("client-id") {
				fields["clientId"] = fClientID
			}
			if cmd.Flags().Changed("client-secret") {
				fields["clientSecret"] = fClientSecret
			}
			if cmd.Flags().Changed("proxy") {
				fields["proxy"] = fProxy
			}
			if cmd.Flags().Changed("start-billing-period") {
				fields["startBillingPeriod"] = fStartBillingPeriod
			}
			if cmd.Flags().Changed("tenant-id") {
				fields["tenantId"] = fTenantID
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.FinopsOnboardingBillConnectAzureCSPUpdateJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			writePlan := map[string]any{"method": "PATCH /finops-onboarding/v1/orgs/{orgId}/bill-connects/azure-csp/{id}"}
			writePlan["orgId"] = deps.Config.OrgID
			writePlan["body"] = json.RawMessage(raw)
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, false, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.FinopsOnboardingBillConnectAzureCSPUpdateWithResponse(cmd.Context(), deps.Config.OrgID, id, body)
			if err != nil {
				return err
			}
			if resp.StatusCode() != 204 {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			fmt.Fprintln(deps.Stdout, "OK")
			return nil
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	c.Flags().StringVar(&fBillingAccountID, "billing-account-id", "", "billingAccountId (body)")
	c.Flags().StringVar(&fClientID, "client-id", "", "clientId (body)")
	c.Flags().StringVar(&fClientSecret, "client-secret", "", "clientSecret (body)")
	c.Flags().StringVar(&fProxy, "proxy", "", "proxy (body)")
	c.Flags().StringVar(&fStartBillingPeriod, "start-billing-period", "", "startBillingPeriod (body)")
	c.Flags().StringVar(&fTenantID, "tenant-id", "", "tenantId (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}
