// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag CustomCatalog.

package customcatalog

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "custom-catalog" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "custom-catalog",
		Short: "CustomCatalog operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newCustomCatalogListCmd(),
		newCustomCatalogTagCmd(),
		newCustomCatalogReplaceCmd(),
	)
	return c
}

// newCustomCatalogListCmd — GET /policy/v1/orgs/{orgId}/custom-catalog (operationId: Policy_CustomCatalog_index)
func newCustomCatalogListCmd() *cobra.Command {
	var (
		filter        string
		orderBy       string
		limit         int64
		catalogSource string
		noPaginate    bool
		skipToken     string
	)
	c := &cobra.Command{
		Use:   "list",
		Short: "Index published templates with applied custom catalog settings",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			params := flexera.PolicyCustomCatalogIndexParams{}
			if cmd.Flags().Changed("filter") {
				v := filter
				params.Filter = &v
			}
			if cmd.Flags().Changed("order-by") {
				v := orderBy
				params.OrderBy = &v
			}
			if cmd.Flags().Changed("limit") {
				v := limit
				params.Limit = &v
			}
			if cmd.Flags().Changed("catalog-source") {
				ev := flexera.PolicyCustomCatalogIndexParamsCatalogSource(catalogSource)
				params.CatalogSource = &ev
			}
			var initialSkipToken *string
			if t := strings.TrimSpace(skipToken); t != "" {
				initialSkipToken = &t
			}
			result, err := flexera.CollectPages(cmd.Context(), noPaginate, initialSkipToken,
				func(ctx context.Context, st *string) (any, error) {
					p := params
					p.SkipToken = st
					resp, callErr := client.PolicyCustomCatalogIndexWithResponse(ctx, int64(deps.Config.OrgID), &p)
					if callErr != nil {
						return nil, callErr
					}
					if resp.JSON200 == nil {
						return nil, flexera.ResponseError(resp.StatusCode(), resp.Body)
					}
					return resp.JSON200, nil
				})
			if err != nil {
				return err
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
		},
	}
	c.Flags().StringVar(&filter, "filter", "", "filter (query)")
	c.Flags().StringVar(&orderBy, "order-by", "", "orderBy (query)")
	c.Flags().Int64Var(&limit, "limit", 0, "limit (query)")
	c.Flags().StringVar(&catalogSource, "catalog-source", "", "catalogSource (query)")
	c.Flags().BoolVar(&noPaginate, "no-paginate", false, "return only the first page (do not follow nextPage)")
	c.Flags().StringVar(&skipToken, "skip-token", "", "resume pagination from this token")
	return c
}

// newCustomCatalogTagCmd — GET /policy/v1/orgs/{orgId}/custom-catalog/{publishedTemplateId}/tag (operationId: Policy_CustomCatalog_showTag)
func newCustomCatalogTagCmd() *cobra.Command {
	var (
		publishedTemplateID string
	)
	c := &cobra.Command{
		Use:   "tag",
		Short: "Retrieve custom catalog tags for a published template in an organization",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(publishedTemplateID) == "" {
				return fmt.Errorf("--published-template-id is required")
			}
			resp, err := client.PolicyCustomCatalogShowTagWithResponse(cmd.Context(), int64(deps.Config.OrgID), publishedTemplateID)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringVar(&publishedTemplateID, "published-template-id", "", "publishedTemplateId (path, required)")
	return c
}

// newCustomCatalogReplaceCmd — PUT /policy/v1/orgs/{orgId}/custom-catalog/{publishedTemplateId}/tag (operationId: Policy_CustomCatalog_upsertTag)
func newCustomCatalogReplaceCmd() *cobra.Command {
	var (
		publishedTemplateID  string
		bodyRaw              string
		fChildOrgsVisibility bool
		dryRun               bool
		yes                  bool
	)
	c := &cobra.Command{
		Use:   "replace",
		Short: "Create or update custom catalog tags for a published template under an MSP parent organization",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(publishedTemplateID) == "" {
				return fmt.Errorf("--published-template-id is required")
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("child-orgs-visibility") {
				fields["childOrgsVisibility"] = fChildOrgsVisibility
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.PolicyCustomCatalogUpsertTagJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			writePlan := map[string]any{"method": "PUT /policy/v1/orgs/{orgId}/custom-catalog/{publishedTemplateId}/tag"}
			writePlan["orgId"] = deps.Config.OrgID
			writePlan["body"] = json.RawMessage(raw)
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, false, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.PolicyCustomCatalogUpsertTagWithResponse(cmd.Context(), int64(deps.Config.OrgID), publishedTemplateID, body)
			if err != nil {
				return err
			}
			if resp.StatusCode() != 204 {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			fmt.Fprintln(deps.Stdout, "OK")
			return nil
		},
	}
	c.Flags().StringVar(&publishedTemplateID, "published-template-id", "", "publishedTemplateId (path, required)")
	c.Flags().BoolVar(&fChildOrgsVisibility, "child-orgs-visibility", false, "childOrgsVisibility (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}
