// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag Customization Value.

package customizationvalue

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "customization-value" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "customization-value",
		Short: "Customization Value operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newCustomizationValueDeleteCmd(),
		newCustomizationValueGetCmd(),
		newCustomizationValueListCmd(),
		newCustomizationValueReplaceCmd(),
	)
	return c
}

// newCustomizationValueDeleteCmd — DELETE /policy/v1/orgs/{orgId}/customization-values/{customizationTypeId} (operationId: Policy_Customization_Value_delete)
func newCustomizationValueDeleteCmd() *cobra.Command {
	var (
		customizationTypeID string
		dryRun              bool
		yes                 bool
	)
	c := &cobra.Command{
		Use:   "delete",
		Short: "Deletes a customization value",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(customizationTypeID) == "" {
				return fmt.Errorf("--customization-type-id is required")
			}
			writePlan := map[string]any{"method": "DELETE /policy/v1/orgs/{orgId}/customization-values/{customizationTypeId}"}
			writePlan["orgId"] = deps.Config.OrgID
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, true, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.PolicyCustomizationValueDeleteWithResponse(cmd.Context(), int64(deps.Config.OrgID), customizationTypeID)
			if err != nil {
				return err
			}
			if resp.StatusCode() != 204 {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			fmt.Fprintln(deps.Stdout, "OK")
			return nil
		},
	}
	c.Flags().StringVar(&customizationTypeID, "customization-type-id", "", "customizationTypeId (path, required)")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newCustomizationValueGetCmd — GET /policy/v1/orgs/{orgId}/customization-values/{customizationTypeId} (operationId: Policy_Customization_Value_show)
func newCustomizationValueGetCmd() *cobra.Command {
	var (
		customizationTypeID string
	)
	c := &cobra.Command{
		Use:   "get",
		Short: "Retrieves a customization value",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(customizationTypeID) == "" {
				return fmt.Errorf("--customization-type-id is required")
			}
			resp, err := client.PolicyCustomizationValueShowWithResponse(cmd.Context(), int64(deps.Config.OrgID), customizationTypeID)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringVar(&customizationTypeID, "customization-type-id", "", "customizationTypeId (path, required)")
	return c
}

// newCustomizationValueListCmd — GET /policy/v1/orgs/{orgId}/customization-values (operationId: Policy_Customization_Value_index)
func newCustomizationValueListCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "list",
		Short: "Retrieves a collection of customization values",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			params := flexera.PolicyCustomizationValueIndexParams{}
			resp, err := client.PolicyCustomizationValueIndexWithResponse(cmd.Context(), int64(deps.Config.OrgID), &params)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	return c
}

// newCustomizationValueReplaceCmd — PUT /policy/v1/orgs/{orgId}/customization-values/{customizationTypeId} (operationId: Policy_Customization_Value_upsert)
func newCustomizationValueReplaceCmd() *cobra.Command {
	var (
		customizationTypeID string
		bodyRaw             string
		fValue              string
		dryRun              bool
		yes                 bool
	)
	c := &cobra.Command{
		Use:   "replace",
		Short: "Creates or updates a customization value",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(customizationTypeID) == "" {
				return fmt.Errorf("--customization-type-id is required")
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("value") {
				fields["value"] = fValue
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.PolicyCustomizationValueUpsertJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			writePlan := map[string]any{"method": "PUT /policy/v1/orgs/{orgId}/customization-values/{customizationTypeId}"}
			writePlan["orgId"] = deps.Config.OrgID
			writePlan["body"] = json.RawMessage(raw)
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, false, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.PolicyCustomizationValueUpsertWithResponse(cmd.Context(), int64(deps.Config.OrgID), customizationTypeID, body)
			if err != nil {
				return err
			}
			if resp.StatusCode() != 204 {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			fmt.Fprintln(deps.Stdout, "OK")
			return nil
		},
	}
	c.Flags().StringVar(&customizationTypeID, "customization-type-id", "", "customizationTypeId (path, required)")
	c.Flags().StringVar(&fValue, "value", "", "value (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}
