// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag custom_dimensions.

package customdimensions

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "custom-dimensions" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "custom-dimensions",
		Short: "custom_dimensions operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newCustomDimensionsCreateCmd(),
		newCustomDimensionsDeleteCmd(),
		newCustomDimensionsGetCmd(),
		newCustomDimensionsListCmd(),
		newCustomDimensionsReplaceCmd(),
	)
	return c
}

// newCustomDimensionsCreateCmd — POST /bill-analysis/orgs/{orgId}/custom/dimensions (operationId: BillAnalysis_custom_dimensions_create)
func newCustomDimensionsCreateCmd() *cobra.Command {
	var (
		bodyRaw string
		fName   string
		fTagKey string
		dryRun  bool
		yes     bool
	)
	c := &cobra.Command{
		Use:   "create",
		Short: "create custom_dimensions",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("name") {
				fields["name"] = fName
			}
			if cmd.Flags().Changed("tag-key") {
				fields["tag_key"] = fTagKey
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.BillAnalysisCustomDimensionsCreateJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			writePlan := map[string]any{"method": "POST /bill-analysis/orgs/{orgId}/custom/dimensions"}
			writePlan["orgId"] = deps.Config.OrgID
			writePlan["body"] = json.RawMessage(raw)
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, false, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.BillAnalysisCustomDimensionsCreateWithResponse(cmd.Context(), int64(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringVar(&fName, "name", "", "name (body)")
	c.Flags().StringVar(&fTagKey, "tag-key", "", "tag_key (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newCustomDimensionsDeleteCmd — DELETE /bill-analysis/orgs/{orgId}/custom/dimensions/{id} (operationId: BillAnalysis_custom_dimensions_destroy)
func newCustomDimensionsDeleteCmd() *cobra.Command {
	var (
		id     string
		dryRun bool
		yes    bool
	)
	c := &cobra.Command{
		Use:   "delete",
		Short: "destroy custom_dimensions",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			writePlan := map[string]any{"method": "DELETE /bill-analysis/orgs/{orgId}/custom/dimensions/{id}"}
			writePlan["orgId"] = deps.Config.OrgID
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, true, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.BillAnalysisCustomDimensionsDestroyWithResponse(cmd.Context(), int64(deps.Config.OrgID), id)
			if err != nil {
				return err
			}
			if resp.StatusCode() != 204 {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			fmt.Fprintln(deps.Stdout, "OK")
			return nil
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newCustomDimensionsGetCmd — GET /bill-analysis/orgs/{orgId}/custom/dimensions/{id} (operationId: BillAnalysis_custom_dimensions_show)
func newCustomDimensionsGetCmd() *cobra.Command {
	var (
		id string
	)
	c := &cobra.Command{
		Use:   "get",
		Short: "show custom_dimensions",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			resp, err := client.BillAnalysisCustomDimensionsShowWithResponse(cmd.Context(), int64(deps.Config.OrgID), id)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	return c
}

// newCustomDimensionsListCmd — GET /bill-analysis/orgs/{orgId}/custom/dimensions (operationId: BillAnalysis_custom_dimensions_index)
func newCustomDimensionsListCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "list",
		Short: "index custom_dimensions",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.BillAnalysisCustomDimensionsIndexWithResponse(cmd.Context(), int64(deps.Config.OrgID))
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	return c
}

// newCustomDimensionsReplaceCmd — PUT /bill-analysis/orgs/{orgId}/custom/dimensions/{id} (operationId: BillAnalysis_custom_dimensions_replace)
func newCustomDimensionsReplaceCmd() *cobra.Command {
	var (
		id      string
		bodyRaw string
		fName   string
		fTagKey string
		dryRun  bool
		yes     bool
	)
	c := &cobra.Command{
		Use:   "replace",
		Short: "replace custom_dimensions",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(id) == "" {
				return fmt.Errorf("--id is required")
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("name") {
				fields["name"] = fName
			}
			if cmd.Flags().Changed("tag-key") {
				fields["tag_key"] = fTagKey
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.BillAnalysisCustomDimensionsReplaceJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			writePlan := map[string]any{"method": "PUT /bill-analysis/orgs/{orgId}/custom/dimensions/{id}"}
			writePlan["orgId"] = deps.Config.OrgID
			writePlan["body"] = json.RawMessage(raw)
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, false, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.BillAnalysisCustomDimensionsReplaceWithResponse(cmd.Context(), int64(deps.Config.OrgID), id, body)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringVar(&id, "id", "", "id (path, required)")
	c.Flags().StringVar(&fName, "name", "", "name (body)")
	c.Flags().StringVar(&fTagKey, "tag-key", "", "tag_key (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}
