// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag Connector.

package connector

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "connector" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "connector",
		Short: "Connector operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newConnectorGetCmd(),
		newConnectorListCmd(),
		newConnectorCountCmd(),
		newConnectorStatusCmd(),
	)
	return c
}

// newConnectorGetCmd — GET /uobs/v1/orgs/{org_id}/cloud/connectors/{identifier} (operationId: Uobs_get_connector_uobs_v1_orgs_org_id_cloud_connectors_identifier_get)
func newConnectorGetCmd() *cobra.Command {
	var (
		identifier string
	)
	c := &cobra.Command{
		Use:         "get",
		Short:       "Get information about a onboarded connector",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli unified-onboarding connector get --org-id ORG_ID --identifier IDENTIFIER",
		Annotations: map[string]string{"flexera.operationId": "Uobs_get_connector_uobs_v1_orgs_org_id_cloud_connectors_identifier_get", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Uobs_get_connector_uobs_v1_orgs_org_id_cloud_connectors_identifier_get")
			if err != nil {
				return err
			}
			_ = effectiveParams
			if strings.TrimSpace(identifier) == "" {
				return fmt.Errorf("--identifier is required")
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.UobsGetConnectorUobsV1OrgsOrgIdCloudConnectorsIdentifierGetWithResponse(cmd.Context(), fmt.Sprint(deps.Config.OrgID), identifier)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&identifier, "identifier", "", "identifier (path, required)")
	return c
}

// newConnectorListCmd — GET /uobs/v1/orgs/{org_id}/cloud/connectors (operationId: Uobs_list_connectors_uobs_v1_orgs_org_id_cloud_connectors_get)
func newConnectorListCmd() *cobra.Command {
	var (
		limit  int
		offset int
		filter string
	)
	c := &cobra.Command{
		Use:         "list",
		Short:       "List connectors for cloud Accounts in the Organization",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli unified-onboarding connector list --org-id ORG_ID",
		Annotations: map[string]string{"flexera.operationId": "Uobs_list_connectors_uobs_v1_orgs_org_id_cloud_connectors_get", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Uobs_list_connectors_uobs_v1_orgs_org_id_cloud_connectors_get")
			if err != nil {
				return err
			}
			_ = effectiveParams
			params := flexera.UobsListConnectorsUobsV1OrgsOrgIdCloudConnectorsGetParams{}
			if cmd.Flags().Changed("limit") {
				v := limit
				params.Limit = &v
			}
			if cmd.Flags().Changed("offset") {
				v := offset
				params.Offset = &v
			}
			if cmd.Flags().Changed("filter") {
				v := filter
				params.Filter = &v
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.UobsListConnectorsUobsV1OrgsOrgIdCloudConnectorsGetWithResponse(cmd.Context(), fmt.Sprint(deps.Config.OrgID), &params)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().IntVar(&limit, "limit", 0, "limit (query)")
	c.Flags().IntVar(&offset, "offset", 0, "offset (query)")
	c.Flags().StringVar(&filter, "filter", "", "filter (query)")
	return c
}

// newConnectorCountCmd — GET /uobs/v1/orgs/{org_id}/cloud/connectors/count (operationId: Uobs_get_connectors_count_uobs_v1_orgs_org_id_cloud_connectors_count_get)
func newConnectorCountCmd() *cobra.Command {
	c := &cobra.Command{
		Use:         "count",
		Short:       "Get connectors count by provider",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli unified-onboarding connector count --org-id ORG_ID",
		Annotations: map[string]string{"flexera.operationId": "Uobs_get_connectors_count_uobs_v1_orgs_org_id_cloud_connectors_count_get", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Uobs_get_connectors_count_uobs_v1_orgs_org_id_cloud_connectors_count_get")
			if err != nil {
				return err
			}
			_ = effectiveParams
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.UobsGetConnectorsCountUobsV1OrgsOrgIdCloudConnectorsCountGetWithResponse(cmd.Context(), fmt.Sprint(deps.Config.OrgID))
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	return c
}

// newConnectorStatusCmd — GET /uobs/v1/orgs/{org_id}/cloud/connectors/status (operationId: Uobs_get_connector_status_uobs_v1_orgs_org_id_cloud_connectors_status_get)
func newConnectorStatusCmd() *cobra.Command {
	var (
		connectorID string
		accountID   string
	)
	c := &cobra.Command{
		Use:         "status",
		Short:       "Get status for all enabled products for a given connector",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli unified-onboarding connector status --org-id ORG_ID --connector-id CONNECTOR_ID",
		Annotations: map[string]string{"flexera.operationId": "Uobs_get_connector_status_uobs_v1_orgs_org_id_cloud_connectors_status_get", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Uobs_get_connector_status_uobs_v1_orgs_org_id_cloud_connectors_status_get")
			if err != nil {
				return err
			}
			_ = effectiveParams
			params := flexera.UobsGetConnectorStatusUobsV1OrgsOrgIdCloudConnectorsStatusGetParams{}
			if cmd.Flags().Changed("connector-id") {
				params.ConnectorId = connectorID
			}
			if cmd.Flags().Changed("account-id") {
				v := accountID
				params.AccountId = &v
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.UobsGetConnectorStatusUobsV1OrgsOrgIdCloudConnectorsStatusGetWithResponse(cmd.Context(), fmt.Sprint(deps.Config.OrgID), &params)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&connectorID, "connector-id", "", "connector_id (query)")
	c.Flags().StringVar(&accountID, "account-id", "", "account_id (query)")
	return c
}
