// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag costs.

package costs

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "costs" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "costs",
		Short: "costs operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newCostsAggregatedCmd(),
		newCostsCreateExportCmd(),
		newCostsCreateSelectCmd(),
		newCostsGetCmd(),
		newCostsDimensionsCmd(),
		newCostsMetricsCmd(),
	)
	return c
}

// newCostsAggregatedCmd — POST /bill-analysis/orgs/{orgId}/costs/aggregated (operationId: BillAnalysis_costs_aggregated)
func newCostsAggregatedCmd() *cobra.Command {
	var (
		bodyRaw           string
		fBillingCenterIDs []string
		fDimensions       []string
		fEndAt            string
		fGranularity      string
		fLimit            int64
		fMetrics          []string
		fPeriodType       string
		fStartAt          string
		fSummarized       bool
		dryRun            bool
		yes               bool
	)
	c := &cobra.Command{
		Use:   "aggregated",
		Short: "aggregated costs",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("billing-center-ids") {
				fields["billing_center_ids"] = fBillingCenterIDs
			}
			if cmd.Flags().Changed("dimensions") {
				fields["dimensions"] = fDimensions
			}
			if cmd.Flags().Changed("end-at") {
				fields["end_at"] = fEndAt
			}
			if cmd.Flags().Changed("granularity") {
				fields["granularity"] = fGranularity
			}
			if cmd.Flags().Changed("limit") {
				fields["limit"] = fLimit
			}
			if cmd.Flags().Changed("metrics") {
				fields["metrics"] = fMetrics
			}
			if cmd.Flags().Changed("period-type") {
				fields["period_type"] = fPeriodType
			}
			if cmd.Flags().Changed("start-at") {
				fields["start_at"] = fStartAt
			}
			if cmd.Flags().Changed("summarized") {
				fields["summarized"] = fSummarized
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.BillAnalysisCostsAggregatedJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			writePlan := map[string]any{"method": "POST /bill-analysis/orgs/{orgId}/costs/aggregated"}
			writePlan["orgId"] = deps.Config.OrgID
			writePlan["body"] = json.RawMessage(raw)
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, false, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.BillAnalysisCostsAggregatedWithResponse(cmd.Context(), int64(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringSliceVar(&fBillingCenterIDs, "billing-center-ids", nil, "billing_center_ids (body)")
	c.Flags().StringSliceVar(&fDimensions, "dimensions", nil, "dimensions (body)")
	c.Flags().StringVar(&fEndAt, "end-at", "", "end_at (body)")
	c.Flags().StringVar(&fGranularity, "granularity", "", "granularity (body)")
	c.Flags().Int64Var(&fLimit, "limit", 0, "limit (body)")
	c.Flags().StringSliceVar(&fMetrics, "metrics", nil, "metrics (body)")
	c.Flags().StringVar(&fPeriodType, "period-type", "", "period_type (body)")
	c.Flags().StringVar(&fStartAt, "start-at", "", "start_at (body)")
	c.Flags().BoolVar(&fSummarized, "summarized", false, "summarized (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newCostsCreateExportCmd — POST /bill-analysis/orgs/{orgId}/costs/export/select (operationId: BillAnalysis_costs_exportSelect)
func newCostsCreateExportCmd() *cobra.Command {
	var (
		bodyRaw                         string
		fAdjDimensionGranularity        string
		fAggregateToRequestedDimensions bool
		fBillingCenterIDs               []string
		fDimensions                     []string
		fEndAt                          string
		fGranularity                    string
		fMetrics                        []string
		fStartAt                        string
		dryRun                          bool
		yes                             bool
	)
	c := &cobra.Command{
		Use:   "create-export",
		Short: "exportSelect costs",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("adj-dimension-granularity") {
				fields["adj_dimension_granularity"] = fAdjDimensionGranularity
			}
			if cmd.Flags().Changed("aggregate-to-requested-dimensions") {
				fields["aggregate_to_requested_dimensions"] = fAggregateToRequestedDimensions
			}
			if cmd.Flags().Changed("billing-center-ids") {
				fields["billing_center_ids"] = fBillingCenterIDs
			}
			if cmd.Flags().Changed("dimensions") {
				fields["dimensions"] = fDimensions
			}
			if cmd.Flags().Changed("end-at") {
				fields["end_at"] = fEndAt
			}
			if cmd.Flags().Changed("granularity") {
				fields["granularity"] = fGranularity
			}
			if cmd.Flags().Changed("metrics") {
				fields["metrics"] = fMetrics
			}
			if cmd.Flags().Changed("start-at") {
				fields["start_at"] = fStartAt
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.BillAnalysisCostsExportSelectJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			writePlan := map[string]any{"method": "POST /bill-analysis/orgs/{orgId}/costs/export/select"}
			writePlan["orgId"] = deps.Config.OrgID
			writePlan["body"] = json.RawMessage(raw)
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, false, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.BillAnalysisCostsExportSelectWithResponse(cmd.Context(), int64(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringVar(&fAdjDimensionGranularity, "adj-dimension-granularity", "", "adj_dimension_granularity (body)")
	c.Flags().BoolVar(&fAggregateToRequestedDimensions, "aggregate-to-requested-dimensions", false, "aggregate_to_requested_dimensions (body)")
	c.Flags().StringSliceVar(&fBillingCenterIDs, "billing-center-ids", nil, "billing_center_ids (body)")
	c.Flags().StringSliceVar(&fDimensions, "dimensions", nil, "dimensions (body)")
	c.Flags().StringVar(&fEndAt, "end-at", "", "end_at (body)")
	c.Flags().StringVar(&fGranularity, "granularity", "", "granularity (body)")
	c.Flags().StringSliceVar(&fMetrics, "metrics", nil, "metrics (body)")
	c.Flags().StringVar(&fStartAt, "start-at", "", "start_at (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newCostsCreateSelectCmd — POST /bill-analysis/orgs/{orgId}/costs/select (operationId: BillAnalysis_costs_select)
func newCostsCreateSelectCmd() *cobra.Command {
	var (
		bodyRaw           string
		fBillingCenterIDs []string
		fDimensions       []string
		fEndAt            string
		fGranularity      string
		fLimit            int64
		fMetrics          []string
		fPeriodType       string
		fStartAt          string
		dryRun            bool
		yes               bool
	)
	c := &cobra.Command{
		Use:   "create-select",
		Short: "select costs",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			fields := map[string]any{}
			if cmd.Flags().Changed("billing-center-ids") {
				fields["billing_center_ids"] = fBillingCenterIDs
			}
			if cmd.Flags().Changed("dimensions") {
				fields["dimensions"] = fDimensions
			}
			if cmd.Flags().Changed("end-at") {
				fields["end_at"] = fEndAt
			}
			if cmd.Flags().Changed("granularity") {
				fields["granularity"] = fGranularity
			}
			if cmd.Flags().Changed("limit") {
				fields["limit"] = fLimit
			}
			if cmd.Flags().Changed("metrics") {
				fields["metrics"] = fMetrics
			}
			if cmd.Flags().Changed("period-type") {
				fields["period_type"] = fPeriodType
			}
			if cmd.Flags().Changed("start-at") {
				fields["start_at"] = fStartAt
			}
			var typed any
			if len(fields) > 0 {
				typed = fields
			}
			raw, err := clipkg.ResolveBody(bodyRaw, typed, cmd.InOrStdin())
			if err != nil {
				return err
			}
			if len(raw) == 0 {
				return fmt.Errorf("a request body is required: pass --body (inline JSON, @file, or @-) or the body field flags")
			}
			var body flexera.BillAnalysisCostsSelectJSONRequestBody
			if err := json.Unmarshal(raw, &body); err != nil {
				return fmt.Errorf("decoding request body: %w", err)
			}
			writePlan := map[string]any{"method": "POST /bill-analysis/orgs/{orgId}/costs/select"}
			writePlan["orgId"] = deps.Config.OrgID
			writePlan["body"] = json.RawMessage(raw)
			if writeDone, werr := clipkg.ConfirmWrite(dryRun, yes, false, deps.Stdout, writePlan); werr != nil {
				return werr
			} else if writeDone {
				return nil
			}
			resp, err := client.BillAnalysisCostsSelectWithResponse(cmd.Context(), int64(deps.Config.OrgID), body)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringSliceVar(&fBillingCenterIDs, "billing-center-ids", nil, "billing_center_ids (body)")
	c.Flags().StringSliceVar(&fDimensions, "dimensions", nil, "dimensions (body)")
	c.Flags().StringVar(&fEndAt, "end-at", "", "end_at (body)")
	c.Flags().StringVar(&fGranularity, "granularity", "", "granularity (body)")
	c.Flags().Int64Var(&fLimit, "limit", 0, "limit (body)")
	c.Flags().StringSliceVar(&fMetrics, "metrics", nil, "metrics (body)")
	c.Flags().StringVar(&fPeriodType, "period-type", "", "period_type (body)")
	c.Flags().StringVar(&fStartAt, "start-at", "", "start_at (body)")
	c.Flags().StringVar(&bodyRaw, "body", "", "raw JSON body (inline | @file | @-); overrides body field flags")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "print the planned operation as JSON and exit without calling the API")
	c.Flags().BoolVar(&yes, "yes", false, "confirm the operation (required for destructive ops)")
	return c
}

// newCostsGetCmd — GET /bill-analysis/orgs/{orgId}/costs/export/select/{exportId} (operationId: BillAnalysis_costs_exportSelectStatus)
func newCostsGetCmd() *cobra.Command {
	var (
		exportID string
	)
	c := &cobra.Command{
		Use:   "get",
		Short: "exportSelectStatus costs",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			if strings.TrimSpace(exportID) == "" {
				return fmt.Errorf("--export-id is required")
			}
			resp, err := client.BillAnalysisCostsExportSelectStatusWithResponse(cmd.Context(), int64(deps.Config.OrgID), exportID)
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	c.Flags().StringVar(&exportID, "export-id", "", "exportId (path, required)")
	return c
}

// newCostsDimensionsCmd — GET /bill-analysis/orgs/{orgId}/costs/dimensions (operationId: BillAnalysis_costs_dimensions)
func newCostsDimensionsCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "dimensions",
		Short: "dimensions costs",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.BillAnalysisCostsDimensionsWithResponse(cmd.Context(), int64(deps.Config.OrgID))
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	return c
}

// newCostsMetricsCmd — GET /bill-analysis/orgs/{orgId}/costs/metrics (operationId: BillAnalysis_costs_metrics)
func newCostsMetricsCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "metrics",
		Short: "metrics costs",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := clipkg.DepsFrom(cmd.Context())
			if err := deps.Config.RequireOrgID(); err != nil {
				return err
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.BillAnalysisCostsMetricsWithResponse(cmd.Context(), int64(deps.Config.OrgID))
			if err != nil {
				return err
			}
			if resp.JSON200 == nil {
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
		},
	}
	return c
}
