// Code generated by cmd/gencli. DO NOT EDIT.
// Source: unified OpenAPI spec, tag Incident Aggregate.

package incidentaggregate

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	clipkg "github.com/flexera-public/flexera-cli/internal/cli"
	flexera "github.com/flexera-public/unified-go-client"
)

var (
	_ = context.Background
	_ = json.Unmarshal
	_ = fmt.Sprint
	_ = strings.TrimSpace
)

// NewCmd builds the "incident-aggregate" command tree.
func NewCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "incident-aggregate",
		Short: "Incident Aggregate operations (generated from the unified OpenAPI spec)",
	}
	c.AddCommand(
		newIncidentAggregateGetCmd(),
		newIncidentAggregateListCmd(),
	)
	return c
}

// newIncidentAggregateGetCmd — GET /policy/v1/orgs/{orgId}/incident-aggregates/{incidentAggregateId} (operationId: Policy_Incident_Aggregate_show)
func newIncidentAggregateGetCmd() *cobra.Command {
	var (
		incidentAggregateID string
		view                string
	)
	c := &cobra.Command{
		Use:         "get",
		Short:       "Show an incident aggregate.",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli policy incident-aggregate get --org-id ORG_ID --incident-aggregate-id INCIDENT_AGGREGATE_ID",
		Annotations: map[string]string{"flexera.operationId": "Policy_Incident_Aggregate_show", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Policy_Incident_Aggregate_show")
			if err != nil {
				return err
			}
			_ = effectiveParams
			if strings.TrimSpace(incidentAggregateID) == "" {
				return fmt.Errorf("--incident-aggregate-id is required")
			}
			params := flexera.PolicyIncidentAggregateShowParams{}
			if cmd.Flags().Changed("view") {
				ev := flexera.PolicyIncidentAggregateShowParamsView(view)
				params.View = &ev
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			resp, err := client.PolicyIncidentAggregateShowWithResponse(cmd.Context(), int64(deps.Config.OrgID), incidentAggregateID, &params)
			if err != nil {
				return err
			}
			switch resp.StatusCode() {
			case 200:
				if resp.JSON200 == nil {
					return flexera.ResponseError(resp.StatusCode(), resp.Body)
				}
				if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
					return deps.Printer.Render(deps.Stdout, deps.Config.Output, resp.JSON200)
				}
				result, err := clipkg.DecodeResponseJSON(resp.Body)
				if err != nil {
					return err
				}
				return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
			default:
				return flexera.ResponseError(resp.StatusCode(), resp.Body)
			}
		},
	}
	c.Flags().StringVar(&incidentAggregateID, "incident-aggregate-id", "", "incidentAggregateId (path, required)")
	c.Flags().StringVar(&view, "view", "", "view (query)")
	return c
}

// newIncidentAggregateListCmd — GET /policy/v1/orgs/{orgId}/incident-aggregates (operationId: Policy_Incident_Aggregate_index)
func newIncidentAggregateListCmd() *cobra.Command {
	var (
		filter     string
		orderBy    string
		limit      int64
		view       string
		noPaginate bool
		skipToken  string
	)
	c := &cobra.Command{
		Use:         "list",
		Short:       "Index incident aggregates.",
		Example:     "Illustrative only: replace uppercase tokens; provide your own request.json for body input.\n  flexera-cli policy incident-aggregate list --org-id ORG_ID",
		Annotations: map[string]string{"flexera.operationId": "Policy_Incident_Aggregate_index", "flexera.output": "structured", "flexera.validation": "params"},
		Args:        cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Parse formatted query flags before client creation/authentication.
			deps := clipkg.DepsFrom(cmd.Context())
			effectiveParams, err := clipkg.ValidateCommandParams(cmd, "Policy_Incident_Aggregate_index")
			if err != nil {
				return err
			}
			_ = effectiveParams
			params := flexera.PolicyIncidentAggregateIndexParams{}
			if cmd.Flags().Changed("filter") {
				v := filter
				params.Filter = &v
			}
			if cmd.Flags().Changed("order-by") {
				v := orderBy
				params.OrderBy = &v
			}
			if cmd.Flags().Changed("limit") {
				v := limit
				params.Limit = &v
			}
			if cmd.Flags().Changed("view") {
				ev := flexera.PolicyIncidentAggregateIndexParamsView(view)
				params.View = &ev
			}
			client, err := deps.APIClient()
			if err != nil {
				return err
			}
			var initialSkipToken *string
			if t := strings.TrimSpace(skipToken); t != "" {
				initialSkipToken = &t
			}
			result, err := flexera.CollectPages(cmd.Context(), noPaginate, initialSkipToken,
				func(ctx context.Context, st *string) (any, error) {
					p := params
					p.SkipToken = st
					resp, callErr := client.PolicyIncidentAggregateIndexWithResponse(ctx, int64(deps.Config.OrgID), &p)
					if callErr != nil {
						return nil, callErr
					}
					switch resp.StatusCode() {
					case 200:
						if resp.JSON200 != nil {
							if deps.Config.Output == "table" && deps.Printer.JQ == nil && len(deps.Printer.Fields) == 0 {
								return resp.JSON200, nil
							}
							return clipkg.DecodeResponseJSON(resp.Body)
						}
					}
					return nil, flexera.ResponseError(resp.StatusCode(), resp.Body)
				})
			if err != nil {
				return err
			}
			return deps.Printer.Render(deps.Stdout, deps.Config.Output, result)
		},
	}
	c.Flags().StringVar(&filter, "filter", "", "filter (query)")
	c.Flags().StringVar(&orderBy, "order-by", "", "orderBy (query)")
	c.Flags().Int64Var(&limit, "limit", 0, "limit (query)")
	c.Flags().StringVar(&view, "view", "", "view (query)")
	c.Flags().BoolVar(&noPaginate, "no-paginate", false, "return only the first page (do not follow nextPage)")
	c.Flags().StringVar(&skipToken, "skip-token", "", "resume pagination from this token")
	return c
}
